### ISSUE TITLE
🐞 [Bug] Farmerbot: what's the correct wake_up_threshold format? 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#1001]
### What happened?

farmerbot (v0.15.1)

I followed the template as here: https://github.com/threefoldtech/tfgrid-sdk-go/blob/development/farmerbot/README.md#config, and got this error: `error="yaml: unmarshal errors:\n  line 8: cannot unmarshal !!map into uint8"`

I tried replacing cru: 70 with cru: "70" but still got the same error again.

### which network/s did you face the problem on?

QA

### Relevant log output

```console
farm_id: 180
excluded_nodes:
  - 27
power:
  periodic_wake_up_start: "04:30PM"
  overprovision_cpu: 1
  wake_up_threshold:
    cru: 70
```

**Comment by rawdaGastan** [comment]
This is a newer version document, and it is not released yet
the right doc for `v0.15.1` is: https://github.com/threefoldtech/tfgrid-sdk-go/tree/v0.15.1/farmerbot#config

**Comment by A-Harby** [comment]
Thanks for the clarification.
