### ISSUE TITLE
Unusual number of wake up calls under farmerbot management

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/tfgrid-sdk-go#1008]
- Fbot version: v0.15.0.
- Farm ID: 429 

- The following nodes: 1642, 2991, 6472 have been receiving an unusual amount of wake up calls ranging up to 8 wake ups in a day. From the logs these do not look to be random wake up calls as well (given that we understand it's 10 times a month). Logs attached for 8th May (issue reported).

[farmerbot_farm429.log](https://github.com/threefoldtech/tfgrid-sdk-go/files/15253042/farmerbot_farm429.log)

No issues with config:
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/105203696/c25d2506-fb9f-407f-8c79-ec22d3b50336)

**Comment by rawdaGastan** [comment]
Is the problem still reproducible ?

**Comment by TullysInc** [comment]
> Is the problem still reproducible ?

I don't see further reports from the farmer. We can close the issue.
