### ISSUE TITLE
Farmerbot Disclaimer Before Installation

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/tfgrid-sdk-go#1009]
### Is your feature request related to a problem? Please describe

As discussed with @despiegk today, we propose to add a disclaimer when a farmer sets the farmerbot. This disclaimer would mention that the farmerbot is optional and that TF is not responsible for any loss in minting rewards if the farmers use the farmerbot.

This feature would be integrated for the next release (asap).

@xmonader If you can have a look please! Thanks.

### Describe the solution you'd like

# Farmers POV

- When you run the farmerbot for the first time, there is a disclaimer and the farmers must answer yes/no. If no, the farmerbot installation stops. If yes, the installation continues
- This ensures that farmers know that the farmerbot is optional and that it can affect minting rewards and that threefold is not responsible for minting reward losses.
- We propose to use the same template disclaimer that we put on the manual [here](https://manual.grid.tf/documentation/farmers/farmerbot/farmerbot_intro.html)

> Warning: The Farmerbot is an optional feature developed by ThreeFold. Use at your own risk. While ThreeFold will do its best to fix any issues with the Farmerbot and minting, if minting is affected by the use of the Farmerbot, ThreeFold cannot be held responsible. Do you wish to proceed? (yes/no)

---

# Notes

Feedback welcome on how to best proceed with this.

**Comment by xmonader** [comment]
make sure to add flag --auto-approve to disable the interactive answer of yes/no for people who want to automate it
