### ISSUE TITLE
support filtering with node status list

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/tfgrid-sdk-go#1010]
### Is your feature request related to a problem? Please describe

support filtering with list when possible. it is now available for `nodes?farm_ids` and `contracts?state=`

### Describe the solution you'd like

other filters can take a list too like `nodes?status=` and others

**Comment by Eslam-Nawara** [comment]
Verified: 
I queried multiple cases

- status list [up, down] https://gridproxy.dev.grid.tf/nodes?size=99999&status=up,down

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/7476f3cf-6419-4d15-9c90-7d01228c225e)
the returned nodes had no standby nodes
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/b0624fd2-aa98-4200-aa6b-b99ae4e2951b)

- status list [standby, down] https://gridproxy.dev.grid.tf/nodes?size=99999&status=up,down

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/29abd257-8028-4168-a2ae-091d031da95a)

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/583f4860-80b9-42d3-8696-79e0ee67e18c)
