### ISSUE TITLE
Add validations for included, excluded and priority nodes

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/tfgrid-sdk-go#1017]
### Is your feature request related to a problem? Please describe

To make sure config file is valid, so farmer could notice if the date is wrong or messy

### Describe the solution you'd like

Add validations for included, excluded and priority nodes

**Comment by A-Harby** [comment]
Qanet v0.15.10.

Input validation is working correctly.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/621a0ddc-4f4c-455e-8191-eb6ebdfdc71c)

Updated validation to all cases.
[TC2718 - Farmer Bot Installation with priority_nodes](https://app.testlodge.com/a/26076/projects/40893/suites/221831?expand_section=382401#case_4295012)
[TC2472 - Farmer Bot Installation with excluded_nodes](https://app.testlodge.com/a/26076/projects/40893/suites/221831?expand_section=382401#case_4187496)
[TC2466 - Farmer Bot Installation with never_shutdown_nodes](https://app.testlodge.com/a/26076/projects/40893/suites/221831?expand_section=382401#case_4187407)

**Comment by A-Harby** [comment]
But the node priority needs a validation on the node ID to check if it is on the same farm or not.

Farm 180 doesn't have node 291.
```
farm_id: 180
included_nodes:
  - 26
  - 28
  - 29
excluded_nodes:
  - 27
priority_nodes:
  - 291
```
The Famerbot is stuck on this error. 
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/d3ad9671-bd73-4ed1-90a6-c176aac694aa)

**Comment by SalmaElsoly** [comment]
added nodes validation:
- included, excluded and priority nodes are in the farm
- priority nodes are subset of included nodes
- no overlapping nodes between included and excluded
- no overlapping nodes between priority and excluded

**Comment by SalmaElsoly** [comment]
- added never shutdown validation
- handled case of all nodes of the farm included
