### ISSUE TITLE
Mark the node as dedicated if it has extra fee set

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-go#1023]
### Is your feature request related to a problem? Please describe

Parent issue: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2490
The users can create and deploy workloads on the nodes that have extra fees. These nodes mostly have GPU cards so it's meant to be rented first before deploying any workload on it.

### Describe the solution you'd like

Mark the node as dedicated if the extra fee > 0

**Comment by AhmedHanafy725** [comment]
please take this extra fee into account in the `available_for` filter

**Comment by Omarabdul3ziz** [comment]
@AhmedHanafy725  tracked on another issue https://github.com/threefoldtech/tfgrid-sdk-go/issues/1060

**Comment by ashraffouda** [comment]
done
