### ISSUE TITLE
Sort farms by free_ips

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-go#1025]
### Is your feature request related to a problem? Please describe

https://github.com/threefoldtech/tfchain_graphql/issues/83#issuecomment-2122599320

### Describe the solution you'd like

-

**Comment by rawdaGastan** [comment]
### Verifications

- You can now sort by `free_ips`, `total_ips` and `used_ips`

![image](https://github.com/user-attachments/assets/7942edf9-45ae-4b73-86e8-6d82d960c638)

- You can execute https://gridproxy.dev.grid.tf/farms?sort_by=free_ips
- You can execute https://gridproxy.dev.grid.tf/farms?sort_by=used_ips
- You can execute https://gridproxy.dev.grid.tf/farms?sort_by=total_ips

**Comment by rawdaGastan** [comment]
Why `free_farm` is not included in sorting?

**Comment by rawdaGastan** [comment]
Found it in another page
