### ISSUE TITLE
"free_cru" is not a sort filed for Node type

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#1033]
https://gridproxy.grid.tf/nodes?page=1&size=20&ret_count=true&status=up&free_mru=17179869184&free_sru=54760833024&sort_by=free_cru&sort_order=desc

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/64129/3ca13699-4795-4ca3-ba97-e97222f04b47)

also change filed to field.

**Comment by Omarabdul3ziz** [comment]
the feature doesn't reach mainnet yet, sorting nodes with `free_cru` is part of the `v0.15.1` release, mainnet still has `v0.14.14`
