### ISSUE TITLE
🐞 [Bug]: tfrobot workflow failed due to rmb panic

### ISSUE THREAD

**Issue by Eslam-Nawara** [threefoldtech/tfgrid-sdk-go#1038]
### What happened?

tfrobot nightly workflow failed due to rmb panic
https://github.com/threefoldtech/tfgrid-sdk-go/actions/runs/9249134007/job/25440491988

### which network/s did you face the problem on?

Main

### Version

latest

### Relevant log output

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/fbe56a36-7afd-4e44-8cc5-8f11531fd75c)

**Comment by rawdaGastan** [comment]
It is working now: 
https://github.com/threefoldtech/tfgrid-sdk-go/actions/runs/9280182204/job/25534022738
