### ISSUE TITLE
🐞 [Bug]: can't ping nodes in mainnet

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/tfgrid-sdk-go#1057]
### What happened?

Can't ping nodes in main net

### which network/s did you face the problem on?

Main

### Node ID/s

1, 13

### Farm ID/s

1

### Relevant log output

![Screenshot from 2024-06-03 13-59-29](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/6e01b4d9-53cc-4f90-a2a9-a2415d0809f2)

**Comment by ashraffouda** [comment]
can not reproduce, just checked with the node ids above seems working properly. maybe a network issue or so
