### ISSUE TITLE
support the node status from the node power

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-go#106]
## Is your feature request related to a problem? Please describe
We need to give the user the updated state of the node in weblet
 - https://github.com/threefoldtech/tfgrid-sdk-ts/issues/78

## Describe the solution you'd like
the node status should depend on both the current node status and power state

graphql query, may it help
````
query MyQuery {
  nodes {
    power {
      state
      target
    }
  }
}
````

**Comment by AhmedHanafy725** [comment]
the target is to have one more status for the nodes which is `standby`. this status indicates that the node is powered off by the farmerbot

**Comment by xmonader** [comment]
at the time of verification https://gridproxy.dev.grid.tf/nodes?status=standby

resulted
```
[{"id":"0005592547-000002-c2f32","nodeId":88,"farmId":52,"twinId":26,"country":"Egypt","gridVersion":5,"city":"Cairo","uptime":0,"created":1682834604,"farmingPolicyId":1,"updatedAt":1682834604,"total_resources":{"cru":4,"sru":1000000000000,"hru":10000000000000,"mru":10000000000},"used_resources":{"cru":0,"sru":107374182400,"hru":0,"mru":2147483648},"location":{"country":"Egypt","city":"Cairo","longitude":31.477898,"latitude":30.005493},"publicConfig":{"domain":"","gw4":"","gw6":"","ipv4":"","ipv6":""},"status":"standby","certificationType":"Diy","dedicated":false,"rentContractId":0,"rentedByTwinId":0,"serialNumber":"Unknown","power":{"state":"Up","target":"Down"}}]
```

**Comment by xmonader** [comment]
reopened 
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/64129/f7da89c6-e43e-408f-beb9-f24947b82b08)

swagger docs missing the standby option

**Comment by Omarabdul3ziz** [comment]
added swagger docs, and the new changes are deployed now

**Comment by A-Harby** [comment]
Verified the swagger docs are updated. 
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/69c51810-5287-408a-b63e-6206510605e5)
