### ISSUE TITLE
🐞 [Bug]: Node 4771 doesn't have any contracts and isn't rentable

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/tfgrid-sdk-go#1061]
### What happened?

Node ```4771``` doesn't have any active contracts or extra fees so it should be rentable, but grid proxy is showing that it's not.
![Screenshot from 2024-06-04 17-09-29](https://github.com/threefoldtech/tfgrid-sdk-go/assets/66883096/681653d8-f508-463b-9fa4-e7205c42419c)

![Screenshot from 2024-06-04 17-09-16](https://github.com/threefoldtech/tfgrid-sdk-go/assets/66883096/a4375087-121f-4204-9112-057541dd06cf)

### which network/s did you face the problem on?

Main

### Node ID/s

4771

### Relevant log output

```console
https://gridproxy.grid.tf/nodes?node_id=4771

https://gridproxy.grid.tf/contracts?state=Created,GracePeriod&node_id=4771
```

**Comment by Omarabdul3ziz** [comment]
here is what is happening
- proxy depends on some cache tables that denormalize the original tables and its data in the cache table is updated by some triggers on each original table involved.
- there looks to be an out-of-sync in the field `node_contracts_count` where the node doesn't have any active contracts but the field still shows it has `4`
  ![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/32527347/916aab51-947e-44a8-bd48-729810956bab)
  > Note: view is just a predefined query that gets executed each time it is called, but `resources_cache` is the table storing the data. it gets filled by the view at the initialization and then updated by the triggers
- what the trigger was doing is just increment/decrement the `node_contracts_count` each time a contract is deleted/created. this should be good and cover all the scenarios that could happen so i have no idea what causes the issue in the first place.
- but if for any unexpected reason, the increment/decrement operation fails once, the data will always be wrong.
- https://github.com/threefoldtech/tfgrid-sdk-go/pull/1064 suggest to re calculate the node_contracts_count each time. this should fix the wrong data found now on the db also somehow guarantee it doesn't happen again
