### ISSUE TITLE
support Farm public ips endpoint

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-go#1067]
### Is your feature request related to a problem? Please describe

.

### Describe the solution you'd like

expose the public ips data to a separate endpoint

**Comment by Omarabdul3ziz** [comment]
like `proxy.dev.grid.tf/publicips` listing all public ips and allow filters by `free` and `farm_id`

**Comment by rawdaGastan** [comment]
### Verification

- swagger docs don't match the endpoint

**Comment by rawdaGastan** [comment]
### Verification

- swagger docs are updated and will be available in the next deployment
