### ISSUE TITLE
add network workload metadata

### ISSUE THREAD

**Issue by mariobassem** [threefoldtech/tfgrid-sdk-go#107]
to be able to rebuild networks without having state, we need to have some information in network workloads. 
information like:
- chosen public node
- user access private key
- AddWGAcess flag (could be deduced from network workloads, but would be nice to have)

**Comment by rawdaGastan** [comment]
isn't it the same as https://github.com/threefoldtech/tfgrid-sdk-go/issues/29 ? 👀
