### ISSUE TITLE
filter for rented by me and rentable nodes

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-go#1078]
### Is your feature request related to a problem? Please describe

I need to get my rented nodes and the rest of the dedicated nodes I can rent before deploy.

### Describe the solution you'd like

if the query doesn't exist please create one.

**Comment by Omarabdul3ziz** [comment]
this should include rentable OR rented_by user twin

**Comment by rawdaGastan** [comment]
### Verification:

- A new query is added `rentable_or_rented_by` to get rented by a twin id or available to rent for this twin
- Tried https://gridproxy.dev.grid.tf/nodes?rentable_or_rented_by=81 and got the available nodes for renting for me (nothing was rented by me)
- Also added to swagger

![image](https://github.com/user-attachments/assets/a08148da-15bd-4b49-8637-b3041bb018f9)
