### ISSUE TITLE
🐞 [Bug] TFRobot: workflow has been failing for a while now 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#1085]
### What happened?

TFRobot has been failing for a while.
https://github.com/threefoldtech/tfgrid-sdk-go/actions/workflows/tfrobot_test.yml

The error: `failed to validate configuration file './example/test.yaml' with error: node group name: 'group_c' is invalid; there should be unique name across all deployments`.

Maybe in one of the workflows, the test failed to delete, the name is now reserved forever, and the workflow will keep failing.
The test needs to generate a random name, and a job after the test is finished is to delete all the contracts, whether the test passes or fails.

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
8:18AM INF starting peer session=tf-4290 twin=10972
8:18AM INF validating configuration file
Error: failed to validate configuration file './example/test.yaml' with error: node group name: 'group_c' is invalid, should be unique name across all deployments
Usage:
  tfrobot deploy [flags]

Flags:
  -c, --config string   path to config file
  -d, --debug           allow debug logs
  -h, --help            help for deploy
  -o, --output string   path to output file (default "output.yaml")

8:18AM FTL error="failed to validate configuration file './example/test.yaml' with error: node group name: 'group_c' is invalid, should be unique name across all deployments"
exit status 1
Error: Process completed with exit code 1.
```

**Comment by rawdaGastan** [comment]
It failed because old contracts exist, will rerun and see

**Comment by rawdaGastan** [comment]
working: https://github.com/threefoldtech/tfgrid-sdk-go/actions/runs/9476629199
