### ISSUE TITLE
🐞 [Bug]: Why are there two binaries of grid CLI in the releases `tfcmd` and `tf-grid-cli`

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#1101]
### What happened?

Why are there two binaries of grid CLI in the releases `tfcmd` and `tf-grid-cli`?

https://github.com/threefoldtech/tfgrid-sdk-go/releases/tag/v0.15.10

v0.15.10

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/81492f5d-5f4b-4ffd-bec9-bbaf63c8e0f0)

### which network/s did you face the problem on?

Dev, Test

### Relevant log output

```console
.
```

**Comment by rawdaGastan** [comment]
Because we agreed to use both names `tfcmd` and `tf-grid-cli` for cli tool

**Comment by A-Harby** [comment]
> Because we agreed to use both names `tfcmd` and `tf-grid-cli` for cli tool

So both are working fine with latest changes?

**Comment by rawdaGastan** [comment]
Yes

**Comment by A-Harby** [comment]
Alright will close the issue then.
