### ISSUE TITLE
🐞 [Bug]: tfcmd zdb --public flag is documented incorrectly

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-go#1105]
The way that the `--public` flag for zdbs deployed with tfcmd is documented is incorrect:

https://github.com/threefoldtech/tfgrid-sdk-go/blob/52fefb57d79763a1f0f712fd42456b8905bc2313/grid-cli/docs/zdb.md?plain=1#L25

What `--public` actually does is make the namespace in the zdb public (that is, readable by anyone). All zdbs get an ipv6 address assigned if the node supports it.

Deploying a zdb is really just the creation of a namespace within an existing zdb that's created by Zos when the node first detects attached HDD. All users of zdb on a given node connect to the same IP/port. So how any user makes a deployment does not affect whether the zdb is reachable by ipv6.

**Comment by rawdaGastan** [comment]
Thanks for the info, updated now

- https://github.com/threefoldtech/tfgrid-sdk-go/blob/6ad6ecb9dbe90fe89fda1f8883094574d41d5db3/grid-cli/docs/zdb.md

**Comment by scottyeager** [comment]
Sure thing. Looks good.
