### ISSUE TITLE
Support multiple stacks per network in sdk-go

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#1113]

**Comment by rawdaGastan** [comment]
Support it for:

- [ ] graphql
- [ ] proxy
- [x] rmb
- [x] chain


PS: already supported in `chain` and `rmb`

**Comment by Omarabdul3ziz** [comment]
verified on proxy and graphql. the support of multiple stacks per network and the shuffle between them if one failed with one of set of errors like timeout/abort
