### ISSUE TITLE
🐞 [Bug]: Error: message signature verification failed: could not verify signature.

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/tfgrid-sdk-go#1124]
### What happened?

After updating TF Grid version 3.14, some farmers report that they are getting an error: message signature verification failed: could not verify signature.
![photo_2024-07-16_03-12-05](https://github.com/user-attachments/assets/9b1896e0-f5bf-4368-b22d-75384d6e4244)

### which network/s did you face the problem on?

Main

### Twin ID/s

946

### Node ID/s

635

### Farm ID/s

3617

### Relevant log output

```console
Error: message signature verification failed: could not verify signature.
```

**Comment by rawdaGastan** [comment]
What is the version of farmerbot?

**Comment by Cameron1986labeyrie** [comment]
@rawdaGastan  The user is on the v0.15.0, the latest one.

**Comment by rawdaGastan** [comment]
`v0.15.10` is the latest one

**Comment by Cameron1986labeyrie** [comment]
@rawdaGastan  Thank you for the update.

**Comment by scottyeager** [comment]
We've seen a few cases so far where updating the version resolved this issue. Some users have yet to update or yet to report back, but it seems that the older version is indeed the issue.
