### ISSUE TITLE
Farms Sorting by Ips

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-go#1125]
### Is your feature request related to a problem? Please describe

Please add sort_by=total, used & free ips for farms 

### Describe the solution you'd like

ability to sort total, used and free ips by ascending and descending order in farms module

**Comment by rawdaGastan** [comment]
### Verifications

- You can now sort by `free_ips`, `total_ips` and `used_ips`

![image](https://github.com/user-attachments/assets/7942edf9-45ae-4b73-86e8-6d82d960c638)

- You can execute https://gridproxy.dev.grid.tf/farms?sort_by=free_ips
- You can execute https://gridproxy.dev.grid.tf/farms?sort_by=used_ips
- You can execute https://gridproxy.dev.grid.tf/farms?sort_by=total_ips
