### ISSUE TITLE
CLI: Add a way to add a worker to Kubernetes

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#1127]
### Is your feature request related to a problem? Please describe

Add a way to add a worker to Kubernetes master using the TFCMD, The only possible way to add workers is to create a new Kubernetes master with workers.

### Describe the solution you'd like

A better option is to add a way to add a worker to an already created master.

**Comment by Eslam-Nawara** [comment]
there's a way to add a worker to kubernetes cluster, check this example [here](https://github.com/threefoldtech/tfgrid-sdk-go/blob/35c3c20a3dcaba8d47d40ddd1c958d6beb5dc54d/grid-client/integration_tests/k8s_test.go#L183)

**Comment by A-Harby** [comment]
> there's a way to add a worker to kubernetes cluster, check this example [here](https://github.com/threefoldtech/tfgrid-sdk-go/blob/35c3c20a3dcaba8d47d40ddd1c958d6beb5dc54d/grid-client/integration_tests/k8s_test.go#L183)

Nice, Can we just mention how-to on the docs?

**Comment by Eslam-Nawara** [comment]
## WIP
- added update command with subcommands to add/delete workers 

will need to add documentation to the new command
