### ISSUE TITLE
Use the same master's filst when adding a new worker to kubernetes cluster

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-go#1158]
https://github.com/threefoldtech/tf-images/issues/292

**Comment by Eslam-Nawara** [comment]
you mean in the cli? @AhmedHanafy725

**Comment by AhmedHanafy725** [comment]
> you mean in the cli? @AhmedHanafy725

everywhere we use kubernetes

**Comment by Omarabdul3ziz** [comment]
couldn't add a new worker to a cluster with cli
![image](https://github.com/user-attachments/assets/09cb275f-c4c1-4a00-ac76-9a1d4947aacd)

**Comment by Eslam-Nawara** [comment]
### Work completed
- After updating k8s node to be a normal vm, this change introduced multiple problems to updating the cli.
- needed to add the network name to all workers
- workers name were not updating right
- loading the cluster didn't load the env vars of the cluster

worked on fixing all the issue and the update is working fine now

**Comment by Omarabdul3ziz** [comment]
verified. new worker added successfully, used the master flist and the env vars returned in the response
