### ISSUE TITLE
Return `free_public_ips_count` on node response

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-go#1160]
### Is your feature request related to a problem? Please describe

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3321

### Describe the solution you'd like

Add `free_public_ips_count` to node response using table joins

**Comment by rawdaGastan** [comment]
### Verification

- A field named `farm_free_ips` is added:
- Tried https://gridproxy.dev.grid.tf/nodes?node_id=11
- Result

![image](https://github.com/user-attachments/assets/ff35128c-3584-404f-9efe-36b6555284b3)

- Added to swagger:

![image](https://github.com/user-attachments/assets/bb7e67f7-65dc-445c-9488-37955dd57fd6)
