### ISSUE TITLE
tfcmd login fails if ~/.config doesn't exist

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-go#1166]
Attempting to login to tfcmd fails when ~/.config doesn't exist:

![image](https://github.com/user-attachments/assets/566a5bb5-0274-4113-98ce-7e2b08fe342c)

I think there's no harm in just creating the folder in that case. But if we don't want to do that for some reason, giving the user a more helpful prompt about how to resolve this would be nice.

**Comment by xmonader** [comment]
@SalmaElsoly Please make sure to do the validation on the necessary configs before running

**Comment by Omarabdul3ziz** [comment]
verified, now it creates the file if not exists
