### ISSUE TITLE
Switch from auto generated GITHUB_TOKEN in goreleaser workflow to PAT

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgrid-sdk-go#117]
## Describe the bug

According to the introduction from the docs about the [GITHUB_TOKEN](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#using-the-github_token-in-a-workflow):

> When you use the repository’s GITHUB_TOKEN to perform tasks on behalf of the GitHub Actions app, events triggered by the GITHUB_TOKEN will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs.

The release created by gorelaser action won't trigger workflows (proxy build) because it use `GITHUB_TOKEN`

https://github.com/threefoldtech/tfgrid-sdk-go/blob/68147e31eb897e0fde44d2a8864514872f5a22d9/.github/workflows/release.yml#LL31C37-L31C49

The solution is to generate a **PAT with write privileges on the target repo** and add it to new secret and use this one in the goreleaser workflow.

more info:
https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow

**Comment by sameh-farouk** [comment]
Also github checkout action use by default github.token/GITHUB_TOKEN which I guess need to be changed as well in the goreleaser workflow and provide the PAT secret  to actions/checkout as its `token` parameter.

**Comment by xmonader** [comment]
please reopen if still needed

**Comment by alichaddad** [comment]
This issue is preventing the automatic trigger of the building and publishing of the proxy image. Right now this workflow needs to be triggered manually. It is also worth checking out if there is a way to generate the release notes through the release workflow since this too is done manually.

**Comment by sameh-farouk** [comment]
closing this one as it should be fixed now in #196
