### ISSUE TITLE
🐞 [Bug]: Error when getting the consumption for a newly created twin

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-go#1186]
### What happened?

when trying to get the consumption of a twin that doesn't have any contracts. it returns an error 
https://gridproxy.dev.grid.tf/twins/8989/consumption

### which network/s did you face the problem on?

Dev

### Twin ID/s

8989

### Version

0.15.15-dev

### Relevant log output

```console
"error": "sql: Scan error on column index 0, name \"sum\": converting NULL to uint64 is unsupported"
```

**Comment by rawdaGastan** [comment]
### Verification

- Created a new account with a twin ID `9670`
- Tried https://gridproxy.dev.grid.tf/twins/9670/consumption

![image](https://github.com/user-attachments/assets/bcac6d92-6827-4aa6-a172-9f9150b0a5a7)

- Got no errors
