### ISSUE TITLE
Add queries for zos4 on nodes/farms endpoint

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-go#1209]
### Is your feature request related to a problem? Please describe

some networks are not supported on zos4 so we need queries to filter them.

### Describe the solution you'd like

add queries for the node if it supports:
- `wireguard`
- `yggdrasil`
- `public ips`

Also, please add them as fields on the node object

same queries should be added too to the farms' queries

**Comment by ashraffouda** [comment]
@Eslam-Nawara we have features now which provide these info, right?
plz add docs on how to use it and link it in the issue

**Comment by Omarabdul3ziz** [comment]
after the discussion, i think having a filter `features` and `node_features` which takes a list of features and filter the nodes that support it will be more suitable for the usecase. 

- `/nodes?features=network,zmachine,zdb`
- `/nodes?features=zmachine-light,network-light`

and in the node response will add the full list of the supported features

no need for wg/ygg/pubIp filters in that case, knowing that network-light nodes doesn't support them. 

is that okay?

**Comment by rawdaGastan** [comment]
### Verifications

- Tried https://gridproxy.dev.grid.tf/nodes?features=zmachine-light,network-light
- Got nodes for light deployments


- Tried https://gridproxy.dev.grid.tf/nodes?features=network,zmachine,zdb
- Got nodes for v3 deployments

- Tried https://gridproxy.dev.grid.tf/farms?node_features=zmachine-light,network-light
- Got farms supports v4 nodes

### Notes

- I found a node with `ipv4` in ight filter
- Not all nodes supports mycelium in light filter too

**Comment by Omarabdul3ziz** [comment]
i suspect it is because some nodes missed the features set update. 


checking https://gridproxy.dev.grid.tf/nodes?features=zmachine-light&status=up only the up nodes (2 now) they both have mycelium and not ipv4 as expected

the other down nodes are
- 1 node in freefarm which last update was 14 days which is before the update
- 3 nodes are a dev nodes. mostly run from source code which hadn't have the update
