### ISSUE TITLE
update Kubernetes solution flist

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/tfgrid-sdk-go#1210]
### Is your feature request related to a problem? Please describe

- according to this issue https://github.com/threefoldtech/tf-images/issues/292 a new image for k3s was requested with the new tag not using latest tag.

### Describe the solution you'd like

- update your used Kubernetes flist to be using this one : https://hub.grid.tf/tf-official-apps/threefolddev-k3s-v1.31.0.flist.md

**Comment by AhmedHanafy725** [comment]
Requires: #1158

**Comment by Omarabdul3ziz** [comment]
verified 
![image](https://github.com/user-attachments/assets/3a50c57e-f3ca-4fbf-925a-68003b980a4a)
