### ISSUE TITLE
Support zos4 deployments

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/tfgrid-sdk-go#1213]
### Describe the solution you'd like

zos4 now have different workload typs than zos3 
it has networklight instead of network amd zmachine_light instead of zmachine
  - [network light](https://github.com/threefoldtech/zos/blob/zos-light/pkg/gridtypes/zos/network_light.go)
  - [zmachine light](https://github.com/threefoldtech/zos4/blob/main/pkg/gridtypes/zos/network_light.go)

also zos4 nodes doesn't support wireguard, ygg and public config stuff

**Comment by rawdaGastan** [comment]
- You can try to deploy using this script: 
- https://github.com/threefoldtech/tfgrid-sdk-go/blob/c59cf061a57a7b793c8e2d9034a30b5c8401fcb5/grid-client/scripts/deploy_single_vm_with_mycelium_light/main.go
- still under testing

**Comment by Nabil-Salah** [comment]
# Verfication steps:
I tried to run this script: https://github.com/threefoldtech/tfgrid-sdk-go/blob/c59cf061a57a7b793c8e2d9034a30b5c8401fcb5/grid-client/scripts/deploy_single_vm_with_mycelium_light/main.go 
this script use [network light](https://github.com/threefoldtech/zos/blob/zos-light/pkg/gridtypes/zos/network_light.go) and [zmachine light](https://github.com/threefoldtech/zos4/blob/main/pkg/gridtypes/zos/network_light.go)

# It worked fine with zos4 machine with id: 264, 259

Listed on dashboard:

![image](https://github.com/user-attachments/assets/4e2c5e37-b3d9-43f2-b0ba-f8a5c26f97a2)

With Output:

![image](https://github.com/user-attachments/assets/01a3e77b-a4cd-4053-80f1-d42c0eed5246)

![image](https://github.com/user-attachments/assets/9f5d1de0-fed3-4cc4-ae92-e76039548ae1)

# I tried to ping6 mycelium IP and was fine

![image](https://github.com/user-attachments/assets/b6a549c2-697d-4866-851d-4a0b7981c2f4)

it fully addresses the issue linked
there are tests for VM light and it passes
the new code is documented well
