### ISSUE TITLE
Support testing using mycelium instead of ygg

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/tfgrid-sdk-go#1215]
### Describe the solution you'd like

- Change the resulting ygg ips from tests to mycelium ips
-  Install and use mycelium in the integration tests workflow

**Comment by Nabil-Salah** [comment]
# 2-10-2024
Work in Progress (WIP):
We made a generateBasicVM as a template for VMs
we moved use from ygg network to mycelium 
we faced failed tests that we will investigate

**Comment by SalmaElsoly** [comment]
## 3-10-2024:
tests passed with running it locally and on CI (on dev network)
updated path of script file in make file and workflow, installed mycelium in workflow

tests which doesn't pass ZDB, QSFS and Wireguared  due to connection error

**Comment by SalmaElsoly** [comment]
## 8-10:
ZDB tests passed 
But there is an issue with QSFS deployment
![image](https://github.com/user-attachments/assets/2b04a2b7-07a1-4fc4-b19d-5bb3d90e0358)

**Comment by Nabil-Salah** [comment]
# 9-10-2024:
tests passed on CI (on dev network) here: https://github.com/threefoldtech/tfgrid-sdk-go/actions/runs/11237278197/job/31242332960
also pass when running locally one by one
faced a problem with mycelium connection stability here (examples of fails):
![image](https://github.com/user-attachments/assets/3476a366-cd76-4822-a684-f4054dc6e23a)
![image](https://github.com/user-attachments/assets/7e53b260-d20d-4fc3-8981-fd1811507320)

**Comment by Nabil-Salah** [comment]
# 15-10-2024
- resolved part of comments we got today ( reporting with error if it happens in creating basic VM or Network instead of skipping)
