### ISSUE TITLE
Only allow verified users to deploy 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-go#1234]
require: https://github.com/threefoldtech/tfgrid-kyc-verifier/issues/5

The account's status can be queried from the KYC service using the account's address.

**Comment by rawdaGastan** [comment]
### Verification

#### Failure scenario

- Tried to deploy with unverified account and got `unverified` error

![Screenshot from 2024-10-30 13-24-09](https://github.com/user-attachments/assets/b77e1b90-39ce-4ae0-b3f8-97018d9b3426)

#### Success scenario

- Tried to deploy with a verified account and it worked

![image](https://github.com/user-attachments/assets/8b054ef9-734f-489e-850f-22288a9cbbda)

## Note

- once the pr is merged and accounts could be verified we can close the issue
