### ISSUE TITLE
🐞 [Bug]: grid client and tfrobot workflows are failing 

### ISSUE THREAD

**Issue by Eslam-Nawara** [threefoldtech/tfgrid-sdk-go#1239]
### What happened?

after adding kyc limitation the client and tfrobot workflows are not working anymore as they use Alice identity and we couldn't verify the account

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
https://github.com/threefoldtech/tfgrid-sdk-go/actions/runs/11607600019/job/32328467704?pr=1235
https://github.com/threefoldtech/tfgrid-sdk-go/actions/runs/11607600019/job/32329038243?pr=1235
```

**Comment by rawdaGastan** [comment]
Workflows are working now
