### ISSUE TITLE
🐞 [Bug]: failed to deploy zdbs on node 11

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-go#1271]
### What happened?

As per No.343 - [Test case: TC2072](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1254322&selected=33335115) 
I couldn't deploy `zdb` with command `tfcmd deploy zdb --project_name examplezdb --size=10 --count=2 --password=password`

![image](https://github.com/user-attachments/assets/164b638b-c184-45ab-99e8-7f0b4906b48f)

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
failed to deploy zdbs on node 11: error waiting deployment: workload examplezdb0 within deployment 174404 failed with error: failed to create zdb namespace: failed to connect to 0-db: fb45d10b-***: dial unix /var/run/zdb_fb45d10b-***/zdb.sock: connect: connection refused
```

**Comment by scottyeager** [comment]
See here: https://github.com/threefoldtech/zos/issues/2369

I think this is a Zos bug that's independent of any SDK or deployment method.

**Comment by rawdaGastan** [comment]
> I think this is a Zos bug that's independent of any SDK or deployment method.
 
yes not related to the sdk, will close the issue
