### ISSUE TITLE
502 Bad Gateway response to requests for statistics endpoint

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#135]
### Description

Request to statistics endpoint is giving 502 Bad Gateway

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5f900d3d-ef30-4ce0-b522-315a615ac753)

Also causing an error in the console in the explorer node stats in dashboard
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6916fd5b-aed2-4b99-8780-8f6fde25b85c)

**Comment by ramezsaeed** [comment]
duplicate to: https://github.com/threefoldtech/tfgrid-sdk-go/issues/104
