### ISSUE TITLE
relay connection keeps closing

### ISSUE THREAD

**Issue by mariobassem** [threefoldtech/tfgrid-sdk-go#149]
relay connection closes after some time, still trying to investigate why, but with some initial debugging, the connection closes after a reconnection happens with the chain.

**Comment by mariobassem** [comment]
i got part of the issue i think:

the relay closes the connection because i was creating new gridclient instances with the same credentials, which in turn tries to create new relay connections with the same session id...
the part i didn't get is that as i understand the relay should drop the old connection and start using the new one, but this does not happen for some reason, the gridclient keeps opening new connections and the relay keeps closing them after they are opened..

a simple solution is just not to create new instances of the gridclient :D

but i think this would not be great, because of this:
webproxy users are allowed to use the gridclient by sending a login request first, this is what creates a new gridclient instance..
and if a user sent multiple login requests with the same credentials, we could just discard all but the first one...
if the same user sent another login request but with different credentials, the only thing to do here is to drop the the gridclient instance and create a new one.
this approach has two problems:
- the websocket connections of the gridclient (tfchain, rmb relay) are still opened and working in the background.
- if the same user decided that they want to login with the first credentials, we are back at block 0 and the relay does not accept anymore messages

so, since the gridclient has two open websocket connections that never get closed, shouldn't we provide some close method to close these connections?

**Comment by brandonpille** [comment]
It makes sense yes to add a close method that closes the connection. What would even be better is to make it close the connection whenever the client object is destroyed.

**Comment by mariobassem** [comment]
i didn't find a guaranteed way to do this in go. the solution i thought of is whenever the holder of this client decides that the client is no longer relevant and should be released, the holder should be responsible for calling this close method before releasing the client. this is implemented in https://github.com/threefoldtech/web3_proxy/pull/87

**Comment by brandonpille** [comment]
What do you mean? There is no function to close the websocket connection? Or there is no way to call the close functions on object destruction time?
