### ISSUE TITLE
Statistics endpoint takes too long on offline nodes

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-go#153]
## Describe the bug

we need to set timeout to the statistics endpoint, if you visit any offline node statistics it will take too long to get 504 

## To Reproduce

- check any offline node on the dashboard and visit its statistics endpoint 
for example 
https://gridproxy.dev.grid.tf/nodes/18/statistics 

## Expected behavior

return that node is down or minimize the timeout

**Comment by alichaddad** [comment]
This already implemented in 3.11, moving it back.

**Comment by A-Harby** [comment]
Verified,

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/f075d216-0b5d-4334-b6ca-18b72afc0c74)
