### ISSUE TITLE
Swagger Docs: Incorrect example for the `NodeStatistics` endpoint

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-go#163]
## Describe the bug

The provided example for the statistics endpoint is incorrect.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/3419e89b-42a2-44b8-b9d9-a4e7a2570cd0)

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/81a21793-5d2f-4ac3-bb43-1f070ddffae9)

## To Reproduce

- Navigate to https://gridproxy.qa.grid.tf/swagger/index.html#/NodeStatistics/get_nodes__node_id__statistics
- Check the provided example.
- [Navigate to https://gridproxy.qa.grid.tf/contracts](https://gridproxy.qa.grid.tf/nodes/3/statistics)
- Check the actual result.

## Expected behavior

The example should be defined like the actual result from the endpoint.

```
{
          "system": {
                "cru": 0,
                "hru": 0,
                "ipv4u": 0,
                "mru": 0,
                "sru": 0
          },
          "total": {
                "cru": 0,
                "hru": 0,
                "ipv4u": 0,
                "mru": 0,
                "sru": 0
          },
          "used": {
                "cru": 0,
                "hru": 0,
                "ipv4u": 0,
                "mru": 0,
                "sru": 0
          },
          "users": {
                "deployments": 0,
                "workloads": 0
          }
}
```

**Comment by A-Harby** [comment]
Verified on Devnet
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/9f908b84-d7a1-474e-bcce-512bb39f0ab1)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/2f24692e-1970-44df-9d40-6e12d6098760)

**Comment by A-Harby** [comment]
Verified on Devnet
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/9f908b84-d7a1-474e-bcce-512bb39f0ab1)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/2f24692e-1970-44df-9d40-6e12d6098760)
