### ISSUE TITLE
GPU support in tf-grid-cli

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#165]
https://github.com/threefoldtech/home/issues/1392 

https://github.com/threefoldtech/zos/pull/1973
add option for the user to deploy his vm on a node with gpu

**Comment by A-Harby** [comment]
Verified on development 1.0.0 branch.
GPU list option was added, docs were updated and successfully deployed.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/2ade7272-7a6b-4e0a-9b22-1bb8ea10ff60)
