### ISSUE TITLE
Update the releases page link in the monitoring bot readme

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-go#166]
## Describe the bug

Update the `releases page` link in the monitoring bot [readme](https://github.com/threefoldtech/tfgrid-sdk-go/tree/development/monitoring-bot). 

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/b93b35e2-49cb-464d-bf37-3c31ba6125bb)

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/135d8437-15d9-4b7c-adb0-484537f1b6c5)

**Comment by xmonader** [comment]
fixed in https://github.com/threefoldtech/tfgrid-sdk-go/commit/b2fe7029672db58b30b6a773bdba65a64c82c4a7
