### ISSUE TITLE
Monitoring bot fails to check the relay in every network

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-go#167]
## Describe the bug

Monitoring bot fails to check the relay in every network, and from the logs it can be seen that it tried to test the relay but fails with the following error.

```bash
4:56PM DBG get system version for network devnet
4:56PM DBG connecting url=wss://tfchain.dev.grid.tf:443
2023/06/04 16:56:01 Connecting to wss://tfchain.dev.grid.tf:443...
4:56PM ERR error getting relay for network devnet error="failed to create identity: invalid URI format"
4:56PM DBG get system version for network qanet
4:56PM DBG connecting url=wss://tfchain.qa.grid.tf:443
2023/06/04 16:56:02 Connecting to wss://tfchain.qa.grid.tf:443...
4:56PM ERR error getting relay for network qanet error="failed to create identity: invalid URI format"
4:56PM DBG get system version for network testnet
4:56PM DBG connecting url=wss://tfchain.test.grid.tf/ws
2023/06/04 16:56:03 Connecting to wss://tfchain.test.grid.tf/ws...
4:56PM ERR error getting relay for network testnet error="failed to create identity: invalid URI format"
4:56PM DBG get system version for network mainnet
4:56PM DBG connecting url=wss://tfchain.grid.tf/ws
2023/06/04 16:56:04 Connecting to wss://tfchain.grid.tf/ws...
4:56PM ERR error getting relay for network mainnet error="failed to create identity: invalid URI format"

```

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/abfaf7ed-5fb7-4825-bf98-64b894740d35)

## To Reproduce

- Follow the steps in the [readme](https://github.com/threefoldtech/tfgrid-sdk-go/tree/development/monitoring-bot#how-to-start) to run the bot.

## Expected behavior

Checking the relay shouldn't fail since it's working fine on all networks.

**Comment by rawdaGastan** [comment]
which version of monitoring bot you are using?

**Comment by mohamedamer453** [comment]
After checking the env file i realized that the mnemonic of my account had a space and a bracket at the end of it (Probably something wrong happened while copying my config from the old env file) but after fixing it the bot worked without any issues.
