### ISSUE TITLE
Validate configuration files before starting the bot

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-go#169]
## Describe the bug

Based on a previous issue https://github.com/threefoldtech/tfgrid-sdk-go/issues/167#issuecomment-1575603963 where i didn't realize that something was wrong with my `.env` file and the bot reported that there's an error with the relay url. validation for the configuration files should be added to prevent errors like this in the future.

The monitoringbot should validate both the `.env` & `wallets.json` files before running the bot and in case of incorrect validation it should stop the bot and display a clear error message mentioning that the validation is correct for a certain field and if it's not possible to mention where the exact error is then it should mention that one or more input/s in this file is incorrect.

The main inputs that could be validated are:
- Mnemonic (validate that it has the correct format and registered in the mentioned network)
- tfchain address (Validate that it has the correct address and belongs to a twin on the mentioned network(if possible) )
- Not sure what the validation of the other fields could look like but mainly it could be valid format or inputs (ex. `Mins` field should accept numeric values only, etc...)
## To Reproduce

- While configuring the `.env` or the `wallets.json` enter some incorrect input/s.
- Run the bot.

## Expected behavior

The bot shouldn't run in the first place if one the inputs is invalid.

**Comment by maayarosama** [comment]
Validating mnemonics is done, validating wallets is moved to a later milestone #181

**Comment by mohamedamer453** [comment]
Verified.

After building the latest version of the monitoring bot locally since it's not released yet. i was able to test the new validation by adding incorrect mnemonic for each network and now when the mnemonic is invalid it fails to start and mentions that the mnemonic for this specific network is invalid.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/0883e560-c3cf-4e30-a5d2-ac49c8c884f1)
