### ISSUE TITLE
get vm info does not work

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-go#170]
## Describe the bug

`tf-grid-cli  get vm examplevm`
 command does not work same issue for k8s

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/a6758889-4c93-4996-9de5-dd1942f78f34)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/ffae15c1-e2c3-4c93-a54b-fd5e989e20f9)

steps to produce :

1. install grid cli and download the latest binary
2. deploy a vm
3. try to get the vm info

**Comment by A-Harby** [comment]
Verified,
Get contract is working fine with no error now.
Get VM
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/6b1de484-2947-4ee5-8937-7783eecd4c8e)
Get Kubernetes
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/26372fb4-eda9-4cf5-856f-2c0775cebe76)
Get gateway name
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/10b9e97a-1ed3-4218-a0dd-6fe4a6031072)
