### ISSUE TITLE
A gateway deploys even in the case of a failure

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#172]
## Describe the bug

When a gateway deployment fail in grid cli, the contract deploys anyway.

## To Reproduce

try `tf-grid-cli deploy gateway name -n gatewaytest --node 2 --backends http://93.184.216.34:80` on testnet where node 2 is not a gateway node.

## Expected behavior

Rollback to delete the contract.

## Screenshots

[Untitled_ Jun 7 2023 4_19 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/4c30cfd3-c202-474e-aecf-ba8591848b13)

**Comment by A-Harby** [comment]
Same in deploying FQDN Gateway
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/6b0a24c3-6549-43d4-821e-75ea7c7bd01e)

**Comment by ashraffouda** [comment]
> 

this is not the same error as above the error here is because the domain used here doesn't exist

**Comment by ashraffouda** [comment]
> Same in deploying FQDN Gateway ![image](https://user-images.githubusercontent.com/109473873/244077700-6b0a24c3-6549-43d4-821e-75ea7c7bd01e.png)

this is not the same error as above the error here is because the domain used here doesn't exist

**Comment by ashraffouda** [comment]
https://github.com/threefoldtech/tfgrid-sdk-go/pull/180

**Comment by A-Harby** [comment]
Verified
Error message is printed stating that node doesn't have a domain configuration, and no contract was made.
Gateway
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/4ed08b0b-39d9-4124-a7b0-129940b64bf3)
Gateway fqdn
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/d9e4e53e-8b4a-442c-a1bc-9371a50be771)
