### ISSUE TITLE
make deployment process concurrent

### ISSUE THREAD

**Issue by mariobassem** [threefoldtech/tfgrid-sdk-go#174]
currently, the deployer in grid-client performs it's tasks on contracts in a serial manner. this could be improved by using chain batch calls for creations and deletions ( batch updates are currently not supported), and concurrently execute all calls.

**Comment by xmonader** [comment]
Please update the issue with the latest status and if not really needed anymore we can close @rawdaGastan @AbdelrahmanElawady
