### ISSUE TITLE
gridproxy report zero contracts for anode listed in dedicated nodes although it has one active contract 

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/tfgrid-sdk-go#175]
## Describe the bug

on testnet node 14 which is dedicated node , it's not able to rent the node but it's listed in rentable nodes , ans is reported by gridproxy that it has 0 deployments and 0 workloads
https://github.com/threefoldtech/tf_operations/issues/1724
https://user-images.githubusercontent.com/109473873/244090433-16e7e9a7-54ba-499b-aba4-4cc0d54d7b0c.webm

## Expected behavior

node shouldn't be listed in rentable table as long as there is an active contract on it .

## Screenshots
![Screenshot from 2023-06-08 14-08-34](https://github.com/threefoldtech/tfgrid-sdk-go/assets/26298009/b599dbd9-6e30-4ca1-bef6-332d1ffe326e)

![Firefox_Screenshot_2023-06-08T11-16-45 832Z](https://github.com/threefoldtech/tfgrid-sdk-go/assets/26298009/d5e2f23a-405d-4de7-87b6-f997af23cd0e)

**Comment by khaledyoussef24** [comment]
verified and tested on devnet on many nodes.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/19999704-c056-421c-8e6d-920ede6b7d84)
