### ISSUE TITLE
monbot: validate the monitored addresses

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#181]
Try to get the balance of each address

**Comment by mohamedamer453** [comment]
Verified.

Validation for the address was added. first case is when the length of the address in invalid.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/3e6d76d7-5027-44be-ad16-61273b149209)

And when the length/format is correct but the address itself is invalid.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/f02ffbe2-23a3-428f-822e-ecf7475fcd35)
