### ISSUE TITLE
gateway name test is failing

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tfgrid-sdk-go#187]
## Describe the bug

currently gateway name test is failing 
![Screenshot from 2023-06-13 12-59-44](https://github.com/threefoldtech/tfgrid-sdk-go/assets/1689456/f7fc97a7-b108-4f05-ae8c-d56560c55491)

**Comment by khaledyoussef24** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/3dd3c80f-5183-40eb-ac73-8fe1cb92b78e)
verified and works fine
