### ISSUE TITLE
Update the node uptime report period to be 40 mins in gridproxy

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-go#198]
gridproxy is setting the node as up if the `updatedAt` field contains a timestamp less than 2 hours from now which is 2 cycles. this should be 2 cycles as is but the cycle should be 40 mins instead of 60 mins.

**Comment by khaledyoussef24** [comment]
verified on grid proxy no node with status up updated in more than 40 min
![Screenshot from 2023-07-12 10-06-18](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/ee49074e-5d59-402f-9ff8-ef872c0a9e32)
![Screenshot from 2023-07-12 10-05-57](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/aeb18a92-173f-40fa-b888-40062f3af607)

I monitored the same node for 40 min it got updated in the range of 40-45 min in grid proxy
before updating :
![Screenshot from 2023-07-12 10-09-19](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/9df789bc-934a-4289-805b-935608eaa47b)
![Screenshot from 2023-07-12 10-09-01](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/c9457106-d02b-4596-a2e0-8010af31df23)

last minute before updating:
![Screenshot from 2023-07-12 10-15-40](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/0213ebb5-1a59-4a54-a95e-e2cca31692b3)

after 45 min:
![Screenshot from 2023-07-12 10-16-14](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/9dfd5809-6d44-44b4-a62b-8ae3b7ffb44c)
![Screenshot from 2023-07-12 10-15-59](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/4f888116-6f7d-40f0-a5ac-c8ae4ab1ebb9)
