### ISSUE TITLE
GPU support in grid-proxy

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tfgrid-sdk-go#201]
https://github.com/threefoldtech/home/issues/1392 

https://github.com/threefoldtech/zos/pull/1973

change node schema to include has_gpu and extra_fees 
also add an endpoint to get gpu details for the node

**Comment by mohamedamer453** [comment]
Verified on devnet.

Firstly in the `/nodes` endpoint `has_gpu` parameter was added to filter nodes with gpu.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/3f8c94dc-2910-4a2c-a9d0-679a02807ef7)

and 2 new fields are now returned with the node info `num_gpu`: returns the number of gpus on the node & `extraFee`: returns the extra fee that's applied for this node 

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/c622d8df-6625-4011-85d6-209c6b690dcb)

and lastly the [`/nodes/<node_id>/gpu`](https://gridproxy.dev.grid.tf/swagger/index.html#/NodeGPUs/get_nodes__node_id__gpu) endpoint. which returns the full details of the card/s.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/125ab6d9-4f4a-4e1b-b91a-33d6efe04769)

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/441831e2-a6ea-48b8-a722-02b9dede835f)
