### ISSUE TITLE
update stats endpoint for gpus count

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#210]
https://gridproxy.dev.grid.tf/stats

should include number of gpus

not sure if should be number of gpus or number of nodes with gpus enabled, given the node can have multiple GPUs

In case of nodes that has gpu enabled it's a simple query, but in case of the exact number of gpus i believe we will have to count all gpus using listGPUs

**Comment by A-Harby** [comment]
Verified on Devnet,


![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/d142a250-0be2-4b90-a53a-4a901b430c6c)
