### ISSUE TITLE
refactor gridproxy tests

### ISSUE THREAD

**Issue by mariobassem** [threefoldtech/tfgrid-sdk-go#228]
main things to consider while refactoring:

- tests need to be somewhat less random, as at some times tests pass, and some other times they don't
- use a mock db instead of a real db in tests. this would remove the db running on a container dependency from tests, and should make the tests more robust.
- document how tests work since it's currently a bit vague.

**Comment by mariobassem** [comment]
was investigating using [go-sqlmock](https://pkg.go.dev/github.com/data-dog/go-sqlmock), but concluded that this would  add to tests complexity, as it would validate executed sql statements. and since we're using an orm, it should not be our job to test the validity of generated sql statements. 
so, i believe it's better to stick with the current approach for testing. maybe just refactor to make it more simple to update, and easier to figure where failures happen

**Comment by mariobassem** [comment]
currently, if some changes are done in gridproxy filters, and the changes are not reflected in tests, the tests should point to which field in a filter is not  tested.

remaining: enforce handling of filter fields in mock client

**Comment by mariobassem** [comment]
- [x] use `"github.com/google/go-cmp/cmp"` to log differences between local and remote clients
- [x] remove `validateResults` and replace with `reflect.DeepEquals` 
- [x] reorganize local client.
- [x] test each field of each filter separately.
- [x] refactor random filter generators
- [x] fix bugs in postgres

**Comment by mariobassem** [comment]
this issue is related to refactoring gridproxy end-to-end tests. more unit tests need to be added for individual components, but will open other issues for them separately.

**Comment by A-Harby** [comment]
Verified, 
Tests were refactor and database updated.
Docs were added https://github.com/threefoldtech/tfgrid-sdk-go/blob/development/grid-proxy/docs/test.md.
Workflow is working and passing https://github.com/threefoldtech/tfgrid-sdk-go/actions/workflows/gridproxy-integrationtests.yml.
