### ISSUE TITLE
gridproxy filter boolean flags produce erroneous results

### ISSUE THREAD

**Issue by mariobassem** [threefoldtech/tfgrid-sdk-go#229]
## Description 

a lot of  boolean flags in gridproxy filters are treated the same way whether they have a value of true or false.
https://github.com/threefoldtech/tfgrid-sdk-go/blob/f04d664c0ce9ef5eba4559a615831006db1a2566/grid-proxy/internal/explorer/db/postgres.go#L463-L471

## To Reproduce

use a nodes filter for example and provide a boolean flag with a true value, then another time with a false value. the result will be the same

**Comment by mohamedamer453** [comment]
Verified on devnet.

The result is now accurate when the value is set to true or false for the mentioned flags.

### ipv4

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/1dd9f883-6998-410f-a33f-9c2524f2c074)

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/f26fed9d-3ab7-412d-9d84-9a5a620d9b41)

### ipv6

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/398c29c0-d4fd-4f87-8115-5d70a65c8145)

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/0d02921b-3f36-4329-b4f6-7d477aa46ed5)

### domain

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/a75e5b77-24fc-4608-85f9-1a4c6aa3368c)


![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/cec1c86f-fb5d-4271-8774-e60d22d688e5)
