### ISSUE TITLE
update gridproxy filter types

### ISSUE THREAD

**Issue by mariobassem** [threefoldtech/tfgrid-sdk-go#230]
currently gridproxy filter types are not really accurate, as all integer fields use unsigned 64bit integers, which is not the case for a lot of types like twin ids, node ids, and so on...
also, json tags  should be provided for all types where snake case naming is used

**Comment by Omarabdul3ziz** [comment]
Closed as Duplicated.
- https://github.com/threefoldtech/tfgrid-sdk-go/issues/340
- https://github.com/threefoldtech/tfgrid-sdk-go/issues/49
