### ISSUE TITLE
investigate other ways to perform contracts query

### ISSUE THREAD

**Issue by mariobassem** [threefoldtech/tfgrid-sdk-go#231]
currently, the sql query used in fetching contracts from the database contains a subquery to retrieve relevant information, which makes performance a bit bad, as the sql command alone could take ~100ms.

**Comment by Omarabdul3ziz** [comment]
update:
merged now but waiting for a release to move to verification

**Comment by A-Harby** [comment]
Verified, Devnet.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/00f03f52-f84b-4d6a-aecb-78c473a68aec)


Docs was udpated, https://github.com/threefoldtech/tfgrid-sdk-go/blob/ac6592e8a210a4a98b1349909a331ee10c71b6d9/grid-proxy/docs/docs.go#L135C38-L135C38 .

As well as Swagger, https://gridproxy.dev.grid.tf/swagger/index.html#/Contract/get_contracts__contract_id_.
