### ISSUE TITLE
vm support to have console url

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tfgrid-sdk-go#238]
currently zos supports accessing vm via cloud console so this should be reflected in grid-client

**Comment by khaledyoussef24** [comment]
verified  
![Screenshot from 2023-07-31 15-48-05](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/075a2269-b4b2-4f82-a245-18c893119a5f)
![Screenshot from 2023-07-31 15-46-46](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/d9254fe6-a96c-4204-aa11-08bd00f1af55)
![Screenshot from 2023-07-31 15-46-10](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/4e5939c9-140c-41d6-9546-804a6714a6e4)
