### ISSUE TITLE
Swagger docs don't cover all node filter keys 

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-go#249]
## Describe the bug

The swagger docs don't support the filter by total values or `sru, cru, mru, hru` and it's supported to filter by them as seen [here](https://github.com/threefoldtech/tfgrid-sdk-go/blob/development/grid-proxy/internal/explorer/helpers.go#L132-L135) 

## To Reproduce
- Go to the [swagger API](https://gridproxy.dev.grid.tf/swagger/index.html#/GridProxy/get_nodes)

**Comment by mohamedamer453** [comment]
total_cru should be in `vCores` not in `bytes`

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/2abf6b34-c990-48fc-bbed-71cfae1b55c9)

**Comment by xmonader** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/64129/543575b4-2817-4fd5-bedc-ae08cd985b1c)
https://gridproxy.qa.grid.tf/swagger/index.html#/GridProxy/get_nodes
