### ISSUE TITLE
[Bug 🐞]: https://gridproxy.grid.tf/swagger doesn't work

### ISSUE THREAD

**Issue by fl0wm0ti0n** [threefoldtech/tfgrid-sdk-go#252]
### What happened?

if you run https://gridproxy.grid.tf/swagger in browser it will result in a "Not Found"

### What did you expect?

the swagger ui

### ZOS info

-

### Dashboard info

-

### weblets info

-

### Relevant log output

```shell
-
```

**Comment by xmonader** [comment]
correct link https://gridproxy.grid.tf/swagger/index.html

missing a trailing slash

**Comment by fl0wm0ti0n** [comment]
thanks , the help text says it so:

"Welcome to threefold grid proxy server, available endpoints [/farms] [/stats] [/nodes] [/gateways] [/twins] [/contracts] [/nodes/{node_id:[0-9]+}] [/gateways/{node_id:[0-9]+}] [/nodes/{node_id:[0-9]+}/status] [/gateways/{node_id:[0-9]+}/status] [/ping] [/] [/version] [/swagger] "

**Comment by Omarabdul3ziz** [comment]
Verified 
the welcome message has the correct endpoint for swagger with the trailing slash now.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/32527347/6d25744c-114e-426d-bdda-e829ba7b5be1)

and going to https://gridproxy.grid.tf/swagger/ will open the swagger docs
