### ISSUE TITLE
totalCount is not correct when filtering farms

### ISSUE THREAD

**Issue by mariobassem** [threefoldtech/tfgrid-sdk-go#253]
## Describe the bug

When filtering farms by free hru, mru, or sru, the totalCount returned is not correct.
This happens because when this filter is used, the farms table is joined with the nodes table and the node_resource_view view,  which created multiple records for nodes on the same farm. This results in an incorrect totalCount, but the resulting farms are correct .

## To Reproduce

1- Filter farms by free hru, mru, or sru.
2- Set the RetCount flag to true

**Comment by mohamedamer453** [comment]
Verified on devnet.

for the mentioned filters the count returned in the header was consistent with the number of returned farms.

### free mru

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/d998f5fa-c92e-4271-a324-ec9a4b9bbca9)

### free sru

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/97e69681-e7de-465a-931d-53af3e311682)

### free hru

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/8f2265a1-2625-410d-9745-c59a60200d1a)
