### ISSUE TITLE
Some filter fields are not parsed when using the gridproxy client

### ISSUE THREAD

**Issue by mariobassem** [threefoldtech/tfgrid-sdk-go#255]
## Describe the bug

Some Filter fields are not parsed when using the gridproxy client. for now, the affected fields are:
- Dedicated in NodeFilter
- Relay in TwinFilter
- PublicKey in TwinFilter

## To Reproduce

- Use the gridproxy client with any of the above fields set to any value

## Expected behavior

- gridproxy should return the result according to the provided filter fileds

**Comment by mohamedamer453** [comment]
Verified on qanet.

All of the mentioned endpoints are working without any issue.

### Dedicated in `/nodes`

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/139eba8a-cebd-4c19-af88-f7000c372092)

### Relay in `/twins`

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/e2e3dd80-f6fd-4232-911a-aef1b8692480)

### Public key in `/twins`

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/2cc70aab-d349-4e1f-97a2-a617612c366b)
