### ISSUE TITLE
Support searching with decimal values

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-go#261]
## Is your feature request related to a problem? Please describe

Searching with decimal values for some endpoints should be possible. as mentioned before in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/721#issuecomment-1653453655 adding this functionality from the dashboard so the user can search with the exact values instead of rounding it was not possible due to the limitation from the gridproxy.

## Describe the solution you'd like

Endpoints related to SRU, HRU, MRU should support decimal values.

**Comment by AhmedHanafy725** [comment]
The filters are already working with bytes, so I don't think we should have fractions for these queries. byte is the lowest value we can have.
For the dashboard, it can accept decimal values (with GB) and convert them to bytes, then ceil the value if they still have fractions and send it to the gridproxy.

**Comment by mohamedamer453** [comment]
Closing in favor of https://github.com/threefoldtech/tfgrid-sdk-ts/issues/891
