### ISSUE TITLE
support some queries on farms endpoint

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-go#263]
required for https://github.com/threefoldtech/tfgrid-sdk-ts/issues/491

- [ ] node status
- [ ] node rented by (twin id)
- [ ] node certified
- [ ] node has gpu
- [ ] has nodes available for (twin id)

**Comment by xmonader** [comment]
@MarioBassem please create a ticket to upgrade the proxy

**Comment by mohamedamer453** [comment]
Verified on devnet.

All of the mentioned queries were added and documented in the swagger page.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/7bb58197-a907-4d79-ad52-b535e6a6575c)

### Node status

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/92b59128-49a9-4ca5-b9c1-239f600ef6cb)

### Node rented by

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/c35c35d4-49cd-4489-9076-538084df2672)

### Nodes certified

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/420dfada-092b-4b3c-bb63-6cebbf1a0f16)

### Node has gpu

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/ab93d318-3f90-4621-a2cf-cf1cc83e5bba)

### Node available for

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/8eecf5fa-c19f-4aee-a2e6-aaf75234d544)
