### ISSUE TITLE
Filtering nodes using storage is not accurate

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-go#264]
The way users use [`FilterNodes`](https://github.com/threefoldtech/tfgrid-sdk-go/blob/development/grid-client/deployer/node_filter.go#L19) is to provide a filter with all the storage needed and we do a Pool check to determine if it has enough storage.
The issue is that it can miss some nodes that are available . for example: a deployment with 3 disks each one is 100GB. the filter provided will have 300 SRU needed. A node with 3 Pools of 100GB will not be marked as available although it can be used.

A better way to do that is to sort different storage needed and check each storage if it can be allocated to a Pool or not.

Related: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/886

**Comment by xmonader** [comment]
Let's do this as part of 3.11

**Comment by AbdelrahmanElawady** [comment]
Note: ZOS provisioning orders workloads as `zmounts` -> `zmachines` so checks for disks need to be done before rootfs size as it is not considered a `zmount`.
ZOS [code](https://github.com/threefoldtech/zos/blob/d151e9cda7ad4991842b4c96c494967bfc5f1dbe/cmds/modules/provisiond/main.go#L329-L337).

**Comment by 0oM4R** [comment]
> Note: ZOS provisioning orders workloads as `zmounts` -> `zmachines` so checks for disks need to be done before rootfs size as it is not considered a `zmount`. ZOS [code](https://github.com/threefoldtech/zos/blob/d151e9cda7ad4991842b4c96c494967bfc5f1dbe/cmds/modules/provisiond/main.go#L329-L337).


@AbdelrahmanElawady 
I guess we already handle this here

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/aa51babe5ad696d5adb79070857a3685a5ccb30d/packages/grid_client/src/primitives/nodes.ts#L470

checks for ssd and hdd disks done __then__ we check on rootfs

**Comment by khaledyoussef24** [comment]
it is already handled as @0oM4R  mentioned and it checks on the rootfs
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/f496a8d6-0f79-4c5b-9946-aac0643c3486)
