### ISSUE TITLE
long response time in some gridproxy requests

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/tfgrid-sdk-go#265]
## Describe the bug

some requests to gridproxy takes long time to respond. the issue was found on mainnet but also can be reproduces on some requests on other networks

## To Reproduce
original issue was in requesting https://gridproxy.grid.tf/nodes?free_mru=8589934592&free_sru=55834574848&country=United%20States&available_for=1061&status=up

## Notes
- the issue happens when using the two filters `country` & `available_for` together.
- but it looks that `available_for` with `country_contains` filter works fine.
- there is also some broken requests like https://gridproxy.grid.tf/contracts?state=Deleted&type=rent and https://gridproxy.dev.grid.tf/contracts
- maybe the problem with `/contracts `endpoint is the subquery [here](https://github.com/threefoldtech/tfgrid-sdk-go/blob/c3044cec66862d5c86f4cdfde0f1c59c5bab6731/grid-proxy/internal/explorer/db/postgres.go#L703) but not sure if it the problem with `/nodes` endpoint also

**Comment by Omarabdul3ziz** [comment]
the `/contracts` endpoint performance is fixed with this pr https://github.com/threefoldtech/tfgrid-sdk-go/pull/356

**Comment by Omarabdul3ziz** [comment]
I can't find any particular problem with this request. also, it can't reproduce even on a large db mock.
hope it will be fixed with the improvements from this issue https://github.com/threefoldtech/tfgrid-sdk-go/issues/308, will update the progress there.

**Comment by Omarabdul3ziz** [comment]
this https://github.com/threefoldtech/tfgrid-sdk-go/pull/533 should fixed the problem released with tag `v0.13.0` and deployed now on devnet

**Comment by khaledyoussef24** [comment]
the issue is not reproducible any more endpoints work fine now
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/0cb29b14-e167-4987-9b1b-c07dd876e8da)
