### ISSUE TITLE
GPU indexer sql error in gridproxy qa-net

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/tfgrid-sdk-go#267]
## Describe the bug

error in gridproxy pod

## To Reproduce

Not sure how the error is generated

## Expected behavior

no errors

## Screenshots

![image_2023-08-02_10-40-32](https://github.com/threefoldtech/tfgrid-sdk-go/assets/88312671/78757fc5-d3a7-4b37-8466-e3fa12f1822d)

**Comment by xmonader** [comment]
this is caused by the order of the upgrade, the tfchain and graphql need to happen first, then the migration will update the database with node.extra_fees column. I'll close, but please reopen if not clear
