### ISSUE TITLE
Add an example for the async client

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-go#268]
## Is your feature request related to a problem? Please describe

While verifying #220 i didn't find an example for the async client or how to use it. the [examples](https://github.com/threefoldtech/tfgrid-sdk-go/tree/development/rmb-sdk-go/examples) that were available were only for the direct client.

## Describe the solution you'd like

An example for the async client in the [examples](https://github.com/threefoldtech/tfgrid-sdk-go/tree/development/rmb-sdk-go/examples) directory and a readme file on how to use it.

**Comment by xmonader** [comment]
@Eslam-Nawara xD

**Comment by Eslam-Nawara** [comment]
Work Completed:

- [x] implement an example of `rmb` direct client.
- [x] rename old direct client to `rpc` client.
- [x] add README to all clients examples.

**Comment by AbdelrahmanElawady** [comment]
Verified and examples were added to `rmb-sdk-go/examples` and they run as per documentation.
