### ISSUE TITLE
use schema package to encode and decode query paramters

### ISSUE THREAD

**Issue by mariobassem** [threefoldtech/tfgrid-sdk-go#269]
currently, http query parameters are encoded and decoded using local converters, which may be error prone if some type changes happen. luckily there is a package that does this already [schema](https://github.com/gorilla/schema). 

i think it would be better to use it and not bother with the conversion again.

**Comment by xmonader** [comment]
It's definitely a step in the right direction.

**Comment by mariobassem** [comment]
rebased the pr branch on latest development

**Comment by Omarabdul3ziz** [comment]
track updates on the pr discussion
