### ISSUE TITLE
support zdb as a subcommand on tf-grid-cli

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#271]
the cli should support creation of zdbs within a project

suggested usage should be 

```tf-grid-cli zdb -size=50GB -n 4 -password=X```

to create 4 zdbs of size 50GB

**Comment by A-Harby** [comment]
Verified, Development_1.0.0.0_release.
Docs were added.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/3d7b9443-c553-4b10-a1bc-052ab3d8a12d)

Deploying 
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/44217907-3da7-4271-8931-8f8a846707f8)
Get
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/cb0c1eb8-a950-436a-b678-e423181f84c4)
Cancel
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/e6e8d9ac-fd23-44e9-9da7-13101eeceece)
