### ISSUE TITLE
cli panics

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-go#275]
## Describe the bug

tf-grid-cli panics when deploying name gateways without specifying a node

## To Reproduce

- run `tf-grid-cli deploy gateway name -n anyname --backends http://example.com`

## Expected behavior

It should either succeed or fail but not panic.

**Comment by khaledyoussef24** [comment]
still facing the same issue 
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/17edf129-0392-49d9-b56f-a3cba672b533)

**Comment by khaledyoussef24** [comment]
works fine now
![Screenshot from 2023-08-10 13-09-29](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/b1cca333-bb9d-48cf-ba0b-8265d8da11ca)
verified
