### ISSUE TITLE
Some server logs should be less severity

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgrid-sdk-go#276]
## Describe the bug

I want to emphasize the importance of assessing the severity of any event that needs to be logged in the application and selecting the right log level. If it does not affect any of the application functions, then you should use a lower level than error, such as warn, info, or debug, for better performance and less confusion when we get reports that the application is not working properly because it prints all kinds of errors.

## logs

```bash
error couldn't parse total_sru strconv.ParseUint: parsing "512067475865.6": invalid syntax: bad request
error node not found
error failed to read message error="read tcp 10.244.1.127:60542->185.206.122.7:443: use of closed network connection"
error cannot fetch GPU information from node 93 with status: down
error cannot fetch statistics from node 86 with status: standby
error failed to read message error="websocket: close 1006 (abnormal closure): unexpected EOF"
error couldn't parse total_cru strconv.ParseUint: parsing "44.54": invalid syntax: bad request
error failed to reconnect error="failed to connect (): : dial tcp: lookup relay.dev.grid.tf on 10.96.0.10:53: server misbehavin
error couldn't parse size strconv.ParseUint: parsing "1000000?ret_count=true": invalid syntax: bad request
```

I think these logs have different levels of severity, and some should be lower (at least to my understanding).
Things like bad requests, unreachable nodes shouldn't be reported as errors.

**Comment by rawdaGastan** [comment]
### Verification

- Log level is now defined

![image](https://github.com/user-attachments/assets/e8aa510e-5aa0-47cc-bc7b-5fd03165e40a)
