### ISSUE TITLE
SQL 53300 state 

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgrid-sdk-go#302]
## Describe the bug
I noticed this in the Devnet Gridproxy server logs

Not sure, but SQL 53300 state may have something to do with the db connection pooler. if opening these many connections is not a bug in gridproxy, we could then try to increase `max_connections` if the value is too low.

## Screenshots
![Screenshot from 2023-08-08 16-30-32](https://github.com/threefoldtech/tfgrid-sdk-go/assets/42457449/251476c5-dc25-4ae3-afb9-7f56af67263f)

## Update:
The db connection pool maximum open connections should be set (using `SetMaxOpenConns()` method) to a value lower than the `max_connections` parameter in PostgreSQL, which is 100 by default.

See this [comment](https://github.com/threefoldtech/tfgrid-sdk-go/issues/302#issuecomment-1670353846) for more detalis.

**Comment by A-Harby** [comment]
It appears that there is a limitation on the amount of requests that can be made to the grid proxy before it crashes or refuse the request, as shown in the [issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/942); this should be fixed from the dashboard side, but it reveals that the grid proxy's stress load isn't the best.

**Comment by sameh-farouk** [comment]
> It appears that there is a limitation on the amount of requests that can be made to the grid proxy before it crashes or refuse the request, as shown in the https://github.com/threefoldtech/tfgrid-sdk-ts/issues/942; this should be fixed from the dashboard side, but it reveals that the grid proxy's stress load isn't the best.

Indeed there is a limitation but in this case it is more about the amount of requests that can be made to the db.
The db configuration sets a concurrent connections limit for PostgreSQL that prevents more connections than the maximum size. The client also set a limit for the number of connections (pool), When the limit is hit, new requests have to wait until the ongoing queries end and give up their connections. the wait will be also limited to some seconds (actual value is depends on how this is configured also) then these pending requests would timeout and gives such a nice error.

Checking our db instance,

```bash
root@processor-db-75b55b9864-2vjmp:/# psql -U postgres -c 'SHOW max_connections;'
 max_connections 
-----------------
 100
(1 row)
```

We have 100 as the maximum number of connections which sets the maximum number of concurrent connections allowed by the db server. That can handle maybe 1000 requests if the queries are fast enough. However, if the queries take too long to run, or if some code fails to close or dispose the connection properly, or if the server is overwhelmed by a large number of requests, or the size of the db connection pool maintained by the gridproxy are not set properly, then this error is likely to occur.

The purpose of this issue is to identify the root cause of the problem and to determine whether the max_connection parameter needs to be increased or other optimizations or fixes need to be explored such how to size the connection pool properly, so that it can handle the expected workload without exhausting the server resources or causing connection timeout errors ..

**Comment by xmonader** [comment]
postgres should be able to handle more than this? Why is also not pooled? and most importantly why do we need such many connections?

**Comment by sameh-farouk** [comment]
> postgres should be able to handle more than this? Why is also not pooled? and most importantly why do we need such many connections?

@xmonader I was looking at the code and searching for how to configure the connection pool properties for Go’s sql.DB, as it seems we are not setting the maximum number of connections in the pool. I came across this useful article that explains how to manage connections pool in Go:

https://www.alexedwards.net/blog/configuring-sqldb

Exceeding connection limits section talk about what could be exactly the issue.

It explains that if you don’t set a limit on the number of open connections in your pool, you may run into this error when the pool tries to open more connections than the database instance can handle (`max_connections` in `postgresql.conf`). The author suggests setting the pool size (using `SetMaxOpenConns()` method) to a value lower than the `max_connections` parameter in PostgreSQL, which is 100 by default. 

From the article:
> As a rule of thumb, you should explicitly set a MaxOpenConns value. This should be comfortably below any hard limits on the number of connections imposed by your database and infrastructure.

According to @A-Harby’s comment, the dashboard sent too many requests to Gridproxy due to a bug or inefficient code/queries.

Subsequently, the database reached its limit of connections and could not accept any more requests because the client pool capacity was unlimited (not set).
