### ISSUE TITLE
Too aggressive reconnect attempts

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgrid-sdk-go#316]
## Describe the bug

We should avoid too aggressive/fast reconnect attempts when the relay is not available. We don't want to DDOS our servers with our own application. 

A better / resource efficient choice would be to attempt an immediate reconnect, followed by a wait time that increases exponentially with each failure. this known as exponential backoff strategy.
Alternatively, we could also use a fixed wait time of one second maybe after each reconnect attempt.

In the current implementation, I saw about 30 connect attempts per second which isn't optimal.

## Screenshots

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/42457449/ac12e50f-e385-45c6-92e7-08998ee043ee)

**Comment by muhamadazmy** [comment]
The `reconnection` happens here. 
https://github.com/threefoldtech/tfgrid-sdk-go/blob/development-direct-refactor/rmb-sdk-go/direct/connection.go#L132

I usually (like in rmb-peer) add waits before retrying to reconnect. We can introduce similar approach here or as @sameh-farouk suggested.

I will reassign to mario
