### ISSUE TITLE
improve the gpu indexing with the change in number of nodes

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#322]
Right now we run the indexing goroutine every 1hr (it's configurable), however maybe we should also do better if the number of the nodes changes before and after? and we can even improve by indexing  the newest ones first?

**Comment by Omarabdul3ziz** [comment]
we kept the periodically running ticker to requery the nodes and upsert the GPUs info each hour.
also for newly added nodes a Postgres trigger is added on the node table which will notify the client with the added node twin id and then the client will ask the node with an RMB call if it has a GPU or not.

but this focus on enhancing the indexing process for newly added nodes, not for the nodes updated with add/remove gpu,  also considered using a trigger depending on another field that changes whenever a new GPU is added, even if it's added to a node already in the table. but couldn't find something like that

do you have any suggestions or immediately indexing the new node is enough?

**Comment by A-Harby** [comment]
When a new node is added with a GPU, the Postgres database is triggered with notify_nodes_count_changed, and the node data is added.

For enhancement, it will be more visible on the mainnet, and if more improvement is needed, reopen the issue.

**Comment by Omarabdul3ziz** [comment]
Update:
had to reopen this because the implementation wasn't stable, had a bit more complexity than needed, and relied on a postgres feature.
we rolled back the code using these two prs #475 and #480.
and a new release `v0.11.6` without these changes is now deployed.

Note:
consider checking the last row in the node table and, if it's changed, trigger a reindex

**Comment by ramezsaeed** [comment]
Current implementation:
- each 1 hour the indexer will call all the nodes to get its' gpu info if it has one
- each 5 min a check will run to watch the node table count if it is changed it will trigger the indexer to run, if not it will do nothing

**Comment by ramezsaeed** [comment]
Test in Progress:
Add Test coverage here:
https://app.testlodge.com/a/26076/projects/40893/suites/228929?expand_section=423253#suite_section_423253
