### ISSUE TITLE
can't specify the node without GPUs using CLI

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-go#324]
## Describe the bug

Specifying a node using tf-grid-cli will result in an error saying you have to specify GPUs

## To Reproduce

- run `tf-grid-cli deploy vm --name anyname --ssh ~/.ssh/id_rsa.pub --node 12`

## Expected behavior

To try deploying on the node not fail because a GPU is not specified.

**Comment by mohamedamer453** [comment]
Verified on devnet.

Using the latest release `0.10.4` i was able to deploy a vm with the `--node` flag without specifying a gpu and it was deployed without any issues.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/3b2b3107-4670-45a4-9eae-2cb534cc7d78)
