### ISSUE TITLE
Add country filter on farms endpoint

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-go#329]
The playground is using now the farm filters at the beginning so the country should be there to provide the farms within a certain country.

Related: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/862

**Comment by A-Harby** [comment]
Verified Devnet.
Docs and swagger was updated with country filter.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/4c4155a7-7d43-4fc2-a2d7-b84c01742c31)
And Endpoint is working fine with both sensitive and insensitive cases.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/627171b9-a215-4e91-8986-754346f6e5e2)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/cb3bf56a-eeb2-47fc-aa77-12a29af947e2)
