### ISSUE TITLE
Swagger docs: update the certification types for the `/nodes` endpoint

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-go#335]
## Describe the bug

While updating the description of the `certification_type` for the `/farms` endpoint in https://github.com/threefoldtech/tfgrid-sdk-go/issues/62 the same values were also updated for the `/nodes` endpoint.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/c1735ac2-9ede-436a-9919-3f98dbffeef5)

## Expected behavior

For the `/nodes` endpoint the `certification_type` should either be DIY or Certified not silver, gold, notCertified

**Comment by khaledyoussef24** [comment]
verified 
Now, nodes have different options for the end points 
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/fd55e525-4008-41b4-8b91-edb7c1463a61)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/2ac4af25-ca28-42d0-ae66-204c62de5d8f)
