### ISSUE TITLE
The `realy` and `public_key` filters in the `/twins` endpoint are not documented in swagger

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-go#336]
## Describe the bug

The `realy` and `public_key` filters in the `/twins` endpoint are not documented in the swagger docs.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/5b57fe25-768a-499b-b8a9-66b89f1d8aeb)

both filters are working fine but there's no documentation for them in the swagger page.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/1eac2b92-9ec8-4f36-9362-16e09d9eda07)

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/101194226/80dbf896-ce34-4eb3-bbed-96d34f851d19)

**Comment by khaledyoussef24** [comment]
the swagger endpoint are added and works fine now
relay:
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/f29ad7bf-ebe5-4964-8732-b838fccc5be0)
public key:
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/90fb41d1-272d-4811-85fd-17ee06de0edc)

test lodge :https://app.testlodge.com/a/26076/projects/40893/suites/211680?expand_section=354530#case_4163835
