### ISSUE TITLE
ensure that server and client implementation return the same types

### ISSUE THREAD

**Issue by mariobassem** [threefoldtech/tfgrid-sdk-go#343]
our gridproxy go client implements the [Client](https://github.com/threefoldtech/tfgrid-sdk-go/blob/75aa8943c973dd084b2bcb2373bd1eb0dab0f960/grid-proxy/pkg/client/grid_client.go#L15) interface.
but there is actually no guarantee that the http server will return the same types.
the server then should have a member that implements the client interface.

**Comment by xmonader** [comment]
is the PR scope still the same for the issue?
if not please close and create another issue

**Comment by mariobassem** [comment]
yes it's the same, the pr only resolves this issue. there're just some conflicts, will resolve them

**Comment by mariobassem** [comment]
resolved conflicts
