### ISSUE TITLE
renaming for stats and counters

### ISSUE THREAD

**Issue by mariobassem** [threefoldtech/tfgrid-sdk-go#345]
stats and counters are used interchangeably in the proxy 
https://github.com/threefoldtech/tfgrid-sdk-go/blob/75aa8943c973dd084b2bcb2373bd1eb0dab0f960/grid-proxy/internal/explorer/server.go#L102-L107 
maybe stick with `statistics` or just one of them?

**Comment by Omarabdul3ziz** [comment]
work is done: pr in review

renamed all to `stats` to be aligned with the name of the endpoint `/stats`

**Comment by khaledyoussef24** [comment]
verified stats endpoint renamed and now reachable by using
https://gridproxy.dev.grid.tf/stats
![Screenshot from 2023-12-27 19-45-59](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/ac131ea7-8bd6-4d00-93df-1ff4b8bf2ab6)
