### ISSUE TITLE
support sorting contracts

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-go#349]
In playground we are making 3 requests to get the contracts using graphql, we can do only one request to gridproxy and get all the contracts we need, but as the gridproxy support pagination, we need to support sorting as well. we can't support sorting in Vue while we have external sorting.
the current situation in playground is working fine but in case the user have to many contract the sorting may not preforming well  
- #324
## Describe the solution you'd like

support sorting by: 
- ID
- Type
- State"
- Billing Rate
- Solution Type
- Solution Name
- Created At
- Expiration
- Details

**Comment by Omarabdul3ziz** [comment]
work is done: pr in review
add two new params:
- `sort_by`: that can take any of the contract field
- `sort_order`: that can be `desc` or `asc`. `desc` is the default

**Comment by muhamadazmy** [comment]
@Omarabdul3ziz please check the review on your PR

**Comment by khaledyoussef24** [comment]
verified 
env used : devnet
sorting now works with contracts supporting

1. ID
2. Type
3. State
4. Billing Rate
5. Solution Type
6. Solution Name
7. Created At
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/56f4a537-4736-47b7-8ea1-bbb09601d58f)

[Screencast from 12-21-2023 03:26:26 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/840fca2a-b6f8-4362-9b84-16c6a084677d)

test lodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4160543
