### ISSUE TITLE
Support sorting for nodes and farms 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-go#350]
As gridproxy supports pagination we have to use external sorting as well, not sure what is the required sorting keys but the current ones in dashboard for the farms is the farm id and farm name only 
- #349 
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/45

**Comment by Omarabdul3ziz** [comment]
work is done: pr in review
add two new params:
- `sort_by`: that can take any of the node/farm field
- `sort_order`: that can be `desc` or `asc`. `asc` is the default

**Comment by khaledyoussef24** [comment]
verified now you can sort nodes and farm by order (ascending by default).
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/5976a181-96f7-4017-bfe5-7e4e67c5ff7b)
desc
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/2d3a3299-b0dd-47ff-8440-323d93208f6a)

swagger also updated
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/54e758d3-4ea7-491e-9d71-b889e9a21e44)


testlodge:
https://app.testlodge.com/a/26076/projects/40893/suites/211680?expand_section=354530#case_4157422
