### ISSUE TITLE
add monitoring bridge tests

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/tfgrid-sdk-go#383]
original issue:
- https://github.com/threefoldtech/tf_operations/issues/1920

**Comment by A-Harby** [comment]
I got this error after running the bot with the [How to start](https://github.com/threefoldtech/tfgrid-sdk-go/tree/development/monitoring-bot#how-to-start) steps.

```
TfChain Bridges to Stellar Monitor Results:

- Bridge for devnet is working ✅
 Account balance reports:
  - Original balance: 284.095626 TFT
  - Balance after deposit with stellar bridge: 293.095626 TFT
  - Balance after withdraw with stellar bridge: 283.094608 TFT

- Bridge for qanet is working ✅
 Account balance reports:
  - Original balance: 99.989816 TFT
  - Balance after deposit with stellar bridge: 108.989816 TFT
  - Balance after withdraw with stellar bridge: 98.988798 TFT

- Bridge for testnet is not working ❌
failed to verify destination account: Get "https://horizon-testnet.stellar.org/accounts/GA2CWNBUHX7NZ3B5GR4I23FMU7VY5RPA77IUJTIXTTTGKYSKDSV6LUA4": dial tcp: lookup horizon-testnet.stellar.org on 127.0.0.53:53: read udp 127.0.0.1:35298->127.0.0.53:53: i/o timeout

- Bridge for mainnet is not working ❌
failed to verify destination account: horizon error: "Resource Missing" - check horizon.Error.Problem for more information
```

**Comment by Omarabdul3ziz** [comment]
wip: trying to debug what happens with stellar public bridge.

**Comment by Omarabdul3ziz** [comment]
Update:
- tested all the networks bridges transactions to/from using tfconnect app and the dashboard. and they are working fine with no issues.
- found an issue creating the stellar client and fixed it * which was causing the errors appeared on harby comment above *
- but we still face a problem on main/test bridges with status code `tx_insufficient_balance` or `tx_insufficient_fee` 
  tried to modify the fee and the sent amount but nothing worked.
  double-checked the const addresses for bridges/issuer and they are correct.
  tried to reproduce the same issue (same account balance and same fee/sent amount) on dev/qa but it works fine.


will continue reading the docs and debugging on this.

**Comment by Omarabdul3ziz** [comment]
Progress update:
kept debugging with @sameh-farouk and @AhmedHanafy725 and we reached that to make transactions from stellar to the tfchain you have two options:

1. the sender wallet on Stellar has some XLM (even if we are sending TFT) to be used as fees.

2. use the [Sponsored Reserves](https://developers.stellar.org/docs/encyclopedia/sponsored-reserves) feature and custom service we have [Transaction funding Service](https://github.com/threefoldfoundation/tft-stellar/tree/master/ThreeBotPackages/transactionfunding_service#transaction-funding-service) to manage the transection fees. and that is how it is done in Threefold connect app.

funded the wallet with some xlm (first approach) and it worked. still exploring the other option.
  ![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/32527347/bbaf8dc6-2545-42a7-af7c-9b384a8f64ed)

**Comment by Omarabdul3ziz** [comment]
Update: we will go with the first approach by funding the wallet with some xlm. mentioned this in the docs

**Comment by A-Harby** [comment]
Verified, https://github.com/threefoldtech/tfgrid-sdk-go/pull/427
The amount was decreased to 2 TFT.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/a648b8de-7e71-4cd5-b0cd-fd31bc0b622a)
And Note was added to have some XLM in the wallet.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/fc5ee607-d39b-4d10-ac4e-1c0fa455195d)

And after running it, it was running with no error, and a message was sent to both Testnet and Mainnet.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/37544841-f76c-4e90-b13f-6e9ca5833886)
