### ISSUE TITLE
gateway fqdn is not working CLI

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#386]
## Describe the bug
grid cli, v0.11.2

the gateway fqdn command is not working.
`tf-grid-cli deploy gateway fqdn -n gatewaytest --node 14 --backends http://93.184.216.34:80 --fqdn example.com`

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/b7bba0e2-242c-4f79-9d29-4c15a533e4ab)

**Comment by rawdaGastan** [comment]
the fqdn you provide should point to the node `14` ip
