### ISSUE TITLE
(Mainnet verifications) duplicated nodes records

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/tfgrid-sdk-go#387]
## Describe the bug
caused by the joins to the `node_gpu` table. when there are two cards with the same `node_twin_id`.

## Original issue
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1106

**Comment by khaledyoussef24** [comment]
env used : mainnet
version : 2.2.0

verified issue is no longer reproducible 
tried many cases 
![Screenshot from 2024-01-16 13-13-09](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/035cf3b3-c811-45ac-8c8e-53883bf32a7e)
![Screenshot from 2024-01-16 13-12-56](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/47ca295e-f7d6-4f47-8384-dc55d6ce739e)
