### ISSUE TITLE
Monitoring bot is having a problem with the websocket

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#403]
## Describe the bug

I followed the steps mentioned here [How to start](https://github.com/threefoldtech/tfgrid-sdk-go/tree/development/monitoring-bot#how-to-start), and the bot worked fine in first message but in the second message this happened and it kept going like this for a while until I had to stop it.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/9eaa7db1-51cd-403d-b348-85d03453aa90)

Farm name is Freefarm and MINS=3, I filled out all the fields in the .env (including the stellar fields which could be the reason for this to happen)

**Comment by rawdaGastan** [comment]
We have limited proxy msgs since:
- https://github.com/threefoldtech/tfgrid-sdk-go/issues/85

So, it won't send and messages unless all random nodes failed or proxy is not working for a network
the readme is updated

**Comment by A-Harby** [comment]
> We have limited proxy msgs since:
> 
> * [Reduce proxy test bot messages #85](https://github.com/threefoldtech/tfgrid-sdk-go/issues/85)
> 
> So, it won't send and messages unless all random nodes failed or proxy is not working for a network the readme is updated

Depending on previous [issue](https://github.com/threefoldtech/tfgrid-sdk-go/issues/85), errors are to prevent spamming but code is working fine.
