### ISSUE TITLE
Add new query on the nodes endpoint to get nodes owned by a certain twin id

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-go#417]
in the dashboard, there is a table that lists the nodes for the currently logged-in user but to get these nodes, it has to get the user's farms first then get the nodes belonging to these farms. It would be better if we could do that with a single request.

**Comment by Omarabdul3ziz** [comment]
work is done:
added the new param `owned_by` to the `/nodes` endpoint, pr is in review
