### ISSUE TITLE
investigate schema update for gridproxy

### ISSUE THREAD

**Issue by mariobassem** [threefoldtech/tfgrid-sdk-go#418]
some sql queries in gridproxy db have low performance. we need to investigate changing db schema to be more denormalized, so that we can efficiently access data.

**Comment by Omarabdul3ziz** [comment]
this pr https://github.com/threefoldtech/tfgrid-sdk-go/pull/533 already did some changes in the schema adding two denormalized cache tables for node/farm that improved the speed of the queries
