### ISSUE TITLE
Update the dedicated field on nodes endpoint to be true if the node is free

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-go#420]
The current dedicated field can be only `true` if the node is in a dedicated farm but if the node is free (can be dedicated in this case), it will be set to `false`.

**Comment by Omarabdul3ziz** [comment]
Work is done:
in the mentioned pr, we updated the logic of deciding if the node is dedicated or not by including nodes that:
- belongs to a dedicated farm
- have no active node contracts
- have an active rent contract
