### ISSUE TITLE
Supporting Filtering Objects by ID List in gridProxy

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-go#423]
**Description:**

### Problem Statement:
Currently, gridProxy lacks the ability to filter objects based on a list of specific IDs. This functionality is crucial for efficient data retrieval and manipulation, especially when dealing with large datasets. The absence of such a feature limits the flexibility and usefulness of the proxy.

### Proposed Solution:
Implement the ability to filter objects in gridProxy by a list of data or specific IDs. This will enhance the proxy's functionality and provide users with a powerful tool for querying and managing their data.

### Details:
- **Endpoint:** `/nodes`
- **Filtering Parameter:** `node_id__in=[1,2,3]` (Example)
- **Expected Behavior:** When the filtering parameter `node_id__in` is provided in the URL, the gridProxy should filter the nodes based on the provided list of IDs (in this example, IDs 1, 2, and 3).

The same goes for all fields e.g. if I want to filter with multiple statues it'll be like => `status__in=['up', 'down']`.

**Comment by xmonader** [comment]
While I understand the need, this is already implemented in the graphql. Which story is this needed for? can it be in 3.13?

**Comment by Mahmoud-Emad** [comment]
@xmonader

The usage of it can be in several cases; here is an example.

Imagine if I have deployments on nodes 1, 2, and 3, and I want to check if these nodes are offline or online. Why not get the details of them all at once? So when filtering by their IDs, it'll be better than sending a request to load all offline nodes and then looping over them.

What do you think?

**Comment by xmonader** [comment]
I understand, but still relevant to which story in tfgrid-sdk-ts?

**Comment by Mahmoud-Emad** [comment]
This issue, https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1220, instead of requesting to load all offline nodes and then looping over them to check if the node ID matches the deployment node ID, it'll be better to get only the nodes that I really need.

**Comment by Omarabdul3ziz** [comment]
we already provided filtering by list for some filters like
- `/nodes?farm_ids=1,2`
- `/nodes?status=up,standby`
- `/contracts?state=Created,GracePeriod`

will work on adding it for `/nodes?node_id`

**Comment by Omarabdul3ziz** [comment]
verified the new filter `node_ids` https://gridproxy.dev.grid.tf/nodes?node_ids=11,14,1,9999,16
returns nodes 11,14,16 
and the old filter `node_id` is still that same
