### ISSUE TITLE
update the monitoring bot docs

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#431]
## Describe the bug

The old name was monitoring-bot, but now it is tfgridmon.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/52458abd-25e1-4463-b9be-6764d6ebd935)
So the documents need to be updated.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/9eec7d8b-da7a-42d0-951a-de99b7846282)

## To Reproduce

Just change the directory to the monitoring bot and run `make build`.

**Comment by khaledyoussef24** [comment]
verified building fine now
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/ca8b15cf-706a-4523-9d3c-60b0483d3c0a)

**Comment by ramezsaeed** [comment]
directory name change again to the old name "monitoring-bot" and working fine now
