### ISSUE TITLE
Incorrect Bad Request response for the `nodes/{node_id}` endpoint

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-go#44]
### Description

The response for bad requests in the `nodes/{node_id}` endpoint is incorrect. currently it shows `404 page not found` for invalid requests however it should show something like `Bad Request` or `Invalid Request Format`

![image](https://user-images.githubusercontent.com/101194226/224691014-0bde8b7a-05a3-46fa-90c5-57caace4d758.png)

![image](https://user-images.githubusercontent.com/101194226/224691061-0522efa6-84fe-48d0-896e-32a20f796aef.png)

**Comment by maayarosama** [comment]
The ``` 404 Page not found ``` is accurate right as the routes that requires a nodId only accepts numeric characters as shown bellow
![Screenshot from 2023-06-11 13-38-38](https://github.com/threefoldtech/tfgrid-sdk-go/assets/66883096/4f5f89b1-1625-4e2c-8216-848fdfb63597)

If we want to show a ``` Bad Request message ``` we'll have to refactor all the routes and make them accept alphabetic characters.

**Comment by mohamedamer453** [comment]
Closing since the current input validation is correct and is sufficient enough.
