### ISSUE TITLE
The `randomize` query is already supported by gridproxy but not mentioned in Swagger docs

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-go#447]

**Comment by Omarabdul3ziz** [comment]
yes, noticed that and added it in this pr, https://github.com/threefoldtech/tfgrid-sdk-go/pull/459

**Comment by khaledyoussef24** [comment]
verified .
it can be found in the swagger now
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/51d22a07-efdc-46a7-a117-810a42c4a7d6)
