### ISSUE TITLE
support certified filter on nodes endpoint

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-go#45]

**Comment by mohamedamer453** [comment]
Verified on devnet.

The `certification_type` parameter was added to the nodes endpoint and it's working fine with the 2 available options `Diy` & `Certified`.

![image](https://user-images.githubusercontent.com/101194226/230773355-9a40e0b9-28fc-4c79-9b59-592a985158e9.png)

![image](https://user-images.githubusercontent.com/101194226/230773411-c71e7bba-d491-42ec-8c4d-34a02d1ccb90.png)


However the swagger docs were not updated with the new parameter `certification_type`

**Comment by A-Harby** [comment]
Verified,
Docs and swagger have been updated.
![image](https://user-images.githubusercontent.com/109473873/234604404-ed09f872-d490-4e2e-a063-9e7394f67195.png)
