### ISSUE TITLE
Add ssh key space and newline trimming 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#450]
## Describe the bug

CLI ssh key should have a space and newline trimming.

## To Reproduce

Run tf-grid-cli and deploy any solution, and provide ssh either in the command or through a file using the ssh option.
`tf-grid-cli deploy vm --name examplevm --ssh ~/.ssh/id_rsa.pub --cpu 1 --memory 1 --disk 10`

## Expected behavior

SSH should be validated, and any extra spaces or newlines should be removed.

## Screenshots

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/a696df51-0d2d-4da4-9e6f-4c5a39fc4334)

**Comment by xmonader** [comment]
The thing is i could be passing `~/.ssh/authorized_keys`, which is a list of sshkeys concatenated together by a new line. What should we do in that case? I think it's fine if nothing is affected tbh

**Comment by xmonader** [comment]
please ropen if you need to discuss
