### ISSUE TITLE
Add option to provide ssh key in the command

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#451]
## Describe the bug

Grid CLI should provide a way to type ssh key in the command to give the user option to deploy a solution without only using his own ssh key or a file containing that ssh key.

## Screenshots

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/d98818fd-9813-41e2-990b-d0b5faf5261c)

**Comment by xmonader** [comment]
but it should be a file not string, please remove from 3.12 testrun, files are more ergonomic in case of long strings like sshkeys. please reopen if you think we need to discuss
