### ISSUE TITLE
VMs get assigned the same IP on different deployments

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-go#457]
## Describe the bug

Deploying multiple VMs on the same network but different deployments assign the same private IP to the VMs.

## To Reproduce

- Create two deployments with one VM
- Assign the deployments to a network
- Deploy network then deployments
- Check the private IPs of the VMs it should match

## Expected behavior

On a private network VMs shouldn't have the same IP even in different deployments

## Related issue

- https://github.com/threefoldtech/terraform-provider-grid/issues/781

**Comment by rawdaGastan** [comment]
Tested, the deployments now got assigned with different private IPs on the same network

- case1: same network different nodes:
```console
IP1: 10.20.2.2
IP2: 10.20.3.3
```

- case2: same network same node:
```console
IP1: 10.20.2.2
IP2: 10.20.2.3
```

also solves: 
- https://github.com/threefoldtech/tfgrid-sdk-go/issues/478

problem:
- for case1 the IP should be `10.20.3.2` not `10.20.3.3`

issue:
- https://github.com/threefoldtech/tfgrid-sdk-go/issues/545
