### ISSUE TITLE
add validation on query params

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/tfgrid-sdk-go#461]
in case passing undefined params in the URL it will be ignored and no filtration will happen. so `/nodes?total_cro=24` will return the same response as `/nodes` without any filtration. they may lead to a typo in the query params goes un-noticed

**Comment by Omarabdul3ziz** [comment]
do this with the schema package from [this pr](https://github.com/threefoldtech/tfgrid-sdk-go/pull/315)

**Comment by xmonader** [comment]
Is this still in accepted? I can see a PR merged referencing this issue?

**Comment by Omarabdul3ziz** [comment]
yes. still no work done on this yet, I just mentioned in a conversation on the merged pr that we have an issue for the validation of the queries
