### ISSUE TITLE
Add ips of kubernetes worker after deploying in CLI

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#462]
## Describe the bug

Can't we also show the ygg ip of the workers? It would also help the user to show that it was successful for both master and worker, and here are the ips of them.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/37d1bb66-5b74-44db-be62-3de2ed96f372)

**Comment by Eslam-Nawara** [comment]
## Work Completed:
- update the cli to show all master and workers available ips

**Comment by AbdelrahmanElawady** [comment]
Verified and the workers IPs are included with the output:
```console
$ tf-grid-cli deploy kubernetes -n examplektest11 --ssh ~/.ssh/id_rsa.pub --workers-number 2      
1:41PM INF starting peer session=tf-437467 twin=192
1:41PM INF deploying network
1:42PM INF deploying cluster
1:42PM INF master wireguard ip: 10.20.2.2
1:42PM INF master yggdrasil ip: 300:d205:aee5:1d1e:680c:7abf:e9ff:c55d
1:42PM INF worker1 wireguard ip: 10.20.3.3
1:42PM INF worker0 wireguard ip: 10.20.3.2
1:42PM INF worker1 yggdrasil ip: 301:b989:8977:ff23:593b:d90c:7417:30de
1:42PM INF worker0 yggdrasil ip: 301:b989:8977:ff23:5615:17fc:1220:e0d5
```
