### ISSUE TITLE
Assigning IPs to deployments on different nodes is faulty

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-go#478]
## Describe the bug

The way assigning IPs to VMs goes as follow:
- We get the network subnet
- Start from the last octet of 2 up to 254
- If not used before assign to the VM

This flow works fine for deployments on the same node as it is expected to be in /24 range on the same node. However, for multiple node deployments it will also assign IPs to the VMs in the same range which is wrong as it should be on different /24 range.
For example:
- A CIDR of 10.20.0.0/16.
- IPs for the first node in the network will be 10.20.2.0/24.
- For another node it will be also be in 10.20.2.0/24 which is a problem.

## To Reproduce

- Create a deployment with VM on a node.
- Create another on a separate node but in the same network.
- IPs of the VMs will be different but still in the same /24 range.

## Expected behavior

Nodes should have different subnets so for the previous example first node should be 10.20.2.0/24 while the other should be 10.20.3.0/24 but all under 10.20.0.0/16

**Comment by rawdaGastan** [comment]
I tried to deploy 2 vms on the same network using 2 different nodes and I got different IPs (subnets)
I used batch for deploying networks

```console
IP1: 10.20.2.2
IP2: 10.20.3.3
```

**Comment by AbdelrahmanElawady** [comment]
I tried reproducing the issue again but for some reason I couldn't. I either made a mistake while creating the deployments during the time of this issue or it got fixed somehow (unlikely). I think it should be closes for now and reopened in case it happened again.
