### ISSUE TITLE
Add new field on nodes endpoint for dedicated farms

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-go#483]
based on #420, now the dedicated field says that the node is dedicated when it's free but we can't distinguish if the node is in a dedicated farm or not to allow the deployment on it. So we need a new boolean field for the node in dedicated farms

**Comment by khaledyoussef24** [comment]
an end point to dedicated node is now reachable
and it is available on swagger also

![Screenshot from 2023-12-27 13-59-55](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/335ed8df-1940-4a61-9235-fe0fc1c50388)
![Screenshot from 2023-12-27 14-00-57](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/d081c5f8-a507-4a19-8ced-4b0415e68106)

test lodge : https://app.testlodge.com/a/26076/projects/40893/suites/211680?expand_section=354530#case_4163774
