### ISSUE TITLE
rewrite the farmerbot in go

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#484]
there's a lot of instability in the v version combined with the instability in components + the requirement of having rmb-peer and http server exposing the sdk-ts functionality.

Rawda did some initial work on the a farmerbot version before in go, and it's time to revive, and revise it. Please also introduce simplification in the configurations format, toml or yaml should be very intuitive options ✌🏼

**Comment by rawdaGastan** [comment]
v repo: https://github.com/threefoldtech/farmerbot
go repo: https://github.com/rawdaGastan/farmerbot

farmerbot:

we have 3 managers:
1. node manager
2. farm manager
3. power manager

Jobs can be sent to the farmerbot using RMB

farm manager jobs:
1. define: to define a new farm

node manager jobs:
1. define: to define a new node
3. fine_node: to find a node (returns a node ID)
```
- _has_gpus_ => if you require one or more gpus you can filter on that with this parameter (should be a positive value)
- _gpu_vendors_ => a list of strings that will be used to filter the nodes on gpu vendor (for example AMD)
- _gpu_devices_ => a list of strings that will be used to filter the nodes on gpu device (for example GTX 1080)
- _certified_ => whether or not you want a certified node (not adding this argument means you don't care whether you get a certified or non certified node)
- _public_config_ => whether or not you want a node with a public config (not adding this argument means you don't care whether or not the node has a public config)
- _public_ips_ => how much public ips you need
- _dedicated_ => whether you want a dedicated node (rent the full node)
- _node_exclude_ => the node ids you want to exclude in your search
- _required_hru_ => the amount of hru required in kilobytes (add suffix mb or gb to define the required resources in megabyte or gygabite)
- _required_sru_ => the amount of sru required in kilobytes (add suffix mb or gb to define the required resources in megabyte or gygabite)
- _required_mru_ => the amount of mru required in kilobytes (add suffix mb or gb to define the required resources in megabyte or gygabite)
- _required_cru_ => the amount of cru required
```
power manager jobs:
1. power on: powers on a node
2. power off: powers off a node
3. configure: configures power
```
- wake_up_threshold => a value between 50 and 80 defining the threshold at which nodes will be powered on or off. If the usage percentage (total used resources devided by the total amount of resources) is greater then the threshold a new node will be powered on. In the other case the farmerbot will try to power off nodes if possible.
- periodic_wakeup => the time at which the periodic wakeups (powering on a node that is off) should happen. The offline nodes will be powered on sequentially with an interval of 5 minutes starting at the time defined in periodic_wakeup.
- periodic_wakeup_limit => by default only one node will be woken up every 5 minutes during a periodic wakeup. You can change that behavior by setting the periodic_wakeup_limit setting. 
```
4. periodic_wakeup: turns the nodes on according to a configured wakeup time
5. powermanagement: turns nodes on/off according to the resources usage and the configured threshold

**Comment by muhamadazmy** [comment]
It's not clear what those managers do in the comment above. Can we add link to docs. 

each module need to define:
- Role of operation, what does it's needed in general
- Automated tasks the manager does (for example, a power manager does random wake ups)
- Configuration 
- Requests that are handled by this manager
- How it work with other managers.

For example above, it seems there is a `farm manager job` to define a new farm. I have no idea what that mean

**Comment by rawdaGastan** [comment]
docs: https://github.com/threefoldtech/farmerbot/blob/development/farmerbot/farmerbot.md

**Comment by rawdaGastan** [comment]
- testing in progress 
- getting farms/nodes from substrate in progress

**Comment by rawdaGastan** [comment]
Added:
- testing the farmerbot using Brandon farm
- added examples
- sync config files updates

**Comment by rawdaGastan** [comment]
Tested here: 
- https://github.com/threefoldtech/tfgrid-sdk-go/issues/787
