### ISSUE TITLE
Should we check HDD disks with the size of SSDs?

### ISSUE THREAD

**Issue by Eslam-Nawara** [threefoldtech/tfgrid-sdk-go#491]
## Describe the bug

NodeFilter function uses the size of SSD disks as a filter for the hdd disks [here](https://github.com/threefoldtech/tfgrid-sdk-go/blob/b1ac1f1e83635d8ebe4a704892aa16587d71261f/grid-client/deployer/node_filter.go#L61) but I think we should use the HDD disks size

**Comment by rawdaGastan** [comment]
Verified, fixed here:
- https://github.com/threefoldtech/tfgrid-sdk-go/blob/development/grid-client/deployer/node_filter.go#L76
