### ISSUE TITLE
create rmb examples against zos nodes 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#493]
currently all of the examples use `calculator.add` for no obvious benefit, does zos expose a calculator.add rpc? why not use something like zos.version or something that's more intuitive ?

also please change any occurrences of `dist` to `dest`

**Comment by rawdaGastan** [comment]
create a new directory for zos examples and add an rpc example for `zos.system.version`

**Comment by AbdelrahmanElawady** [comment]
Verified and it returned the version after providing mnemonic and a node:
```console
$ go run main.go 
{"level":"debug","url":"wss://tfchain.dev.grid.tf/ws","time":"2023-12-13T15:28:57+02:00","message":"connecting"}
2023/12/13 15:28:57 Connecting to wss://tfchain.dev.grid.tf/ws...
{"level":"info","twin":192,"session":"test-client","time":"2023-12-13T15:28:58+02:00","message":"starting peer"}
output: {0.0.0-fc3562a v0.2.11}
```
