### ISSUE TITLE
[grid client] support TestableExamples

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#494]
https://go.dev/blog/examples

- [x] add an example for tfplugin creation
- [x] add an example for batch cancel contracts
- [x] add an example for deploy/batch/cancel network
- [x] add an example for deploy/batch/cancel deployment
- [x] add an example for deploy/batch/cancel gateway fqdn
- [x] add an example for deploy/batch/cancel gateway name
- [x] add an example for deploy/batch/cancel kubernetes
- [x] add an example for FilterNodes usage

**Comment by Eslam-Nawara** [comment]
WIP: 
- done creating all the testable examples for the requested functions
- the docs need some improvement as there's a comment repeated in all the files in the deployer pkg so will be removed
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/2a053967-9cbe-4ec9-bbe9-d15b8cd48cfd)

**Comment by rawdaGastan** [comment]
## Added example in [v0.12.0](https://pkg.go.dev/github.com/threefoldtech/tfgrid-sdk-go/grid-client@v0.12.0)

### add an example for TF plugin creation

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/0fc52fa5-1373-423f-b52e-4c2ce096be24)

### add an example for batch cancel contracts

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/665e8c58-122f-4763-85f9-c88a75c95308)

### add an example for deploy/batch/cancel network

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/416f1a2d-38db-4474-99fa-7f3de0405427)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/5b025cff-9412-4be3-814c-22c607e1e6a8)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/51097076-0d3f-40a9-a8e9-c82553b99f23)

### add an example for deploy/batch/cancel deployment

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/c54edb9b-52d2-4aa0-b450-6731e5e2945b)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/74507dec-75de-4632-a45a-152ce52b9927)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/76faa654-3972-433e-a27b-60abefbcbbed)

### add an example for deploy/batch/cancel gateway FQDN

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/a33fad5c-aa9d-45a8-ad8b-b7480de25a57)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/aeb8d843-a7ae-4c1a-894c-aab0d0606443)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/f42822a0-9e5d-4538-89e7-77ace7bd667b)

### add an example for deploy/batch/cancel gateway name

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/cfbfbc78-928a-4f8d-a8c1-1cec7c624a35)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/46b25c8d-3c55-4ea5-ad79-35dc870f1f19)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/28142531-bb34-4bea-89be-3fb2d69dc49a)

### add an example for deploy/batch/cancel Kubernetes

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/7277170d-37eb-4a01-9307-1319f189873a)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/e564f3d9-c8b8-4501-af77-682de41764eb)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/3c8440f0-8448-42f5-99d6-cf4a8a3ca650)

### add an example for Filter Nodes usage

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/35b2760e-25f3-4290-8809-482c65038fa6)
