### ISSUE TITLE
FilterNodes returns misleading error

### ISSUE THREAD

**Issue by Eslam-Nawara** [threefoldtech/tfgrid-sdk-go#496]
## Describe the bug
- FilterNodes returns an error ` could not find any node with free ssd pools: 15 GB` with a nodeID = 39 with 98% free ssd

## To Reproduce

try to use the grid-client to filter the nodes of mainnet with node filter with this [example](https://gist.github.com/Eslam-Nawara/23ee7f9b604c2d8195f613f21c215d9f)

## Expected behavior

expected to get one node with id 39 as it has enough storage, but it fails due to no enough storage

## Screenshots

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/acb67830-0505-4fa9-a2f8-3ad0990578dc)

**Comment by Eslam-Nawara** [comment]
In this case, the FilterNodes results with that error due to failure in HDD filtration, although the example doesn't use HDD storage at all, but it doesn't check if there's no storage required and starts checking if the requested pools are available in the node and reports failure as there's no available pools even if the required storage is none.

**Comment by Eslam-Nawara** [comment]
Work Completed: 
fixed the filtration problem and changed the error message to be more specific of what might caused the problem

**Comment by rawdaGastan** [comment]
Verified and fixed
