### ISSUE TITLE
Failed to create contract with `NodeNotAvailableToDeploy` error

### ISSUE THREAD

**Issue by Eslam-Nawara** [threefoldtech/tfgrid-sdk-go#506]
## Describe the bug

- When trying to deploy new network on 50 nodes, it fails with ambiguous error `NodeNotAvailableToDeploy`
- the error message is not informative what node is not available or why it is 

## Screenshots

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/99f4edec-2260-4156-9809-c84bcb46f981)

**Comment by AhmedHanafy725** [comment]
which network was used? (dev, test, ..)

**Comment by Eslam-Nawara** [comment]
mainnet @AhmedHanafy725

**Comment by ramezsaeed** [comment]
probably this is a rented node or dedicated node,
need to fix the error to be clear.

**Comment by muhamadazmy** [comment]
What about @Eslam-Nawara I assign this to you and you try to figure out where this error is coming from and why, and maybe extend the error message with relevant information

**Comment by Eslam-Nawara** [comment]
This error is no longer showing since I used `AvailableFor` for filtration, so I think the problem was the node was rented, dedicated, or in a dedicated farm as ramez mentioned, maybe we should just add the id of the failing node for more information and maybe add the failure cause too if available

**Comment by Eslam-Nawara** [comment]
The error is returned from the tfchain so I think the update should be to the respons message send from the chain to be more specific about why the node is not available to deploy

**Comment by rawdaGastan** [comment]
Verified. 
`Available for` filter is added now and the error doesn't appear anymore

https://github.com/threefoldtech/tfgrid-sdk-go/blob/b02cae7ddb3c4ec68ddc5c6309ca57479e449748/grid-client/deployer/node_filter.go#L29-L32
