### ISSUE TITLE
add encoding/decoding formats as an option to the peer

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/tfgrid-sdk-go#507]
- Add peer encoding/decoding format and schema which means the user has to specify this as a value during creating a new peer.
- Also make sure to move the NewPeer functions args to a new struct `PeerOptions` to deal with arguments and default values.

suggestion: https://golang.cafe/blog/golang-functional-options-pattern.html

**Comment by AbdelrahmanElawady** [comment]
Update:

- Peer now takes non-required arguments through options.
- Peer now uses an Encoder interface to manage encoding payloads.
- The interface allows for more schemas support in the future.
