### ISSUE TITLE
examples documentation for perf does not open

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-go#513]
## Describe the bug

examples documentation for perf does not open

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/10599be1-f757-42bc-872e-3ec9a178d74a)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/38089fdf-bdfe-4f5d-a31f-a95af6cd11fe)
and it is opening a path 'rmb-sdk-go/examples/client_rpc/main.go'

**Comment by rawdaGastan** [comment]
It should be `rmb-sdk-go/examples/client/main.go` not `rmb-sdk-go/examples/client_rpc/main.go`
Can you specify where you found the perf docs?

**Comment by khaledyoussef24** [comment]
sure 
https://github.com/threefoldtech/zos/tree/main/docs/tasks

**Comment by xmonader** [comment]
Why was this open in sdk-go repo? 

another issue in zos tracked https://github.com/threefoldtech/zos/issues/2151
