### ISSUE TITLE
research: postgrest

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#523]
https://postgrest.org/en/stable/index.html and see how can we protect the resources from being updated or even create the user accessing the database with readonly access.

**Comment by Omarabdul3ziz** [comment]
I did some research and explored the tool, finding that it generates sql (dml) queries based on url parameters.
After a thorough examination, it looks like the tool can perform operations comparable to both GraphQL and GridProxy. 
- horizontal/vertical filtering on each table (similar to graphql)
- and inter-table filtering by utilizing another table's fields (similar to gridproxy)
- Additionally, it handles the basic operations like ordering, limiting, and aggregations.

Despite its capabilities, it doesn't seem to bring any additional benefits compared to our existing toolset.
- but it could be suitable for scenarios requiring raw data access and custom filtering. However, using its calls for client applications will not be reliable. 
- even if it provides users with flexibility for custom queries, it introduces complexities related to understanding the schema and writing correct joins.

Some notes to consider if we going to do it:
- regarding security,  all requests directed to the database through the postgrest server coming from a configured role. so setup should ensure read-only access, preventing unintended transactions on the database.
- to leverage the 'Embedded resources' feature, which essentially joins two tables, will need to update the schema by adding proper foreign keys between tables, like farm/node. currently, the joins are based on conditions, which doesn't align with how the embedded resource feature works.

**Comment by Omarabdul3ziz** [comment]
we don't have even a read access  to the database now  after changing the stack to docker-compose instead of k8s, we can consider this approach to expose the raw data for debugging cases
