### ISSUE TITLE
integration test `TestBatchGatewayNameDeployment` skipped with no available nodes found

### ISSUE THREAD

**Issue by Eslam-Nawara** [threefoldtech/tfgrid-sdk-go#530]
trying to run [this](https://github.com/threefoldtech/tfgrid-sdk-go/blob/development/grid-client/integration_tests/batch_gateway_name_test.go) integration test on devnet but skipped with couldn't find any available nodes with filters:
```go
var nodeFilter = types.NodeFilter{
	Status:  &statusUp,
	FreeSRU: convertGBToBytes(5),
	FreeHRU: convertGBToBytes(2),
	FreeMRU: convertGBToBytes(1),
	FarmIDs: []uint64{1},
	Rented:  &falseVal,
	Domain:  &trueVal,
}
```

the test needs two nodes to be able to run

**Comment by xmonader** [comment]
It's fine, mark the tests as skipped with this issue ticket

**Comment by Eslam-Nawara** [comment]
Now there are two nodes with gateway, the resources shouldn't be a problem anymore

**Comment by rawdaGastan** [comment]
### Verification

- It is working now 👍🏻 

```
2024/01/16 11:10:27 network: dev
11:10AM INF starting peer session=tf-784793 twin=81
--- PASS: TestBatchGatewayNameDeployment (98.02s)
PASS
ok      github.com/threefoldtech/tfgrid-sdk-go/grid-client/integration_tests    98.032s
```
