### ISSUE TITLE
k8s deployment with WGAccess failed with `could not list node interfaces`

### ISSUE THREAD

**Issue by Eslam-Nawara** [threefoldtech/tfgrid-sdk-go#531]
## Describe the bug

[this](https://github.com/threefoldtech/tfgrid-sdk-go/blob/development/grid-client/integration_tests/batch_k8s_test.go) integration test fails when WGAcess is required and for some reason it reports `failed to get node 11 endpoint` within the error message even when the deployment is not run using node 11 at all 

## Network
devnet

## Screenshots

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/7df73218-e330-449d-a7ff-0b6cde11aba3)

**Comment by rawdaGastan** [comment]
Verification steps:

- Deploy a Kubernetes cluster using a network with a WireGuard access
- Deployed 2 VMs using a network with a WireGuard access

It worked fine after the fix:
- https://github.com/threefoldtech/tfgrid-sdk-go/pull/537
