### ISSUE TITLE
Add extra checks for nodes being filtered

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-go#536]
## Description

Filtering nodes with the grid-client in either `deployer.FilterNodes` or `deployer.GetPublicNode` will sometime return nodes that have status "up" but not actually responsive. We need to ping the nodes as an extra check to make sure the nodes are actually up.

related: #531

**Comment by rawdaGastan** [comment]
Verified!

I tried to deploy a Kubernetes cluster and 2 VMs using a network with a WireGuard access, and it worked fine after the fix:
- now filter returns only working nodes
