### ISSUE TITLE
Batch deploy assigned IPs increment used IPS for another node's subnet

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/tfgrid-sdk-go#545]
I tried to batch deploy 2 VMs using the same network on different nodes and got

```console
IP1: 10.20.2.2
IP2: 10.20.3.3
```

problem:
- The IP should be `10.20.3.2` not `10.20.3.3`

suggestion:
- I think we should track subnets for deployments in batch to avoid using a used host for another subnet

**Comment by Eslam-Nawara** [comment]
Verification:
- deployed two VMs on two separate nodes and on the same network using `BatchDeploy` and the subnet of one vm is not affected by the other

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/126450ef-dd1d-46f0-aea0-68c6da207e36)
