### ISSUE TITLE
improve farms endpoint query performance

### ISSUE THREAD

**Issue by mariobassem** [threefoldtech/tfgrid-sdk-go#555]
farms endpoint take too long, especially with having node specific filters

**Comment by mariobassem** [comment]
added some indices and code optimizations. still testing different/random queries, and cleaning up code

**Comment by Omarabdul3ziz** [comment]
this https://github.com/threefoldtech/tfgrid-sdk-go/pull/533 should fixed the problem released with tag `v0.13.0` and deployed now on devnet
