### ISSUE TITLE
Sort by node status

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-go#566]
Sort_by is now added to nodes, However, sorting by node status is not yet implemented.

**Comment by Omarabdul3ziz** [comment]
the thing is the available sort-by criteria are fields of each table we order on. in the `status` case it is not a field of node table but calculated value based on `updated_at` and `power` fields. 
so it will need a special handling. will work on it

**Comment by zaelgohary** [comment]
Filter has a weird behavior as explained [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2134#issuecomment-1960177502).
