### ISSUE TITLE
sdk-go resilience library

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#570]
We are currently working on enhancing the resilience of our codebase. The goal is to find/implement a resilience library that is simple to use, intuitive.
We are looking for a resilience library with the following characteristics:

1. **Ease of Use:** The library should offer a straightforward and intuitive API, making it easy for developers to integrate and work with in our codebase.

2. **Reliability:** We prioritize reliability in handling errors, retries, and other resilience-related features. The library should contribute to the overall stability and robustness of our applications.

So please: 
1. Research and evaluate resilience libraries suitable for our  codebase.
2. Test the shortlisted libraries for ease of use and compatibility.
3. Provide a report summarizing findings and recommendations (including creating our own).

### Deliverables
Submit a report detailing the research, including insights into the selected library, its usage, and any potential integration considerations.

**Comment by sameh-farouk** [comment]
Here are some potential candidates (not exhaustive) for whoever is going to conduct the research.

- https://github.com/eapache/go-resiliency
It is based in part on Hystrix, Semian, and others. It currently implements patterns such as circuit-breaker, semaphore, deadline/timeout, batching, and retriable. It also has a simple and clean design.

- https://github.com/slok/goresilience
It is inspired by Hystrix and similar libraries. It is easy to extend, test, and customize. It uses the decorator pattern (middleware), like Go’s http.Handler does. It also supports Prometheus/Openmetrics metrics. You can use different runners in chains to create custom resilience flows.

- https://github.com/afex/hystrix-go
Based on Hystrix (a great project from Netflix) which is a latency and fault tolerance library designed to enable resilience in complex distributed systems where failure is inevitable.
