### ISSUE TITLE
The client has changes for the incoming tfchain runtime 147 which is not upgraded yet on live networks

### ISSUE THREAD

**Issue by Eslam-Nawara** [threefoldtech/tfgrid-sdk-go#576]
```
➜  grid-client git:(development_fix_grid-client_integration_tests) ✗ go test -v ./integration_tests -run TestBatchGatewayNameDeployment
=== RUN   TestBatchGatewayNameDeployment
batch_gateway_name_test.go:111:
                Error Trace:    /home/eslam/work/tfgrid-sdk-go/grid-client/integration_tests/batch_gateway_name_test.go:111
                Error:          Received unexpected error:
                                unable to decode field 2 event #11 with EventID [27 9], field TFTBridgeModule_BurnTransactionExpired: Unknown byte prefix for encoded OptionBool: 224
                                failed to decode event
                                github.com/threefoldtech/tfchain/clients/tfchain-client-go.(*Substrate).getEventRecords
                                        /home/eslam/.go/pkg/mod/github.com/threefoldtech/tfchain/clients/tfchain-client-go@v0.0.0-20231129121046-56ffc1f8f5c6/utils.go:495
```

**Comment by xmonader** [comment]
The events need to get synced and tfchain dependency to be upgraded

**Comment by sameh-farouk** [comment]
tfchain and the tfchain-client underwent a change in some types and events related to the bridge like the `TFTBridgeModule_BurnTransactionExpired` event as part of the upcoming runtime 147 update, but live networks have not been upgraded yet.

The current runtime is 146 for dev, qa and test networks, for main net its is 145.

The version used here as shown in the logs is dated November 23, so it is more recent and requires runtime 147 to run and an update to the dependent tools/libs as well.

Related PRs:
https://github.com/threefoldtech/tfchain/pull/888

https://github.com/threefoldtech/tfchain/pull/885

**Comment by rawdaGastan** [comment]
The chain is updated on devnet and working now
