### ISSUE TITLE
check triggering the gridproxy docker image workflow automatically 

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/tfgrid-sdk-go#597]
Currently, on each release we need to manually run [proxy](https://github.com/threefoldtech/tfgrid-sdk-go/blob/development/.github/workflows/grid-proxy-release.yml) and [farmerbot](https://github.com/threefoldtech/tfgrid-sdk-go/blob/development/.github/workflows/farmerbot-release.yml) workflow

- add docs

**Comment by rawdaGastan** [comment]
- The workflow is triggered now: https://github.com/threefoldtech/tfgrid-sdk-go/actions/runs/7462208582
- It had an issue with tags (`workflow_run` event doesn't have a reference to the latest tag/release), so it was replaced by the git command `git describe --tags --abbrev=0` to get the latest tag
- workflow succeeded: https://github.com/threefoldtech/tfgrid-sdk-go/actions/runs/7463258265
