### ISSUE TITLE
Separate types into a pkg/ importable package

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/tfgrid-sdk-go#60]
[Models](https://github.com/threefoldtech/tfgridclient_proxy/blob/development/internal/rmbproxy/models.go) resides in internal so it can't be used by an outside package. Separating it into pkg/gridproxytypes for example gives additional benefit of not requiring sub dependencies of tfgridclient_proxy in the project that uses it.

**Comment by Omarabdul3ziz** [comment]
done https://github.com/threefoldtech/tfgrid-sdk-go/tree/development/grid-proxy/pkg/types
