### ISSUE TITLE
status query is not working  as expected

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-go#602]
## Describe the bug
node shown as down while using `status=up` query

## To Reproduce

check https://gridproxy.dev.grid.tf/nodes/18?status=up&size=1

## Expected behavior
 show list only `up` status node

**Comment by Omarabdul3ziz** [comment]
as we discussed it is an invalid URL.
either filter the nodes endpoint `/nodes?status=up&size=1` or call a single node `/nodes/18`
