### ISSUE TITLE
Sometimes nodes are stuck (waking up, shutting down)

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/tfgrid-sdk-go#605]
### Description
- Sometimes when changing the power target of a node to up/down, the node's state doesn't change 

### Results
- That will exclude the node from farmer bot management, as it will not be on to be turned off and vice versa
- If the node is waking up or shutting down, the farmer bot won't periodically wake it up because it is not powered off

### Logs
- example logs from a stuck node
```
unable to decode field 2 event #5 with EventID [27 9], field TFTBridgeModule_BurnTransactionExpired: Unknown byte prefix for encoded OptionBool: 224
```

**Comment by muhamadazmy** [comment]
This means that the chain events type is different from the events types in the go client. The problem is with this encoding format used by the chain is that if one entry in the received events are wrong, the encoder fail to decode all other events in the same block.

This means either the client or the chain need to be updated to match

**Comment by muhamadazmy** [comment]
Wait, I didn't notice the full log message. This is not an `unknown event` it's actually a bad event type definition. 

This horrible encoding format use alignment and type size to decode the message. It means if for example u are decoding a `u64` but the message data only holds `u32` for example, it means the decoder will read 2 extra bytes (but will not fail) but it means than all following types are misaligned (and wrong). 

The only solution is to make sure always that changes to the types in the change has to be reflected correctly in the client.

**Comment by rawdaGastan** [comment]
fixed after chain upgrades (maybe other factors may make nodes stuck)
