### ISSUE TITLE
Include farm name in returned node details

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-go#606]
- What about adding farm name also as the farm id for node details ?

**Comment by Omarabdul3ziz** [comment]
duplicated https://github.com/threefoldtech/tfgrid-sdk-go/issues/612

deployed on dev now
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/32527347/8f17609e-ef3f-4be4-a861-e3cb5d3e820b)
