### ISSUE TITLE
allow sorting and querying nodes by price 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-go#608]
first, to allow sorting nodes based on the price, a new field should be created on the nodes view table to calculate the node's price in units based on the node resources with the following equation: 
```
priceInUnits = (cu * pricingPolicy.cu.value + su * pricingPolicy.su.value) * certifiedFactor * 24 * 30
```
> certifiedFactor = 1.25 if the node is certified otherwise 1

how to calculate the CU:
https://github.com/threefoldtech/tfgrid-sdk-go/blob/63bc34d8eb3a4d4e724c9a73ddce9cc60724e25b/grid-client/calculator/calculate.go#L123-L139

how to calculate the SU:
https://github.com/threefoldtech/tfgrid-sdk-go/blob/63bc34d8eb3a4d4e724c9a73ddce9cc60724e25b/grid-client/calculator/calculate.go#L119-L121

second, to allow querying the nodes based on the price, the user will provide the following: 
- balance (0 if not provided)
- min price (0 if not provided)
- max price (infinity if not provided)

gridproxy at this moment should get the TFT price from the TFChain and calculate the staking discounts based on the balance provided in the where clause of the query and it will satisfy the condition if the price of the node after applying the discounts is within the provided min and max price. 
> node's extra fee need to be taken into account

how to calculate the staking discounts
https://github.com/threefoldtech/tfgrid-sdk-go/blob/63bc34d8eb3a4d4e724c9a73ddce9cc60724e25b/grid-client/calculator/calculate.go#L53

**Comment by Omarabdul3ziz** [comment]
update (wip):
- added a generated field on the resources cache table that calculates the total_resources price for each node per month, then gets the tftPrice from the substrate client to decide the final price for the node.

**Comment by Omarabdul3ziz** [comment]
update (wip):
work has been paused here to work on more urgent issues and resumed today,
- added tests for the price filed
- fixed the price equations

**Comment by Omarabdul3ziz** [comment]
work is done and pr in review
