### ISSUE TITLE
Change tf-grid-cli to tfcmd

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/tfgrid-sdk-go#635]
# Request

Update tf-grid-cli to tfcmd, as per [ourworld.tf issue](https://git.ourworld.tf/threefold_coop/circle_prodmgmt_grid/issues/3)

# Solution

Update tf-grid-cli to tfcmd in the repository to call the cli with tfcmd.

**Comment by xmonader** [comment]
As names are always changing, please in the release pipeline make it the output binary named tfcmd (or generate multiple binaries tf-grid-cli and tfcmd) or change cmd/tf-grid-cli.go to cmd/tfcmd, but don't do any internal changes

**Comment by rawdaGastan** [comment]
## Verification

- now the latest release has `tfcmd` and `tf-grid-cli`

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/23ef8771-645b-4135-a3a3-8a7fd8b5b6d2)
