### ISSUE TITLE
add grid-proxy continuous deployment workflow

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/tfgrid-sdk-go#641]
### Is your feature request related to a problem? Please describe

it takes some effort to release/deploy gridproxy each time we need an update on devnet

### Describe the solution you'd like

- it will be easier if we have a workflow that deploys any merged changes to development on the proxy
- will be faster to address if there is any issue 
- I think we can't use `gridproxy.dev.grid.tf` because it is heavily used by the dashboard. but maybe a different stack like `gridproxy.bknd1.dev.ninja.tf`

**Comment by xmonader** [comment]
Don't think we should tbh reopen and let me know if you think otherwise
