### ISSUE TITLE
🐞 [Bug]: healthy nodes reports false on mainnet

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/tfgrid-sdk-go#644]
### What happened?

on `v0.13.12` deployed on ninja (mainnet) there is a lot of nodes that is up and responds to rmb calls but its `healthy` field is false.
checking: https://gridproxy.bknd1.ninja.tf/nodes?healthy=true&size=1000 last healthy node is 562

i think due to the large number of nodes on the mainnet 'about 6k', the health indexer workers couldn't catch up in the small interval '5 min'

### which network/s did you face the problem on?

Main

### Relevant log output

```console
none
```

**Comment by scottyeager** [comment]
Today I'm seeing only 22 mainnet nodes marked as healthy.

**Comment by Omarabdul3ziz** [comment]
i was debugging with @AbdelrahmanElawady 

debugging steps:
- tracing the code i found it is not only a problem on the health indexer but there is a problem on all the rmb calls from the proxy. checking the `/nodes/<id>/statistics` or `/nodes/<id>/gpu` endpoints times out for all nodes healthy/unhealthy.
- issue is not only on `bknd1.ninja.tf` stack but also `02.grid.tf` i suspected it maybe a broken connection to the relay or something but a restart gives the same state.
- we suspected it maybe related to an issue we had before for the same twin id trying to connect to different relay, but checked with ops and every stack is started with a different mnemonics.
- we tried to debug the container seeing the logs and the opened connection but things looks fine. actually there is a weird multiple connections on the `TIME_WAIT` state but it is with the process_db so it is not our problem. [here](https://gist.github.com/PeterNashaat/0c66b95c94c7b3640821073fe7d36450)
- first i tried to run the proxy locally on version `v0.14.11` the same one on broken stack with `tfchain.grid.tf` and `relay.grid.tf` and injected some dump data from mainnet nodes and both indexer and endpoints works fine.
- but when we checked the relay of the proxy twin id 11023 it uses the `relay.bknd1.ninja.tf` and when we changed the local server to the same relay it gives the same errors

conclusion:
- we tried to verify that we can't make connections between peers on different relays by running client/server locally and it is verified. only connections between two peers on the same relay succeed
- it is weird that there are 22 nodes are healthy knowing that they have relay `relay.grid.tf` which is different from the proxy. but i suspect it is an old data and somehow it didn't get invalidated.

notes
- also, not sure if it is related but the relay started to get an abnormal amount of requests at some time. check the monitor [here](https://mon.grid.tf/d/3YtJPrJVz/relay-stats?orgId=1&from=now-7d&to=now)

**Comment by xmonader** [comment]
Alright, raised to critical. All hands on this tmw for the release.

**Comment by Omarabdul3ziz** [comment]
considering the mentioned issue on the rmb-rs, we re-configured the ninja stack to use `relay.grid.tf` and it works fine now. direct rmb calls from `/statistics` and `/gpu` is working and health indexer returns 1626 node from `1720` up node which looks fine.

so we are good to upgrade main net.
