### ISSUE TITLE
🐞 [Bug]: FarmerbotGo, periodic_wakeup_limit warning error message when optional

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/tfgrid-sdk-go#649]
### What happened?

Running the farmerbot with no periodic_wakeup_limit set in config.yml, the following warning is displayed:

`3:43PM WRN The setting periodic_wake_up_limit should be greater then 0! setting it to 1`

The warning is in red and might confuse the farmer.

Maybe we could simply set it to 1 when it's not set (as it's optional) without displaying an error (warning) message. The exclamation mark after 0 makes it look like 0 factorial, which is 1.

Or:

`The setting periodic_wake_up_limit has not been set. Setting it to 1.`

### which network/s did you face the problem on?

Main

### Relevant log output

```console
3:43PM WRN The setting periodic_wake_up_limit should be greater then 0! setting it to 1
```

**Comment by rawdaGastan** [comment]
Updated with the latest version:

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/33ff7938-7252-4acc-bb82-c457d0948cf2)
