### ISSUE TITLE
🐞 [Bug]: Farmerbot Go, failed to read message

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/tfgrid-sdk-go#650]
### What happened?

When running the farmerbot go on a full vm (playground, ubuntu 22.04 and wireguard), with .env and config.yml files set, I get this message error:

`3:44PM ERR failed to read message error="read tcp 10.20.4.2:47130->185.206.122.83:443: use of closed network connection"`

`3:59PM ERR failed to read message error="read tcp 10.20.4.2:58268->185.206.122.83:443: use of closed network connection"`

It might be worth investigating, or not.

### which network/s did you face the problem on?

Main

### Relevant log output

```console
3:44PM ERR failed to read message error="read tcp 10.20.4.2:47130->185.206.122.83:443: use of closed network connection"
```

**Comment by scottyeager** [comment]
I see a lot of the same error message when running farmerbot. Seems to happen basically every five minutes when the farmerbot does it's cycle and attempts to connect to the relay.

**Comment by coesensbert** [comment]
Seeing the same on mainnet farmerbot v0.13.14
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/88312671/73bd2452-ebba-462b-8b91-995067cb6d72)
