### ISSUE TITLE
🐞 [Bug]: Farmerbot Go, failed to update node

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/tfgrid-sdk-go#651]
### What happened?

When running the farmerbot go on a full vm (playground, ubuntu 22.04 and wireguard), with .env and config.yml files set, I get this message error:

`3:53PM ERR error="failed to update node 879 with error: failed to get node 879 statistics from rmb with error: context deadline exceeded"`

It might be worth investigating, or not.

### Relevant log output

```console
3:53PM ERR error="failed to update node 879 with error: failed to get node 879 statistics from rmb with error: context deadline exceeded"
```

### which network/s did you face the problem on?

Main

### Note

I get the same error message for all 5 nodes set in the farmerbot (the other 6th node is set to never shut down).

**Comment by scottyeager** [comment]
I see the same thing. It seems like the farmerbot is attempting to retrieve stats via RMB for nodes that are asleep.
