### ISSUE TITLE
🐞 [Bug]: RMB Peer generates different pub key than mainnet playground

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-go#661]
I noticed while testing the new farmerbot that the RMB peer spawned by the bot was updating my key/relay at the start of the session. This seemed odd because I use this twin regularly for creating deployments.

Upon further testing, I noticed that the public key generated by the Go SDK's peer is different than the public key used both by the Playground and the `rmb-rs` peer. That is to say, switching between use of farmerbot and either of the other implementations will change my public key on chain.

### Network
mainnet
### Twin id
18
### Steps to reproduce:

1. Start farmerbot (or otherwise spawn a Go SDK peer) and check public key stored in TF Chain as reported by GraphQL:
```
"publicKey": "0x0257ca53143a98bf3879046c4b24d0c97e94a4ca009ba1205c5113798de511ea22"
```

2. Using the same twin, do some operation in Playground requiring RMB or fire up `rmb-peer` from `rmb-rs`. Check public key again:

```
"publicKey": "0x021ce6e445881c336be8015a1cc20a14cc02bf832d6d6b48652f32251c6febb5d7"
```

Changed!

### Final note

It appears that RMB communication is successful, as long as the public key planted by farmerbot remains on TF Chain. So I'd guess that the issue is in how the private key is being derived from the seed, rather than how the public key is derived from the private one.

**Comment by muhamadazmy** [comment]
Have you tried using the latest rmb-peer from this version https://github.com/threefoldtech/rmb-rs/releases/tag/v1.2.0

**Comment by muhamadazmy** [comment]
There was definitely a difference between how the TS client and the rmb-peer does it. Maybe the Go client is also still off. If that is the case, the Go client need to be updates as well to follow the same standard

**Comment by rawdaGastan** [comment]
@muhamadazmy That's how it is implemented in rmb-go
https://github.com/threefoldtech/tfgrid-sdk-go/blob/development/rmb-sdk-go/peer/peer.go#L46-L54

**Comment by muhamadazmy** [comment]
Can you compare and test that both implementation produce a compatible keys. The rmb-peer implementation is here https://github.com/threefoldtech/rmb-rs/blob/main/src/peer/e2e/mod.rs#L32

**Comment by muhamadazmy** [comment]
It might be that @scottyeager still using an older version of the rmb-peer that causes a problem

**Comment by scottyeager** [comment]
Thanks for the tip @muhamadazmy. Looks like the issue is indeed with both older versions of sdk-ts and rmb-peer.

I compared the following and they all produce the same keys:
* Devnet dashboard
* rmb-peer 1.2.0
* Dev branch of sdk-go

The remaining issue then is that mainnet playground is on a version of sdk-ts that produces the incompatible keys. So if a user starts up their farmerbot and then tries to use the playground with the same twin, farmerbot RMB will start to fail.

We can try to tell users not to do that, but I think it would be nicer if we can either:

1. Patch mainnet playground to play nice with the other implementations
2. Catch the error here on invalid cipher data and update the key on chain (this could interfere with the user's attempt to make a deployment in the playground if the timing is bad, but I think most would prefer reliable operation of farmerbot)

Thoughts @xmonader?

**Comment by xmonader** [comment]
@scottyeager what do you need the rmb-peer for? I think I got distracted, this project shouldn't depend on rmb-peer unlike the previous version


For the current mainnet: did you try this https://dashboard.bknd1.ninja.tf/ ?

**Comment by scottyeager** [comment]
@xmonader, I use rmb-peer for a variety of things, but it's indeed true that this farmerbot doesn't depend on it. I just checked its behavior for comparison, since I figured it was the reference implementation.

For playground I only checked play.grid.tf

**Comment by rawdaGastan** [comment]
I checked `go-rmb`, `ts-rmb` and `rs-rmb` and all generated the same public key if mnemonic or seed is used

**Comment by scottyeager** [comment]
Thanks @rawdaGastan. Good to know all the latest implementations are consistent.

We've seen some users encountering the conflict between keys generated by Farmerbot and play.grid.tf. I'd say this is moderately serious, because it cripples RMB comms for the bot in a way that's not automatically recovered.

I see three courses of action:
1. Just continue advising users to avoid using play.grid.tf with the same twin used with Farmerbot
2. Patch play.grid.tf to generate consistent public keys
3. Catch the cipher error here in sdk-go, check if the public key on chain has diverged from expected, and reset it if needed (maybe a bad idea because it can generate too many on chain transactions)

**Comment by scottyeager** [comment]
@xmonader, what do you think about this? We're noticing this happens quite often when farmers start using the bot. I think even just logging into the dashboard (dashboard.grid.tf) is enough to overwrite the public key with one that doesn't work with farmerbot.

**Comment by rawdaGastan** [comment]
Already solved
