### ISSUE TITLE
🐞 [Bug]: Farmerbot, Timezone UTC not local

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/tfgrid-sdk-go#662]
### What happened?

The readme of farmerbot says:

`⚠️ Be careful: The timezone of the farmerbot will be the same as the time zone of the machine the farmerbot running inside.`

But on my side, I set the wakeup of the nodes at 1pm and it starts at 8am. So the time is 1pm UTC = 8am EST. This works as EST = UTC - 5.

We could write: 

`⚠️ Be careful: The timezone of the farmerbot is in UTC.`

Or we really make the farmerbot in the timezone of the machine the farmerbot is running inside.

**Comment by rawdaGastan** [comment]
Can you provide more logs from your machine?

**Comment by mik-tf** [comment]
Of course! Here it is.

[fbotgologs.log](https://github.com/threefoldtech/tfgrid-sdk-go/files/14026996/fbotgologs.log)


Let me know if you need anything else! Thanks.

**Comment by xmonader** [comment]
can you please do `datetimectl`,  code checks shows it's using datetime local to the machine

**Comment by mik-tf** [comment]
I am deploying on a full VM on the farm itself, node 3860. Here's the output:

```
root@fbotgo:~# timedatectl
               Local time: Tue 2024-01-23 19:17:53 UTC
           Universal time: Tue 2024-01-23 19:17:53 UTC
                 RTC time: n/a
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

You are right the node is set to UTC. It seems playground full vm node gets the UTC timedate, or at least in this case. We can close the issue I think. I thought the node would get the local time zone.
