### ISSUE TITLE
🐞 [Bug]: integration tests workflow fails

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/tfgrid-sdk-go#666]
### What happened?

ssh connections test fails during integration tests

### which network/s did you face the problem on?

Dev, QA, Test, Main

### Relevant log output

```console
Received unexpected error:
dial tcp [301:5073:1e9b:46a5:667b:f6da:816d:27bb]:9900: i/o timeout
```

**Comment by xmonader** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/64129/417723e7-006c-47c3-9deb-11360d7b7079)

Tests are passing on all networks except for testnet
