### ISSUE TITLE
Set WG ports as part of the client state

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-go#675]
## Description

When deploying a batch of networks some networks assign the same WG port because they query the node for free ports, assign a random one and then wait until all networks do the same thing. Since it is not recorded anywhere which ports are used before deploying, sometimes multiple networks use the same ports.

**Comment by Eslam-Nawara** [comment]
Verified: 
tried deploying batch of 20 networks all with wg access and now all networks get deployed with different wg ports
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/80bda84e-27c7-411b-9fbb-c798648cce81)
