### ISSUE TITLE
Optimize deploying networks

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-go#676]
## Description

Deploying a batch of networks takes a lot of unnecessary time due to the fact that a lot of calls that should be concurrent are done sequential. For example: deploying 1000 network on devnet took around 8 mins with 6 of them in generating the deployment struct while only around a minute in creating contracts and deploying on nodes. the 6 minutes happen because calls to the nodes are done sequentially and there are multiple calls repeated for no reason (wg ports for example) and all that is done for each network also sequentially.

There are a lot of optimization that could be done here for example:

- a thread safe state to allow concurrent writes to it.
- concurrent preprocessing for each network.
- removing unnecessary calls to the nodes.

**Comment by rawdaGastan** [comment]
## Verification

- tried to deploy 50 vms using tfrobot and it succeeded
```
4:02PM INF Deployment took 1m15.054844303s
```
