### ISSUE TITLE
Improve network wg port assignment

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-go#680]
## Description

Currently the grid-client assigns wireguard ports randomly to the networks from the range 2000 to 7999 leaving a lot of ports unused and increases the possibility of collision with other networks being deployed.
The range should be from 1024 to 32767 leaving privileged ports (0 to 1023) and ephemeral ports according to zos kernel (32768 to 60999).

```console
$ sysctl net.ipv4.ip_local_port_range
net.ipv4.ip_local_port_range = 32768  60999
```

**Comment by Eslam-Nawara** [comment]
Discussed the issue with @AhmedHanafy725, and we agreed to leave the handling of the display of the output of the `iperf` tests to the client side and the test will still return the same output.

We also discussed if a public node testing the speed of itself would return a non-reasonable result, so I'm currently investigating that

While investigation, I noticed that the pref test on all `mainnet` nodes returns zero values for all fields with errors 
- node_id: 1
- twin_id: 7

- `error:unable to connect to server - server may have stopped running or use a different port, firewall issue, etc.: Operation timed out`
- `error:unable to connect to server - server may have stopped running or use a different port, firewall issue, etc.: Connection refused `
