### ISSUE TITLE
mass-deployer: continuation

### ISSUE THREAD

**Issue by Eslam-Nawara** [threefoldtech/tfgrid-sdk-go#683]
Add improvements and fix reported issues of the mass deployer

- [x] #690 
- [x] #688 
- [x] #689 
- [x] #687 
- [x] #686 
- [x] #684 
- [x] #685 
- [x] #694
- [x] #697
- [x] #700 
- [x] #715

**Comment by Eslam-Nawara** [comment]
Allow users to configure retries

https://github.com/threefoldtech/tfgrid-sdk-go/pull/527#discussion_r1469727327

**Comment by Eslam-Nawara** [comment]
Add mass deployer to sdk readme packages

**Comment by xmonader** [comment]
convert to a checklist in the body of the issue instead of using comments for sub issues please
