### ISSUE TITLE
node group vm free mru checks

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#687]
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/64129/b555ef9a-ea76-4973-8a8c-547b80e4686c)

it should have failed and reported the error from the beginning

**Comment by Eslam-Nawara** [comment]
can you specify what is the error
if the problem is in free mru the limit is 262144 which is more than 200048, so it's safe, but we need to add limits to the node group values

**Comment by xmonader** [comment]
validated in https://github.com/threefoldtech/tfgrid-sdk-go/issues/710#issuecomment-1921749327
