### ISSUE TITLE
mass-deployer: Allow users to configure retries

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#689]
Allow users to configure retries

https://github.com/threefoldtech/tfgrid-sdk-go/pull/527#discussion_r1469727327

_Originally posted by @Eslam-Nawara in https://github.com/threefoldtech/tfgrid-sdk-go/issues/683#issuecomment-1915037177_

**Comment by Eslam-Nawara** [comment]
Verified:
- tried to deploy a node group with `max_retries: 1`
- now when the deployment fails, it retries to run the deployer only once 
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/783e481a-75f0-4180-9424-07854fefbd5e)
