### ISSUE TITLE
Cancel projects in grid-client with batch

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-go#696]
## Description

Instead of canceling project contracts one by one we can batch cancel all contracts at once.

**Comment by Eslam-Nawara** [comment]
Verified: 
- cancel command, cancel all deployments of a project in batch
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/c4ecdabe-53e6-49b3-94c0-25d58befeaf8)

**Comment by rawdaGastan** [comment]
Cancel projects in `grid-client` using batch is used in the cancel command of the `grid-cli`. That's why we verified using it.
