### ISSUE TITLE
Add more  documentation to the mass deployer

### ISSUE THREAD

**Issue by Eslam-Nawara** [threefoldtech/tfgrid-sdk-go#697]
### Is your feature request related to a problem? Please describe

deployer commands and flags are not documented in the readme file

### Describe the solution you'd like

Add documentation to the commands and flags of mass deployer

**Comment by timurgordon** [comment]
Can we also document how to pass env variables (if supported) to configuration?

**Comment by Eslam-Nawara** [comment]
@timurgordon it's not supported now, will be added soon

**Comment by Eslam-Nawara** [comment]
### Work Completed
added usage docs

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/f6a6b120-d4f6-44ac-bff8-a857ce708241)

**Comment by A-Harby** [comment]
Verified,
Add env var with examples.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/647feee1-f53f-4d36-8e56-548721c3e6f9)
And subcommands with flags
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/6bc564ce-91f7-49c3-b586-01195d2317db)
