### ISSUE TITLE
Dedicated Node 1967 with GPU: is not showing  GPU availability and specs.

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/tfgrid-sdk-go#713]
The dedicated Node 1967 is not showing the same GPU results across the old dashboard and new.
 
![image](https://github.com/threefoldtech/test_feedback/assets/105203696/96d14653-4e11-41c7-ac50-8039b53439a7)

![image](https://github.com/threefoldtech/test_feedback/assets/105203696/ec85ae3d-4056-491b-8649-a520425ddf20)

![image](https://github.com/threefoldtech/test_feedback/assets/105203696/a568b1f5-d161-4f6e-97a2-502a232cc4e3)

![image](https://github.com/threefoldtech/test_feedback/assets/105203696/c2cfd8b3-a147-40e6-8515-bb265c295c8d)

**Comment by ramezsaeed** [comment]
Fixed on Ninja Domain.
https://dashboard.bknd1.ninja.tf/#/
