### ISSUE TITLE
Change mass deployer clean up strategy 

### ISSUE THREAD

**Issue by Eslam-Nawara** [threefoldtech/tfgrid-sdk-go#715]
### Is your feature request related to a problem? Please describe

Mass deployer clean up strategy is to remove all deployments of the failed group and rerun the deployer for that group (reported [here](https://github.com/threefoldtech/tfgrid-sdk-go/pull/527#discussion_r1469764638))

### Describe the solution you'd like

A [suggestion](https://github.com/threefoldtech/tfgrid-sdk-go/pull/527#discussion_r1469777337) is to update the deployer to rerun only the failed deployments

**Comment by Eslam-Nawara** [comment]
WIP: 
- updated the retry strategy to only redeploy failed deployments.

- tried to use `ListContractsOfProjectName` to load deployed contracts from grid instead of keeping state of the deployments, but it doesn't list the contracts deployed just now for some reason, I would be required to wait for some time before I call it, not sure what the expected behavior is.

- sometimes the created contracts can't be loaded from state at all, with both methods of listing contracts, not sure what is the cause of it

the deployments exist on the playground with the same info

```console
5:30PM INF couldn't load from state error="failed to find deployment  on node 100: not found" deployment=examplevm4 node ID=100 vm=examplevm4
5:30PM INF couldn't load from state error="failed to find deployment  on node 150: not found" deployment=examplevm1 node ID=150 vm=examplevm1
5:30PM INF couldn't load from state error="failed to find deployment  on node 153: not found" deployment=examplevm3 node ID=153 vm=examplevm3
5:30PM INF couldn't load from state error="failed to find deployment  on node 146: not found" deployment=examplevm0 node ID=146 vm=examplevm0
5:30PM INF couldn't load from state error="failed to find deployment  on node 152: not found" deployment=examplevm2 node ID=152 vm=examplevm2
```

**Comment by Eslam-Nawara** [comment]
### Blocked:
- continued working on updating the redeployment strategy
- fixed the `couldn't load from state` problem
- tested the new strategy and it works as expected

No we need to fix the `DeploymentDeployer.BatchDeploy` function as it suppose to be not atomic, but it still all deployments fails to deploy any deployment if one of the used networks failed, which is not the expected behavior reported in:
- #765

**Comment by rawdaGastan** [comment]
Tried to deploy 100 VMs and some of them failed then the only failed deployments got deployed again and it worked
