### ISSUE TITLE
🐞 [Bug]: TFRobot Docs improvement

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#717]
### What happened?

https://github.com/threefoldtech/tfgrid-sdk-go/tree/development/mass-deployer

- The example is outdated.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/ae9ad53f-b9f1-469f-a5dd-88da322decfd)
e.g., free_mru is in GB, not MB.

- Can we also specify the config file extension `YML` in the fourth step? `Create a new configuration file. For example:`.

- it's either a certified or DIY can't be certified of DIY (DIY not diyed, so user can get it).
- Regions are not the same as the dashboard; for example, the Americas is not split into northern and southern regions, and there are a lot more regions than in the dashboard.
- max = 256; bool value: can you add true or false; and does the positive value include zeros?
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/d9f6ef80-a822-441f-b55b-7126170d5915)

- Is there a flag option for debugging? and if there's any other flag, it must be included.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/75d0f4ff-c664-43e6-876a-d67f17c96e04)

Everything is also applied to https://github.com/threefoldtech/tfgrid-sdk-go/blob/development/mass-deployer/example/conf.yaml.

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
.
```

**Comment by Eslam-Nawara** [comment]
- Regions had some changes lately and were changed from proxy to be the continents names, the values in the docs some of them may not have nodes currently, but they are supported regions

**Comment by A-Harby** [comment]
Verified, https://github.com/threefoldtech/tfgrid-sdk-go/blob/development/mass-deployer/README.md.

The config file example has been updated, as have the description points, and a debug and help command has been added.
Also, some notes were added, and regions were updated to the latest (Africa, Americas, Antarctic, Antarctic Ocean, Asia, Europe, Oceania, Polar).

[TC2489 - Documentations](https://app.testlodge.com/a/26076/projects/40893/suites/236972?expand_section=427885#case_4193612)
