### ISSUE TITLE
TFRobot: Add any indication that bot is working

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#720]
### Is your feature request related to a problem? Please describe

I waited for more than 3 minutes and didn't know if the bot was working or what was happening.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/76b325da-bf03-4a30-a5ff-62886650bf3a)

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/8b780b97-8f3d-4a69-9cc5-48a5e7e156cc)

### Describe the solution you'd like

Maybe we should add a loading status or print some logs for the user to keep him updated with what is happening.

Or, if not possible, at least tell him that this may take a few minutes.

**Comment by Eslam-Nawara** [comment]
More info would be displayed using the debug flag, the message `Running deployment Node group=group_a` is indicating that the deployer is running, I think it's informing that the deployment is running

**Comment by A-Harby** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/a1938ce2-e887-488a-8aa9-b97654308ef7)
