### ISSUE TITLE
TFRobot: Add an command option `help`

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#722]
### Is your feature request related to a problem? Please describe

It would be better if we also added the help option to print some help information, the deploy/cancel options, and the flags.

### Describe the solution you'd like

The help option is always found on any cli bot, and it is even better to let the user know if the bot is working or not (like ping).

**Comment by rawdaGastan** [comment]
@A-Harby It exists if you tried `-h` or `--help`

- cancel example

```
cancel all deployments of configuration file

Usage:
  tfrobot cancel [flags]

Flags:
  -c, --config string   path to config file
  -h, --help            help for cancel

Global Flags:
  -d, --debug   allow debug logs
```

**Comment by A-Harby** [comment]
@rawdaGastan Can we add to the docs.

**Comment by rawdaGastan** [comment]
Added:

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/47260239/33a33936-b620-4d5f-8f89-bc14d1c00d65)

**Comment by A-Harby** [comment]
[TC2524 - Run help command](https://app.testlodge.com/a/26076/projects/40893/suites/236972?expand_section=427886#case_4201405)
