### ISSUE TITLE
🐞 [Bug] TFRobot: Add more details in the output file

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#724]
### What happened?

The output file should have all the VM details, like the JSON from the dashboard or tsclient.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/36c47fae-8f07-4cd8-8e3a-4659767d6d70)

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
tfrobot deploy -c config.yml -o output.yml
```

**Comment by xmonader** [comment]
While that's understandable, the output data was defined in the story https://github.com/threefoldtech/home/issues/1504
