### ISSUE TITLE
🐞 [Bug] TFRobot: Better error message for wrong config file content

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#730]
### What happened?

Update the message error to make it easily understandable to the user. Here the error was the wrong file content, but the error message wasn't really helpful.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/2f0e37d5-8ac9-4efe-8d7b-f737c7e564dc)

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
.
```

**Comment by A-Harby** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/ada37f44-6e44-4187-86c3-b403810da8b6)
I just added a line anywhere:
```
  "network": "dev",
  "max_retries": 5,
  "test: 'gi',
}
```
Or a duplicate:
```
  "network": "dev",
  "network": "qa",
```

**Comment by xmonader** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/64129/f054710f-5d17-4888-849c-8d079a93d262)


Now it shows the failed parts

**Comment by A-Harby** [comment]
The duplicate line is still not validated anymore; two networks are on the same config file.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/66a11bf9-fe05-47af-834d-de3460650f2a)

**Comment by Eslam-Nawara** [comment]
@A-Harby Any duplicated field, the parser will skip the fields and parse only the last one, will add note about that in the docs

**Comment by Eslam-Nawara** [comment]
Validation:
added note about duplicated fields in the docs
https://github.com/threefoldtech/tfgrid-sdk-go/pull/793/files#diff-a5a1edde2d3d22afef0bef78335fa43d6b78bf30c0b11899fc908e8ee1f63427R72
