### ISSUE TITLE
🐞 [Bug] TFRobot: Config file extension validation 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#731]
### What happened?

File parsing accepts any file extension not mentioned in the documents.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/9c84aa46-73b3-4791-bcb1-c1cf8fe7bbf2)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/0bd690e2-07f5-4541-b52b-129423473946)

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
.
```

**Comment by rawdaGastan** [comment]
I can't generate this error after trying:

```
Error: unsupported configuration file format 'conf.txt', should be [yaml, yml, json]
Usage:
  tfrobot cancel [flags]

Flags:
  -c, --config string   path to config file
  -d, --debug           allow debug logs
  -h, --help            help for cancel

1:48PM FTL error="unsupported configuration file format 'conf.txt', should be [yaml, yml, json]"
exit status 1
```

**Comment by A-Harby** [comment]
I was using the latest release, but for most of the new fixes, it's not yet released, and I will start testing on the dev branch instead.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/d1f2d4ff-38b0-4cf7-a6bb-8bffe2cecfdb)

**Comment by A-Harby** [comment]
[TC2493 - Config File extension Validation](https://app.testlodge.com/a/26076/projects/40893/suites/236972?expand_section=427888#case_4194102)
