### ISSUE TITLE
🐞 [Bug] TFRobot: Node group name validation 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#733]
### What happened?

As I get from the documents, there's no construction on the node group name except for the unique name.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/d4d34075-cd0e-4cfe-9e99-a32920f54004)
But when I tried to do a duplicate name, it allowed me to do it with no validation or error message.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/3eefb9f1-5343-4888-b0ea-e7bcf7c874fc)

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
,
    {
      "name": "group_c",
      "nodes_count": 3,
      "free_cpu": 2,
      "free_mru": 10,
      "free_ssd": 10,
      "free_hdd": 50
    },
    {
      "name": "group_c",
      "nodes_count": 3,
      "free_cpu": 2,
      "free_mru": 10,
      "free_ssd": 10,
      "free_hdd": 50
    }
```

**Comment by rawdaGastan** [comment]
Validations are done (alphanumeric and underscores)

**Comment by A-Harby** [comment]
Verified,

Validation is updated to lowercase alphanumeric and underscore only, and unique group name.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/628c1147-d400-4e81-8e59-d70550e22949)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/538bf68a-d7b9-4cfc-b66e-0d6fd45930ea)

[TC2495 - Node Group name](https://app.testlodge.com/a/26076/projects/40893/suites/236972?expand_section=427888#case_4194108)
