### ISSUE TITLE
🐞 [Bug] TFRobot: Validation works on the JSON files but not on the YML files

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#734]
### What happened?

There isn't any kind of validation in the YML config file, e.g. nodes count, CPU, etc.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/29389fb6-78ef-4112-afd4-cd664157515e)
In the same case, I tried it on the JSON file, and it validated my input correctly.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/eed295a6-cfb8-4f3b-bacc-b14cdee90c2a)

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
node_groups:
  - name: group_a
    nodes_count: 3.1
    free_cpu: 2
    free_mru: 10
    free_ssd: 10
    free_hdd: 50
  - name: group_b
    nodes_count: 30.1
    free_cpu: 2.1
    free_mru: 10
    free_ssd: 10
    free_hdd: 50
```

**Comment by Eslam-Nawara** [comment]
yaml parse float to int without reporting error, it rounds the float input to integer value and drop the fractional part, the json format is more restricted so it reports these kinds of errors.

Is there other validation that doesn't work in yaml other than float problem?

**Comment by Eslam-Nawara** [comment]
It's a known issue that parsing YAML with a floating point value for an integer input does not report an error. Instead, it disregards the fraction and returns only the integer part.

**Comment by A-Harby** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/d8a88aaa-6fe8-4aa4-9dc2-f7347b1e8880)
