### ISSUE TITLE
🐞 [Bug] TFRobot: maximum CPU limit on vms 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#738]
### What happened?

Is it 1 to 4 or to 32?

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/ced84a6c-7983-40bd-a1d7-296e3171f13a)

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
"vms": [
    {
      "name": "examplevm13",
      "vms_count": 3,
      "node_group": "[:]",
      "cpu": 32,
      "mem": 1,
      "flist": "https://hub.grid.tf/tf-official-apps/base:latest.flist",
      "entry_point": "/sbin/zinit init",
      "root_size": 0,
      "ssh_key": "example1",
      "env_vars": {
        "user": "user1",
        "pwd": "1234"
      }
    }
  ],
```

**Comment by rawdaGastan** [comment]
please provide the node group too, and pull the latest changes :D

**Comment by xmonader** [comment]
https://github.com/threefoldtech/tfgrid-sdk-go/issues/710#issuecomment-1921749327 please check the validation is working with max of 32

**Comment by A-Harby** [comment]
After reviewing the config file and retesting a few times, it was found that the node group had less resources than the VMs needed.
Now it gives a good error message for such a case.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/f0e5e197-33a1-4ce4-bdc8-7d40916ee197)

[TC2517 - VMs with more resources than Node Group](https://app.testlodge.com/a/26076/projects/40893/suites/236972?expand_section=427886#case_4199125)
