### ISSUE TITLE
TFRobot: check on flists after parsing and before deployment

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#739]
I used this    `flist: https://hub.grid.tf/mariobassem1.3bot/threefolddev-holochain-latestaaa.flist`

which isn't valid (could have been caught by checking the url+.md5 which should have failed
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/64129/f57089ce-97bd-4792-b530-b8e851fb9a2f)

could also have a custom validator `flist` in the struct tags

**Comment by xmonader** [comment]
done in #750

**Comment by AbdelrahmanElawady** [comment]
Verified:

Tried deploying with invalid flist and it detected that successfully:
```text
5:28PM FTL error="failed to validate configuration file 'example/conf.yaml' with error: vms group 'examplevm' flist: 'https://hub.grid.tf/tf-official-apps/threefoldtefowiejfoch-ubuntu-22.04.flist' is invalid, failed to download flist"
```
