### ISSUE TITLE
🐞 [Bug] TFRobot: deploying 50 VMs keeps failing  

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#745]
### What happened?

I tried to deploy 50 VMs on the mainnet using the latest build from the development branch, but at first it failed, not giving me what was deployed and what was not.
So I ran the same file and command again and only added the debug option, and it deployed all of them successfully. So I tried again, and I got the same failure as before, but this time I was able to capture the logs.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/e0c1355d-7e6f-4c3d-a294-1eebf79d880d)

https://gist.github.com/A-Harby/693f73f8513cf5806ed5b69ccd54c8de

### which network/s did you face the problem on?

Main

### Relevant log output

```console
node_groups:
  - name: group_a
    nodes_count: 50
    free_cpu: 2
    free_mru: 16
    free_ssd: 100
    free_hdd: 50
    dedicated: false
    public_ip4: false
    public_ip6: false
    certified: false
    region: "europe"
vms:
  - name: examplevm
    vms_count: 50
    node_group: group_a
    cpu: 1
    mem: 2
    ssd:
      - size: 15
        mount_point: /mnt/ssd
    public_ip4: false
    public_ip6: false
    flist: https://hub.grid.tf/tf-official-apps/base:latest.flist
    entry_point: /sbin/zinit init
    root_size: 0
    ssh_key: example1
    env_vars:
      user: user1
      pwd: 1234

ssh_keys: 
  example1: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvmSYj5BKWkizdNyIziMfMm0CRrgq0UxFtBfBdArUMXSFkU30rtExbg6dlVFJCufw6UsCESm/QBSwlOyYKRdpsfVARcAw5G5OG0iX/22n+tYmCcWpmOJLJZaAmSynF1kwpBx3XDy40mFL6OMXjqFcU3DirbcucIL185XfAsTzrq3tDtSvmYPwbXMVMbs1ZAZValxOQNuaLty4qGD2awxVNZq4vtAzgpz3FFo3cs2g70jsGiPq/rsH+NxZHYmqvYnF/S0aPGBrbOe2yW8Cz0mqq5CzqbjYd+Qorkmt7uyJrlCBI43ky+pUuiAYeE1eJlWl5svA+ibWk5yYoa6svLUkaL1kcOMeZWLzDjL3OCrno9gglNp8zUkdSagHROoYlGgpc5fnzMGX4MKDLpHdE9xdk4NjpjB2Iq3hV3DamexXAhLEirLYv9fSilSyKVf/2kvYAa9o+NS4DgBVvXg9J54By/mAVsydD4lbpNe/2pX/WoFGCczmoQfWdHgJPYVCf2vU= harby@ahmed-Saleh-Harby"
mnemonic: "***"
network: main
max_retries: 5
```

**Comment by A-Harby** [comment]
Also to mention that the same file passed once, so it's not an issue from the config, and what I consider a more significant problem is that the error list is empty, but there should be a 50-deployment failure listed.

**Comment by A-Harby** [comment]
All the deployments were successful, but only when loading them did they fail. I was able to list them from the playground.
 
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/337c9fdf-dc5d-444c-a8d4-c0cb3c386d76)

Also, there should be a rollback to delete all the deployments if one of them fails.

**Comment by rawdaGastan** [comment]
Can you try if this is reproducible?

**Comment by A-Harby** [comment]
I'm trying to reproduce the issue and got this error: https://github.com/threefoldtech/tfgrid-sdk-go/issues/794.
I will keep trying and report it here once it happens again.

**Comment by A-Harby** [comment]
Verified, Dev branch.
Deployment were successful over multiple VMs in this issue [here](https://github.com/threefoldtech/tfgrid-sdk-go/issues/836).
