### ISSUE TITLE
🐞 [Bug] TFRobot: Can't deploy any vm with more than 1 SSD 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#746]
### What happened?

I tried to deploy a VM with more than 1 SSD, but I noticed that I couldn't assign names to them like other clients, so I kept going and added one more, like the documents mentioned, and I did get an error saying I couldn't add a disk with the same name.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/81ca7624-5bbf-45e5-ab67-f3739cbc3818)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/ad7ad888-0caf-49d3-97bb-a7e98ba943b8)

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
"vms": [
    {
      "name": "examplevm13",
      "vms_count": 1,
      "node_group": "test",
      "cpu": 3,
      "mem": 0.25,
      "flist": "https://hub.grid.tf/tf-official-apps/base:latest.flist",
      "entry_point": "/sbin/zinit init",
      "root_size": 0,
      "ssh_key": "example1",
      "ssd": [
        {
          "size": 15,
          "mount_point": "/mnt/ssd"
        },
        {
          "size": 25,
          "mount_point": "/mnt/ssd"
        }
      ],
      "env_vars": {
        "user": "user1",
        "pwd": "1234",
        "user": "user1",
        "test": "pass"
      }
    }
  ],
```

**Comment by rawdaGastan** [comment]
Needed unique names for the disks and it is fixed

**Comment by A-Harby** [comment]
Can you also update the docs
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/f2413657-55a7-4dc6-bbf4-5e3368932aaa)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/87f18af8-af6a-402f-9ff4-5e9afdca1611)

**Comment by A-Harby** [comment]
[TC2512 - Multiple SSD](https://app.testlodge.com/a/26076/projects/40893/suites/236972?expand_section=427888#case_4197046)
