### ISSUE TITLE
tfrobot: use ninja gridproxy for mainnet network

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#748]
when the user choose mainnet network override the proxy url to the ninja proxy (unless the user specifies `NO_NINJA_PROXY_URL`) in the TFPlugin initialization

**Comment by AbdelrahmanElawady** [comment]
Verified:

Using `tcpdump`, requests can be seen when filtering on ninja host:

```console
$ sudo tcpdump host gridproxy.bknd1.ninja.tf --count   
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on wlp0s20f3, link-type EN10MB (Ethernet), snapshot length 262144 bytes
23 packets captured
31 packets received by filter
0 packets dropped by kernel
```

When setting NO_NINJA_PROXY_URL=true:

```console
$ sudo tcpdump host gridproxy.bknd1.ninja.tf --count
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on wlp0s20f3, link-type EN10MB (Ethernet), snapshot length 262144 bytes
0 packets captured
4 packets received by filter
0 packets dropped by kernel
```
Notice packets captured in both cases.

> Note: filtering on `gridproxy.grid.tf` will result in packets being captured in both cases as relay uses the same IP so it results in tcp requests being captured even when not using `gridproxy.grid.tf`.

**Comment by xmonader** [comment]
@AbdelrahmanElawady excellent verification
