### ISSUE TITLE
grid-client 🐞 [Bug]: some network deployments sets contract id = 0 for some nodes

### ISSUE THREAD

**Issue by Eslam-Nawara** [threefoldtech/tfgrid-sdk-go#755]
### What happened?

Some network deployment fails with `failed to get deployment 0 from node **`
when this happens, the `network.NodeDeploymentID` would contain some node with 0 contract ID

### which network/s did you face the problem on?

Dev

**Comment by xmonader** [comment]
@AbdelrahmanElawady what is the cause of this? deleted network resources?

**Comment by AbdelrahmanElawady** [comment]
@xmonader the way we updated the network state after batch deployments didn't handle the case of failed deployments (which had the default value for contract ID: 0) so some failures caused the network to have 0 ids.

**Comment by Eslam-Nawara** [comment]
Verified: 
- A check is added to prevent failed deployments with zero value for contractID to be added to the state
