### ISSUE TITLE
TFRobot: missing requirements

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#756]
### What happened?

I can't find these options in the file config documents; this was mentioned on https://github.com/threefoldtech/home/issues/1504.

```
  #min nr of nodes in farm
  min_nodes_farm: 5
  #nr of nodes in same farm which apply the rules above
  min_nodes_apply_rules: 3
  #bandwidth which can be achieved, do we know this?
  min_bw: 100
```

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
.
```

**Comment by rawdaGastan** [comment]
we don't have those supported filters in the proxy

**Comment by xmonader** [comment]
can be closed
