### ISSUE TITLE
🐞 [Bug] TFRobot: Canceling command fails sometimes

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#757]
### What happened?

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/f966855c-e75f-4451-b4ac-fb8303618a0f)

Are there the same retries here as in the deployment?

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
.
```

**Comment by rawdaGastan** [comment]
Verified. Now it cancels all contracts even if the deployment has failed

**Comment by A-Harby** [comment]
[TC2529 - Cancellation isn't validating](https://app.testlodge.com/a/26076/projects/40893/suites/236972?expand_section=427886#case_4204756)
