### ISSUE TITLE
BatchDeploy failing on one bad deployment

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-go#765]
## Description

BatchDeploy for workloads does not proceed to deploying if 1 workload failed while processing all workloads. BatchDeploy should be non-atomic and try to deploy as much as possible.

**Comment by Eslam-Nawara** [comment]
Verified: 
- BatchDeploy now is non-atomic and always process all deployments and return with some succeeded and other failed deployments and error that indicates if there was a failure in some deployments.
- Failed deployments have a zero value for contractID
