### ISSUE TITLE
🐞 [Bug] TFRobot: Add minimum TFT balance valdition 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#768]
### What happened?

I just created an account, and with less than 0.1 TFT, I was able to deploy VMs. There should be a minimum of 2 TFT balance for the user to be able to deploy.
 
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/46e18d4f-a201-44a9-a86f-91adf3ee8300)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/c8716877-9524-4784-a72a-5bd79b3327cb)

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
.
```

**Comment by rawdaGastan** [comment]
`0.002` TFT is the minimum transaction fees, But okay we can put 2 TFTs as buffered fees

**Comment by Eslam-Nawara** [comment]
Work Completed
Balance is updated to be 2 tfts for deployment

**Comment by A-Harby** [comment]
Verified, Dev branch.

2 TFT min validation was added.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/0abd67d4-c94b-43cc-9a23-91cb340486c7)
