### ISSUE TITLE
Create Farmerbot testsuite on testlodge

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-go#787]
In order to test farmer bot; 
added the testsuite on testlodge: https://app.testlodge.com/a/26076/projects/40893/suites/221831

### solution

regarding to the refactor done on Farmer bot, we need to update the current testsuite and run all the needed tests.

- https://github.com/threefoldtech/tfgrid-sdk-go/issues/484

**Comment by A-Harby** [comment]
WIP:
- Updating the section of the bot from the farmer side and still working on updating it as I keep testing it: https://app.testlodge.com/a/26076/projects/40893/suites/221831?expand_section=382401#suite_section_382401.
- Created an issue for the document messing information: https://github.com/threefoldtech/tfgrid-sdk-go/issues/812.
- Reported two issue: https://github.com/threefoldtech/tfgrid-sdk-go/issues/811 and https://github.com/threefoldtech/tfgrid-sdk-go/issues/653.

**Comment by A-Harby** [comment]
WIP:
- https://github.com/threefoldtech/tfgrid-sdk-go/issues/821
- https://github.com/threefoldtech/tfgrid-sdk-go/issues/822
- https://github.com/threefoldtech/tfgrid-sdk-go/issues/823

**Comment by A-Harby** [comment]
- https://github.com/threefoldtech/tfgrid-sdk-go/issues/830
- https://github.com/threefoldtech/tfgrid-sdk-go/issues/831
- https://github.com/threefoldtech/tfgrid-sdk-go/issues/832

**Comment by A-Harby** [comment]
The test suite is done and should be covering all the cases: https://app.testlodge.com/a/26076/projects/40893/suites/221831.
I will also keep updating it when issues created are closed.

**Comment by xmonader** [comment]
Awesome. can close now
