### ISSUE TITLE
🐞 [Bug] TFrobot: HDD filter isn't used in the VMs depolyments

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#791]
### What happened?

I tried to find a way to add HDD to VMs, but I couldn't, and I didn't find any reason for adding it in the filters as root disks and extra disks are using SSDs.

I confirmed with @rawdaGastan that HDD is used only in ZDB, which isn't used here.

So @xmonader, should we get rid of it, or at least change the validation to accept a zero value as most of the nodes on the grid don't have HDDs?

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
.
```

**Comment by Eslam-Nawara** [comment]
@A-Harby the validation already accepts a zero value for both FreeSRU and FreeHRU filter

**Comment by xmonader** [comment]
I believe it will grow in features to support zdbs. I will close.
