### ISSUE TITLE
🐞 [Bug] TFRobot: improve error messages list 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#794]
### What happened?

Error list messages need improvement for the user to be able to easily read them.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/170bbdd0-6fe0-47ac-bd8f-15936823beaa)
The message looks like this, and it even keeps going farther down, looking much worse.

Also, I deployed 250 VMs, and it shows me only 120 errors, so what happened to the other 130 VMs? Were they deployed but didn't show up, or were all of them cancelled because some of them failed?

### which network/s did you face the problem on?

Dev, Main

### Relevant log output

```console
"vms": [
    {
      "name": "examplevm1",
      "vms_count": 250,
      "node_group": "test1",
      "cpu": 1,
      "mem": 1,
      "flist": "https://hub.grid.tf/tf-official-apps/base:latest.flist",
      "entry_point": "/sbin/zinit init",
      "root_size": 0,
      "public_ip4": false,
      "public_ip6": false,
      "ssh_key": "harby",
      "env_vars": {
        "user": "user1",
        "pwd": "1234",
        "user": "user2",
        "test": "pass"
      }
    }
  ],
```

**Comment by Eslam-Nawara** [comment]
The deployments that succeeded were destroyed after all retries were compleated and not all the other deployment were created, the logs show that they're being canceled.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/5145cbfe-4be2-468b-b759-edb7283328ba)

**Comment by Eslam-Nawara** [comment]
for the error messages, the yaml error are formatted here
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/30081b7a-0cfb-44b5-b203-122c139ee30e)

json format is not meant to be human-readable for multiline strnigs, it's used to be processed further, so it can't be improved
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/aaba1911-2d5b-4873-ae4e-b9457cff9b74)
