### ISSUE TITLE
🐞 [Bug]: Farmerbot wake up threshold works on simple sum of all resource types

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-go#804]
### What happened?

The Farmerbot is currently calculating the resources used in the farm like this:

https://github.com/threefoldtech/tfgrid-sdk-go/blob/3bc870947dc8d0b4ff4f2687d65543928aac366f/farmerbot/internal/power.go#L140

This approach doesn't work:

* Summing together vCPU counts (CRU) and byte counts of RAM/disk (MRU/SRU/HRU) just doesn't make sense
* Nodes can have all their RAM reserved, or have their CPU heavily oversubscribed and never reach threshold

I suggest something like this:

* Evaluate threshold on CRU/MRU/SRU individually (wake another node if any one of these quantities exceeds the threshold percentage individually)
* Just ignore HRU for now (doing this right would involve adding some logic around whether there's a node available to wake up that has HRUs. Since basically nobody is reserving HDD on the grid today, we can figure it out later)

**Comment by A-Harby** [comment]
Verified, Devnet.

Docs were updated.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/60d338e9-aa44-456a-9ce1-857b7f0d383a)

And I also tried it, and it worked as expected.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/0e80df94-7f42-4b03-89d0-c225a4a8907f)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/a42111ad-c9ff-43b1-abab-6aad933e8d8b)

[TC2468 - Farmer Bot Installation with power wake_up_threshold](https://app.testlodge.com/a/26076/projects/40893/suites/221831?expand_section=382401#case_4187430)
