### ISSUE TITLE
🐞 [Bug] TFRobot: Node groups name conflict

### ISSUE THREAD

**Issue by Eslam-Nawara** [threefoldtech/tfgrid-sdk-go#805]
### What happened?

When running the deployer multiple times with the same node group names, if the first deployment passed and the following deployment failed, while cancelation the deployer delete both the deployments of the first and the second deployments as both has the same node group name.

### which network/s did you face the problem on?

Main

### Relevant log output

```console
--
```

**Comment by A-Harby** [comment]
Verified, Dev branch.

[TC2624 - Deploying 2 VMs group with same node group](https://app.testlodge.com/a/26076/projects/40893/suites/236972?expand_section=427886#case_4220274)

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/cd8b0e8b-e28b-49ef-81f4-7fd0d0787d1d)
