### ISSUE TITLE
🐞 [Bug] Farmerbot: failed to start even when the node is up 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#811]
### What happened?

Farmerbot version, v0.14.1.

I configured the yml config file and.env, and after running the bot, I got this error: `FTL error="failed to add node with id 155 with error: failed to get node 155 statistics from rmb with error: context deadline exceeded"` and I checked the node on the dashboard; it was online and responding.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/6fe7dc46-f08d-4ce3-bfc6-ffb404a569ab)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/3c8c1c06-b411-41ba-b3a6-70663c3b3144)

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
farm_id: 4420
included_nodes:
- 155
- 156
excluded_nodes:
- 148
- 149
never_shutdown_nodes:
- 155
- 156
power:
  periodic_wake_up_start: "00:00AM"
  wake_up_threshold: 80
  periodic_wake_up_limit: 1
  overprovision_cpu: 1
```

**Comment by xmonader** [comment]
Also, please attach the farmerbot version.

I noticed you have `included_nodes` has 155 and `never_shutdown` has 155 too as well, not sure if that causing the issue (i think it's normal too)

**Comment by A-Harby** [comment]
> Also, please attach the farmerbot version.
> 
> I noticed you have `included_nodes` has 155 and `never_shutdown` has 155 too as well, not sure if that causing the issue (i think it's normal too)

I updated the issue with the new version, and I also tried a few times again, and farmerbot worked successfully without giving me that error.
So I'm not sure what was wrong, but the websocket error kept showing up in all of them.
