### ISSUE TITLE
🐞 [Bug] Farmerbot: confused about help and completion subcommands

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#812]
### What happened?

The help option in the bot has more command descriptions than in the documents.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/88ab3a1b-ecdc-41a3-b3dc-a99844df84d1)

I can't find any information about commands, including help itself. What does the completion command do?

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
https://github.com/threefoldtech/tfgrid-sdk-go/blob/development/farmerbot/README.md
```

**Comment by xmonader** [comment]
I understand, typically you only care about version and run subcommands.

completion allows to generate completion files (when you press tab after typing farmerbot, a suggestion list will be shown), similar to https://dgraph.io/docs/howto/completion/ 

I'm not sure I got your question, do you want to document help subcommand? All it does is showing help for the subcommand and its flags like that
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/64129/f2b03997-19fe-4a6c-8339-36df08b6cfa6)

**Comment by A-Harby** [comment]
Just to add a command description in the docs for the version, completion, and other.
