### ISSUE TITLE
🐞 [Bug] TF Grid CLI: Update docs 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#813]
### What happened?

This link is outdated.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/08daf31c-12ef-49e2-878f-b749dc36b94e)

And is [Contracts](https://github.com/threefoldtech/tfgrid-sdk-go/blob/development/grid-cli/docs/contracts.md#contracts) command only getting the contracts deployed via CLI or all the contracts on the account?

### which network/s did you face the problem on?

Dev

**Comment by AbdelrahmanElawady** [comment]
Contract command works with any contract whether deployed by the cli or any other tool

**Comment by Eslam-Nawara** [comment]
Verified
- Broken mnemonics link is now removed
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/ba983993-656e-4bb0-a0ca-33f7eac22d92)

- `get contracts` command return contracts deployed by any deployment tool
shown in this comment: [- #882#issuecomment-1971301618](https://github.com/threefoldtech/tfgrid-sdk-go/issues/882#issuecomment-1971301618)

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/4e973702-1974-418e-9f9c-3e5748f8ee12)

**Comment by rawdaGastan** [comment]
Mentioned here:

- https://github.com/threefoldtech/tfgrid-sdk-go/issues/882#issuecomment-1971301618
- https://github.com/threefoldtech/tfgrid-sdk-go/issues/882#issuecomment-1971301618
