### ISSUE TITLE
tfrobot: output log file

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#814]
### Is your feature request related to a problem? Please describe

I'd like to have the ability to add full debug logs so in case of long retries or failures I'm not limited to the screen history lines

### Describe the solution you'd like

either describe how to redirect/ or duplicate using tee, stderr and stdout to a file in docs or create a log file

**Comment by AbdelrahmanElawady** [comment]
Verified:

Mentioned in Readme how to pipe logs to a file using `tee`: https://github.com/threefoldtech/tfgrid-sdk-go/tree/development/tfrobot#logs
