### ISSUE TITLE
tfrobot: rename mass-deployer directory to tfrobot

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#815]
### Is your feature request related to a problem? Please describe

tfrobot: rename mass-deployer directory to tfrobot

### Describe the solution you'd like

tfrobot: rename mass-deployer directory to tfrobot

**Comment by AbdelrahmanElawady** [comment]
Verified:

Binaries under release section are named `tfrobot`. Also, path updated in repo to be under `tfrobot` not `mass-deployer`.
https://github.com/threefoldtech/tfgrid-sdk-go/tree/development/tfrobot
