### ISSUE TITLE
🐞 [Bug] FarmerBot: add key type pair in the `.env` file 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#821]
### What happened?

v0.14.1.

The only way to change the key type pair is by using the command option -k, but what if I want to use the file or in Docker?

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/08ed56f6-0535-4071-a7ed-833f1e6ab015)

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
.
```

**Comment by xmonader** [comment]
Did you try `KEY_TYPE` ?

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/64129/cb531a0e-2722-4a2b-a942-cbcaa2d7c420)
