### ISSUE TITLE
🐞 [Bug] Farmerbot: Validation for running multiple command at once 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#823]
### What happened?

There should be validation to prevent using more than one command.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/a8a887f1-be27-4bc2-8fdf-41e138356ee0)

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
farmerbot run start -c farmerbot_config.yml -e .env -d
```

**Comment by xmonader** [comment]
Addressed in https://github.com/threefoldtech/tfgrid-sdk-go/pull/849
