### ISSUE TITLE
Unify workloads metadata across clients

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-go#828]
## Description

As mentioned in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2164 there are some differences between both clients that cause the user experience to be degraded especially on the dashboard. So, unifying both clients would make it easier for deployments to be fetched and presented across different tools (terraform, cli, dashboard, etc...).

## Suggested changes

The metadata for specific solutions are not handled by go client (Taiga, PeerTube, etc...) as the client treats them all the same as VMs with different flists but it should be the user's responsibility to match the format given in the parent issue in order for it to be listed on the dashboard. But we will handle the default values for different workloads to be listed as just VMs and also to support updating Networks in both clients.

All metadata will also have `version` field, currently set to 3.

### VM

The default metadata for any VM should look like:

```json
{"version": 3, "type":"vm","name":"<name>","projectName":"vm/<name>"}
```

### Kubernetes

The default metadata for any Kubernetes master and workers should look like:

```json
{"version": 3, "type":"kubernetes","name":"<name>","projectName":"<name>"}
```

### Network

Mainly two options:

- Add the IPs used per network workload to its workload metadata.
- Calculate IPs from all deployments for a user on the node that network is on to get this information. This won't require metadata changes but possibly more requests to the node.

**Comment by Eslam-Nawara** [comment]
WIP: 
- update all workloads to have version and set to 3.
- update project name default of vms to be vm/<name>.
- update project name default of k8s to be `.
- update grid-cli and tfrobot to use new project name format for vms.

**Comment by Eslam-Nawara** [comment]
WIP: 
Testing the new update for compatibility with deployments with the old versions

- Creating deployment with the old format:
```console
➜  grid-cli git:(development) ./bin/tfcmd deploy vm --name cliTest --ssh ~/.ssh/id_rsa.pub
11:52AM INF starting peer session=tf-155307 twin=4653
11:52AM INF deploying network
11:53AM INF deploying vm
11:53AM INF vm planetary ip: 302:9e63:7d43:b742:85ef:2cbe:d554:b95b
```

- Loading the deployment with the new version:
```console 
➜  grid-cli git:(development-update-workloads-metadata) ./bin/tfcmd get vm cliTest
11:54AM INF starting peer session=tf-158414 twin=4653
11:54AM INF vm:
{
        "Name": "cliTest",
        "NodeID": 11,
        "SolutionType": "cliTest",
        "SolutionProvider": null,
        "NetworkName": "cliTestnetwork",
        "Disks": [],
        "Zdbs": [],
        "Vms": [
                {
                        "name": "cliTest",
                        .
                        .
                        .
                        .
                }
        ],
        .
        .
        .
        .
        "IPrange": "10.20.2.0/24"
}
```

- Canceling the deployment:
```console
➜  grid-cli git:(development-update-workloads-metadata) ✗ go run main.go cancel cliTest
12:54PM INF starting peer session=tf-234570 twin=4653
12:54PM INF canceling contracts project name=cliTest
12:54PM INF project is canceled project name=cliTest
12:54PM INF canceling contracts project name=vm/cliTest
12:54PM INF project is canceled project name=vm/cliTest

```

**Comment by AbdelrahmanElawady** [comment]
Network metadata now has been updated to be the same as described in TS issue. The new format will look like this:
```json
{
  "version": 3,
  "user_accesses": [
    {
      "subnet": "10.20.2.0/24",
      "private_key": "6Ii9rJwLU7AKEdg4+xMo7YFNfPCunrFllUqcgVo2pFs=",
      "node_id": 11
    }
  ]
}
```

and it will still work with previous network metadata format.

**Comment by AhmedHanafy725** [comment]
zdb metadata needs to be updated to be consistent with the others
```json
{"version": 3, "type":"zdb","name":"<name>","projectName":"zdb/<name>"}
```
as it shows on the contracts list on the dashboard as `vm`. check https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2164#issuecomment-1976498491

**Comment by Eslam-Nawara** [comment]
Default gateways metadata now has been updated to be the same as described in TS issue(same as the gateway name). The new format will look like this:
```json 
{"version":3,"type":"Gateway Fqdn","name":"gateway","projectName":"gateway"}
```

**Comment by Omarabdul3ziz** [comment]
verified by deploying two micro vms from the two clients

the metadata from the go-client
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/32527347/ffe73a0a-8263-43ce-9fc4-30f63d977500)

the metadata from the ts-client
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/32527347/35a9c6db-86dc-48af-aa86-2c397e92ea50)

also the network workload follow the same metadata structure
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/32527347/5fa79996-0d28-4025-b0d6-b4e214318cf5)
