### ISSUE TITLE
🐞 [Bug] Farmerbot: Node usage meaning

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#830]
### What happened?

Does the usage here mean that the node has 1% of the resources used by a workload? 
And if so, how did it go to standby if it had a workload? 
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/bb742769-b232-45b5-b3ca-e9f3f13efb93)

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
.
```
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/522eeb8b-5185-436b-9e30-54dbbb0a3e6e)

**Comment by xmonader** [comment]
As we talked earlier, the resources in zos node are never zero, there's a space that the OS reserves and ofc more resources for the base system
