### ISSUE TITLE
🐞 [Bug] Farmerbot:  wake_up_threshold doesn't work

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#831]
### What happened?

I configured the farmerbot to wake_up_threshold of 40% and used farm 4420, where node 156 is on and node 155 is on standby, and after calculating percentage needed for 40% percent I deployed a contract with 40% resource on node 156, and I was expecting node 155 to wake up as the threshold had been passed, but nothing happened.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/339eb6cb-960a-4767-b21a-a7afd1dab27d)

### which network/s did you face the problem on?

Dev

### Twin ID/s

5754

### Node ID/s

155, 156

### Farm ID/s

4420

### Contract ID/s

87502

### Relevant log output

```console
farm_id: 4420
included_nodes:
- 155
- 156
excluded_nodes:
- 148
- 149
power:
  periodic_wake_up_start: "06:00PM"
  wake_up_threshold: 40
  periodic_wake_up_limit: 10
  overprovision_cpu: 1
```

**Comment by rawdaGastan** [comment]
@A-Harby 
Because minimum threshold is `50` if you noticed there are some warnings adjusting the threshold when starting the farmerbot
