### ISSUE TITLE
Farmerbot: periodic_wake_up and overprovision_cpu questions

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#832]
### Is your feature request related to a problem? Please describe

First: periodic_wake_up, It is the daily time to wake up nodes for your farm to check if they are still working or not, but how long does this wake-up time take?
It did start at 6 and kept going.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/dcca77e5-123c-4827-b6ac-486b484b05cf)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/1fdfca6e-a7f3-47e8-8147-f7e4fd038228)
How long does it take to check, and can we add that info to the docs.

### Describe the solution you'd like

Second: overprovision_cpu; in the docs, it is how much node allows overprovisioning the CPU, but from other nodes and manuals, I thought that the default was 4, and it can always be overprovisioned to 4.
So why would we change it, and does that mean that this node will have a different node case from all the others?
And if so, doesn't it mean that we will need to change the CPU overprovisioning in all the clients?

**Comment by A-Harby** [comment]
And also, why would it run twice in one day? I thought it was daily.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/7b57633a-1de5-41c7-b826-68bfd87c1b26)

**Comment by rawdaGastan** [comment]
@A-Harby I am not sure what do you mean by kept going? do you mean the reporting time?

**Comment by xmonader** [comment]
@A-Harby still needing support? I thought I answered all of your questions when we were at the office
