### ISSUE TITLE
🐞 [Bug] TFRobot: example is missing in the docs 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#840]
### What happened?

The example is missing.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/fcf8d248-ae40-4ba5-8a41-30c5beb4e31e)
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/5493ac77-89ef-4704-b188-b98b53c32cfa)

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
.
```

**Comment by xmonader** [comment]
thanks, should be fixed in fed0436b0a7a158d15cc3d1ee4b0e5a0bb58c7ce

**Comment by Eslam-Nawara** [comment]
the examples were restored here https://github.com/threefoldtech/tfgrid-sdk-go/commit/b24c03616793705f1b7f6b750358af9701cd3064

**Comment by A-Harby** [comment]
Verified. 

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/93e2650c-b98f-4d0f-95f4-64925e58f1f9)
