### ISSUE TITLE
🐞 [Bug] TFRobot: is it mount or mount_point 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#841]
### What happened?

Is it a mount or a mount_point?
Both succeed in deployment (that mean no validation is applied in this case), but only with mount_point the mount point was changed on the deployment disk.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/650f985c-d23a-4b70-9e19-77975466c781)

### which network/s did you face the problem on?

Dev

### Relevant log output

```console
ssd:
      - size: 15
        mount_point: '/mnt/ssd'
```

**Comment by xmonader** [comment]
in the json and the yaml the key is `mount_point`	
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/64129/199e1c73-9102-405d-8a3b-e9f6fdddbcb6)


Fixed in a19f6d81c7b7aeb1a95d9e6ddf9345b55a72c6a3

**Comment by A-Harby** [comment]
verified,
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/6aff24d1-bcf0-4245-ac83-912f6bc52396)
