### ISSUE TITLE
Add recently added mnemonics server arg to Makefile's start script

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgrid-sdk-go#86]
## Describe the bug
- `mnemonics` arg should be added to the **Makefile** start script.

## Screenshots
![Screenshot from 2023-04-17 15-50-04](https://user-images.githubusercontent.com/42457449/232507291-835b9f2d-9b69-4ea3-b3d9-54f02c2357bb.png)

**Comment by sameh-farouk** [comment]
**Update**:
PR submitted with a fix

**Comment by A-Harby** [comment]
Verified 
Renamed start to `server-start` and restart to `all-start`
![image](https://user-images.githubusercontent.com/109473873/234633698-2edf3f0b-2eba-45dd-a7d3-8c86e785c890.png)
Mnemonics are added to mark file
![image](https://user-images.githubusercontent.com/109473873/234642330-09de9711-ac48-4cd3-8f76-bcfa02018550.png)
and when add mnemonics, it works fine
![image](https://user-images.githubusercontent.com/109473873/234643168-c2786e80-4f3c-46a7-9f11-aaa641ad1be1.png)
