### ISSUE TITLE
Refactor deployment deployer to stop using the host IDs in the network state 

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/tfgrid-sdk-go#868]
### Is your feature request related to a problem? Please describe

Saving host IDs in network state is not needed anymore since we added list_private_ips call: https://github.com/threefoldtech/zos/pull/2206

### Describe the solution you'd like

refactor deployment deployer to stop using the host IDs in the network state.

**Comment by AbdelrahmanElawady** [comment]
Verified:

HostIDs was removed from network state [here](https://github.com/threefoldtech/tfgrid-sdk-go/blob/788850c024a1b72f4422cf7a49fcddf61bc5b65b/grid-client/state/network_state.go#L11-L19) and list_private_ips is used [here](https://github.com/threefoldtech/tfgrid-sdk-go/blob/788850c024a1b72f4422cf7a49fcddf61bc5b65b/grid-client/deployer/deployment_deployer.go#L228)
