### ISSUE TITLE
Use deployment.list RMB call in tfrobot

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-go#871]
### Is your feature request related to a problem? Please describe

tfrobot currently gets deployments using deployment.get concurrently, which works fine but leads to a lot of RMB calls. 

### Describe the solution you'd like

We can improve that by using deployment.list to get all the deployments on one node to limit number of requests and be a little bit faster

**Comment by Eslam-Nawara** [comment]
Verified: 
tfrobot uses `nodeClient.DeploymentList()` [here](https://github.com/threefoldtech/tfgrid-sdk-go/blob/0552f9961c051f3c5158b702254f5d8c8009796d/tfrobot/pkg/deployer/load.go#L204), which uses zos call `zos.deployment.list` as requested
