### ISSUE TITLE
🐞 [Bug]: Tried to deploy vm with public ip using `grid-cli` but it panicked 

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-go#879]
### What happened?

![Screenshot from 2024-02-29 11-39-09](https://github.com/threefoldtech/tfgrid-sdk-go/assets/54944491/44e3bdd9-0ce0-4896-885b-099f524f965b)

### which network/s did you face the problem on?

Dev

### Twin ID/s

5110

**Comment by AbdelrahmanElawady** [comment]
It was an issue with the node filter that didn't return an error when no nodes are found when no limit was specified. Should be fixed now:

```console
$ bin/tfcmd deploy vm --name te12345678 --ssh ~/.ssh/id_rsa.pub --ipv4
12:17PM INF starting peer session=tf-1376586 twin=192
12:17PM FTL failed to get node for required vm specs error="could not find enough nodes with options: free_ips: 1, rented: false, available_for: 192, healthy: true, status: up, free_mru: 1073741824, free_sru: 2147483648, farm_ids: 1"
```
