### ISSUE TITLE
update health indexer to use zos.system.diagnostics

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/tfgrid-sdk-go#891]
### Is your feature request related to a problem? Please describe

currently, we decide if the node is healthy or not based on just its response of the rmb call `zos.system.version`

### Describe the solution you'd like

we can use the call `zos.system.diagnostics` instead, and make the node health depend on the `SystemOk` in the response

**Comment by rawdaGastan** [comment]
### Verification

- `zos.system.version` isn't used now and `zos.system.diagnostics` is used instead
