### ISSUE TITLE
use a custom httpclient with timeouts

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-go#892]
## Describe the bug

Most of our code is using `http.Get` depending on the default go's http client behavior which is no timeout which can leads to 
- stalling execution
- resource leakage

Create a custom client whenever needed and set the proper timeout based on the operation 

## Screenshots

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/64129/c937ff65-3c78-4bce-b7bc-e6e9ef15a5ad)

**Comment by Eslam-Nawara** [comment]
Verified: 
now our code is using customized http client with timeout set to 10s in grid-client, monitoring-bot, tfrobot and relay cache warmer
