### ISSUE TITLE
Use suitable timeout per component

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-go#894]
## Description

Currently, all http requests are done with 10 seconds timeout. This might be a lot or not enough based on what's doing the request. We should fine tune it for each request to be suitable for it. If 10 seconds turned out to be fine, we can close this issue.

**Comment by rawdaGastan** [comment]
Related issues

- https://github.com/threefoldtech/tfgrid-sdk-go/issues/892

**Comment by rawdaGastan** [comment]
Already done
