### ISSUE TITLE
codeql failure

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/tfgrid-sdk-go#896]
codeql fails to scan code

- https://github.com/threefoldtech/tfgrid-sdk-go/security

**Comment by xmonader** [comment]
@AbdelrahmanElawady what did you do -_-

**Comment by AbdelrahmanElawady** [comment]
@xmonader I did not know our code was that bad

**Comment by AbdelrahmanElawady** [comment]
The reason for the issue is explained [here](https://github.com/github/codeql-action/issues/2186). It is fixed now and runs with no errors: https://github.com/threefoldtech/tfgrid-sdk-go/actions/runs/8464114977/job/23188181063
