### ISSUE TITLE
Support more than one filter together in proxy.

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-go#911]
### Is your feature request related to a problem? Please describe

- For example i wanna get all my rent contracts, but i wanna show both `Created` and `GracePeriod`.
- but how to do that and paginate them if i only get one of them in the request ?

### Describe the solution you'd like

- I'd like to filter and get both my contracts `Created` and `GracePeriod` together in one call.

**Comment by Eslam-Nawara** [comment]
Verified:
requested contracts in created and grace period states and the filtration worked as expected, the list had contracts with both Created and in GracePeriod states and no contracts in Deleted state
https://gridproxy.dev.grid.tf/contracts?size=9999&state=GracePeriod,Created 

![Screenshot from 2024-06-10 16-07-11](https://github.com/threefoldtech/tfgrid-sdk-go/assets/67752395/2ad71036-8751-4ae6-8914-f1347643dbcf)
