### ISSUE TITLE
add support for multiple rmb relays in the rmb sdk

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/tfgrid-sdk-go#917]
### Is your feature request related to a problem? Please describe

rmb-peer supports connecting to multiple relays for redundancy. This feature allows the rmb-peer to continue operating if one of the relays is facing technical problems.

It also allows messages to be balanced between multiple relays.

### Describe the solution you'd like

Support for multiple relays need to also be implemented in the go client

**Comment by rawdaGastan** [comment]
### WIP

- Investigating twin updates on different relays when multiple relays are supported

**Comment by Omarabdul3ziz** [comment]
verified:
used my mnemonic which has only one relay configured to make an rmb call using the rmb-sdk peer and added two relays with the option `WithRelay()`  
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/32527347/d1087549-3a34-40d1-883e-b77c1de950b2)

and my twin relays is updated, the two relays hostnames separated by `_`
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/32527347/65d7ec9c-a9fb-4d77-b46c-d8924b2b2d08)
