### ISSUE TITLE
🐞 [Bug]: rmb-sdk-go Peer router middlewares not working

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-go#924]
### What happened?

Peer router method `Use` accepts middlewares but does not actually use them.

### which network/s did you face the problem on?

Dev

**Comment by rawdaGastan** [comment]
### Tested on farmerbot

- auth middleware for power subroutes

```console
$ cd ../poweroff && go run main.go
2024/03/07 12:44:58 you are not authorized for this action. your twin id is `81`, only the farm owner with twin id `164` is authorized
exit status 1

$ cd ../poweron && go run main.go
2024/03/07 12:45:05 you are not authorized for this action. your twin id is `81`, only the farm owner with twin id `164` is authorized
exit status 1

$ cd ../includenode && go run main.go
2024/03/07 12:45:19 you are not authorized for this action. your twin id is `81`, only the farm owner with twin id `164` is authorized
exit status 1
```

- Tried `version` sub route and worked fine without the middleware
```console
$ cd ../version && go run main.go
version: v0.14.11
```

**Comment by AbdelrahmanElawady** [comment]
Verified:

Tried it in this [commit](https://github.com/threefoldtech/zos/pull/2223/commits/b355d9f09abc6688ef068e145b37fb2882130d2f) and worked fine.

requests to the node under `admin` subroute responded with "unauthorized" (if not the farm owner)
