### ISSUE TITLE
🐞 [Bug]: fqdn test fails (needs fqdn points to a node in each network)

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/tfgrid-sdk-go#931]
### What happened?

fqdn integration test fails

### which network/s did you face the problem on?

Dev, QA, Test, Main

### Relevant log output

```console
NA
```

**Comment by AhmedHanafy725** [comment]
IMO, I don't prefer to have an integration test for fqdn. Too much hassle for the maintenance (node went down or the ipv4 is changed,...)

**Comment by xmonader** [comment]
Only test manually for now
