### ISSUE TITLE
🐞 [Bug]: Farmerbot complains about invalid or unset relay addresses

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-go#948]
### What happened?

We have several farmers reporting that they see errors from farmerbot regarding invalid or unset relay addresses associated with node twins, when those twins all have `relay.grid.tf` set.

Here's one example from a farmer trying to set up the farmerbot for the first time:

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/17682591/2c435188-73eb-40a4-a768-788edff76e35)

Another from a farmer who's been running the bot with a working setup for a while:

![tg_image_4210451017](https://github.com/threefoldtech/tfgrid-sdk-go/assets/17682591/51b18060-eb40-435c-8cbf-24296902f23b)

One more:

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/17682591/6198e65a-bb5e-41e3-8658-4bbd2a819185)

**Comment by scottyeager** [comment]
Findings after a bit more research:

* While I'm not 100% sure the issue in the first screenshot is related to the other two, it seems like a variant of the issue seen when a twin doesn't have a relay set (that said, I couldn't find a twin with unset relay associated with either the farm or node)
* `InvalidRelayAddress` is an error coming from tfchain. It's thrown from `validate_relay_address`, which is only called when a twin is created or updated
* So it seems somehow a call to update the farm's twin is being made when farmerbot tries to set a node's power target on TF Chain, but with an invalid relay address

**Comment by rawdaGastan** [comment]
what is the version of the farmerbot used?

**Comment by TullysInc** [comment]
> what is the version of the farmerbot used?

It's the latest version.

**Comment by rawdaGastan** [comment]
I don't think it is the latest. Logs from previous versions

**Comment by scottyeager** [comment]
Seems indeed resolved by updating to `v0.14.12`.
