### ISSUE TITLE
🐞 [Bug]: [grid-cli] deploying vm auto generates mycellium ip

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-go#955]
### What happened?

When using the grid-cli to deploy a virtual machine (VM), the tool automatically generates a Mycelium IP address without adding any flag for it. 
<img width="582" alt="Screenshot 2024-03-17 at 12 17 53 PM" src="https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/67c48e11-ce91-4f23-9591-837cc16c1187">
is it mandatory for the user to deploy a vm with Mycelium?

### which network/s did you face the problem on?

Dev, QA, Test, Main

```console
12:15PM INF starting peer session=tf-52391 twin=7606
12:15PM INF deploying network
12:15PM INF deploying vm
12:15PM INF vm planetary ip: 300:1b0f:ec2d:be82:1662:7967:a5b9:afd9
12:15PM INF vm mycelium ip: 4c8:3f9e:faa6:acd1:ff0f:7d37:ab24:809
```

**Comment by AbdelrahmanElawady** [comment]
It is not a bug, it is intended to add both ygg and mycelium and the user can connect with whatever they want.

You can turn it off with `--mycelium=false` the same way as ygg `--ygg=false`.
