### ISSUE TITLE
swagger vs swagger/index.html

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-go#97]
The root url of the proxy shows this message:

```
"Welcome to threefold grid proxy server, available endpoints [/farms] [/stats] [/nodes] [/gateways] [/twins] [/contracts] [/nodes/{node_id:[0-9]+}] [/gateways/{node_id:[0-9]+}] [/nodes/{node_id:[0-9]+}/status] [/gateways/{node_id:[0-9]+}/status] [/ping] [/] [/version] [/swagger] "
```

But `/swagger` gives a 404 and the full url needed is `/swagger/index.html`.

Suggest to either update the welcome message or redirect.

**Comment by sameh-farouk** [comment]
**Update:**
PR with a fix submitted

welcome message updated to `swagger/` where it would be redirect to `swagger/index.html`

**Comment by A-Harby** [comment]
> **Update:** PR with a fix submitted

Is it yet released?

**Comment by sameh-farouk** [comment]
@AhmedHanafy725 not released yet

**Comment by xmonader** [comment]
redirects to /swagger/index.html
