### ISSUE TITLE
Update rmb-peer with the latest envelope data

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-go#977]
## Description

rmb-relay v1.3.0 added a new optional `relays` field that is part of the Envelope to avoid chain updates delay: https://github.com/threefoldtech/rmb-rs/blob/v1.3.0/proto/types.proto#L75
This new field should have the current relays for the twin sending a request to a relay. It should be a list of relays in the format `<hostname>`, for example: `relay.dev.grid.tf` and `relay.dev.02.grid.tf`. neither protocol or port should be added (`wss` or `:443`).

Reference [PR](https://github.com/threefoldtech/rmb-rs/pull/194) and [Issue](https://github.com/threefoldtech/rmb-rs/issues/189)

**Comment by Omarabdul3ziz** [comment]
verified:
- the relays field is added to the challenge hash
- tested an rmb call between:
  - zos node at version `3.10.5` that uses rmb-peer version `1.3.0`
  - local client uses the latest rmb-sdk peer
  and call succeeded
