### ISSUE TITLE
Node wake priority

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-go#978]
### Is your feature request related to a problem? Please describe

Currently the farmer has no control over the order in which farmerbot wakes their nodes.

### Describe the solution you'd like

Allow priority for which nodes to wake first to be specified in the config file. This could be as simple as waking them in the order they are written in the file.

**Comment by A-Harby** [comment]
Verified, Qanet and version v0.15.9.

I tested on farm 180 with 3 nodes: 26, 29, and 28, and set the priority first to node 26 and filled node 28 with deployment to pass the threshold.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/5b2a2ce3-f288-4b68-ac8b-d7d7fb902b00)

And node 26 was the node to wake up after, as I specified in the config file.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/44a9ecfb-44fc-45eb-8102-98324d3a6a6d)


Then I reset everything and started all over again, but this time with node 29 as the priority node, I did the same, and as expected, the node I specified was woken up.
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/109473873/5bfea2e7-b986-4795-a712-f8d9c044aac7)

[TC2718 - Farmer Bot Installation with priority_nodes](https://app.testlodge.com/a/26076/projects/40893/suites/221831?expand_section=382401#case_4295012)
