### ISSUE TITLE
Automatic or command based farmerbot update

### ISSUE THREAD

**Issue by StmLord** [threefoldtech/tfgrid-sdk-go#984]
### Is your feature request related to a problem? Please describe

when I see a new farmerbot upgrade I'm afraid to download it start it and make the config again, incase I do something wrong and it will hit my farm rewards with penalties.
I would prefer a automatic update to the latest version, or a command that will safely update without more intervention from farmers side.

### Describe the solution you'd like

An added Farmerbot Update command that will take care of everything, like removing and re-installing service and re-use the config files.

**Comment by xmonader** [comment]
Hi this repo only provides just the core of the farmerbot, however the scripts provided by Scott is responsible for more

@scottyeager please see if you can provide a subcommand to your script e.g `stable or something`
