### ISSUE TITLE
Include the Workloads info in the stats endpoint

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-go#985]
### Is your feature request related to a problem? Please describe

To add a new card to the dashboard stats page we need to access the workload key from the object which should hold the number of workloads that exist on the network

### Describe the solution you'd like

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/57001890/7918555e-893d-47de-b8a3-44e2d982d74a)

https://gridproxy.dev.grid.tf/stats

**Comment by xmonader** [comment]
@Omarabdul3ziz please see if feasible

**Comment by Omarabdul3ziz** [comment]
done and on dev now ya omda @Mahmoud-Emad
