### ISSUE TITLE
🐞 [Bug]: Farmerbot log file issue.

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/tfgrid-sdk-go#989]
### What happened?

The farmer log command is not working, but the other command works. Even after restarting the farmerbot, the issue remains the same.

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/95933607/34a12be3-0a69-4d42-89d2-9cbf54fe68cf)

Here is the systemctl status Farmerbot -l

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/95933607/f1933ed6-269d-4a0d-bb39-199a5173e9ae)

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/95933607/7d43457a-f37c-4f3c-afbe-fee4a16c287b)

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/95933607/ef823dc7-3367-411d-9b74-9b6692f14810)

 find / -name "*.log"

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/95933607/85dfc6cf-7f60-46ca-a6c5-fdc9e231aef2)

### which network/s did you face the problem on?

Main

### Relevant log output

```console
Even directory command does not work either.
find ~/ -name '*.log'

![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/95933607/844e6846-01f6-4951-a19d-cc2851f0c876)
```

**Comment by rawdaGastan** [comment]
We don't support generating a log file, you can redirect your logs to any file you want.

**Comment by shng4you** [comment]
@rawdaGastan Thank you for the update.

**Comment by rawdaGastan** [comment]
I will close the issue. Let me know if anything is not clear.

**Comment by mahendravarmayadala93** [comment]
> We don't support generating a log file, you can redirect your logs to any file you want.

Hey @rawdaGastan! Could you please explain how to do this? Thank you very much.

**Comment by xmonader** [comment]
after typing the command add ` >> farmerbot.log` or depend on the farmerbot install script that uses systemd features e.g 

```
RestartSec=5
StandardOutput=append:${pwd}farmerbot.log
StandardError=append:${pwd}farmerbot.log
```
