### ISSUE TITLE
Support new volume workload

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-go#993]
## Description

A new Volume workload has been [added](https://github.com/threefoldtech/zos/pull/2270) to ZOS. It should act the same as ZMounts with some extra enhancements in performance as it go through less layers of virtualization.

Volumes work with container images out of the box and our official VM images. For custom VM images `virtiofs` module must be enabled in the image kernel.

> Note: raw images are not supported

## Interface

The new workload is of type `volume` and has the same structure as ZMount:
```json
{
    "size": <size-in-bytes>
}
```

**Comment by Omarabdul3ziz** [comment]
done and verified on this sdk-go packages (cli, tfrobot)
gonna be on 3.16 for (tf, pulumi)
- https://github.com/threefoldtech/pulumi-threefold/issues/440
- https://github.com/threefoldtech/terraform-provider-grid/issues/928
