### ISSUE TITLE
🐞 [Bug]: grid cli  gets unclear error when getting a vm details

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-go#995]
### What happened?

used the command to get vm details after deploying it gets an unclear error with the deployment details
<img width="553" alt="Screenshot 2024-04-30 at 9 00 10 PM" src="https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/2132238f-221d-4be6-a4a8-a757de94bf9a">

or

<img width="586" alt="Screenshot 2024-04-30 at 9 21 42 PM" src="https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/7be90fac-8ad5-441b-a93f-51e8d3ef72bb">

```
khaledyoussef@Khaleds-Air ~ %  get vm examplevm 
9:20PM INF starting peer session=tf-20146 twin=56
9:20PM FTL error="could not validate rmb proxy server: Get \"https://gridproxy.qa.grid.tf/ping\": net/http: TLS handshake timeout"
```

### which network/s did you face the problem on?

QA

### Relevant log output

```console
8:59PM FTL error="invalid character 'o' looking for beginning of value"
```
go version go1.21.6 darwin/arm64

**Comment by khaledyoussef24** [comment]
also getting the same error for deleting
```
khaledyoussef@Khaleds-Air ~ % tfcmd cancel examplevm
9:23PM INF starting peer session=tf-20570 twin=56
9:23PM INF canceling contracts project name=vm/examplevm
9:23PM FTL error="could not load contracts for project vm/examplevm: invalid character 'o' looking for beginning of value"
```

<img width="573" alt="Screenshot 2024-04-30 at 9 24 18 PM" src="https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/f3dea814-ed18-4c65-be43-c573dc13d294">

**Comment by khaledyoussef24** [comment]
<img width="525" alt="Screenshot 2024-04-30 at 9 36 10 PM" src="https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/ef5f0291-66db-4e30-99ab-1f00a688aee5">
same for k8s details

**Comment by xmonader** [comment]
How did you deploy these things in the first place?

**Comment by AbdelrahmanElawady** [comment]
also if possible can you list deployed contracts too?

**Comment by khaledyoussef24** [comment]
@AbdelrahmanElawady Listing all contracts is possible but getting info for one deployment is not working

**Comment by Omarabdul3ziz** [comment]
verified on dev net:
- i managed to deploy/get/delete vm 
- getting the deployment contracts
- also could get a deployment created with ts-client

i am not sure if this is enough, @khaledyoussef24 could you please try to see if the issue still exists?
