### ISSUE TITLE
🐞 [Bug]: Grid cli getting an error while deleting all contracts

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-go#998]
### What happened?

gridcli getting an error when deleting all contracts but working fine in one contract.
also fails to delete while deleting by solution name `tfcmd cancel <deployment-name>`

go version go1.21.6 darwin/arm64
the binary [v0.15.1](https://github.com/threefoldtech/tfgrid-sdk-go/releases/tag/v0.15.1)

<img width="572" alt="Screenshot 2024-05-01 at 10 48 37 AM" src="https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/77e4b627-d923-4d21-8ad4-7862a1553aa4">
(no contracts were deleted )

### which network/s did you face the problem on?

Dev, QA

### Relevant log output

```console
10:46AM FTL error="all not a valid contract id: strconv.ParseUint: parsing \"all\": invalid syntax"
```

**Comment by xmonader** [comment]
Where is all param documented? To me the error sounds like it needs a uint, also please "getting error in the title isn't enough"

Component: summarized error eg tfcmd: all is invalid argument in canceling contracts

**Comment by khaledyoussef24** [comment]
I followed the documents in the deletion process and i found all pram but I missed the -- but it still miss behaves some time
tried it again now and it worked
<img width="613" alt="Screenshot 2024-05-01 at 11 55 58 AM" src="https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/787faeee-cbe5-4511-9c91-0172d9cfebcb">

(contracts are deleted but got the same error as mentioned [here](https://github.com/threefoldtech/tfgrid-sdk-go/issues/996))
<img width="564" alt="Screenshot 2024-05-01 at 11 58 41 AM" src="https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/52360761-06d8-4100-811a-48481cc79582">

for deleting a unit per time it did not work and always misbehaving  like this :
here is a contract for the vm called kube : 
<img width="522" alt="Screenshot 2024-05-01 at 11 52 50 AM" src="https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/79f7e1d9-0b22-47b0-8fc3-147aff7daa9f">
it should be canceled like documented here : 
<img width="886" alt="Screenshot 2024-05-01 at 11 55 29 AM" src="https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/93b8ab7a-f746-457b-8623-cd72ba9b77e9">
<img width="566" alt="Screenshot 2024-05-01 at 12 04 55 PM" src="https://github.com/threefoldtech/tfgrid-sdk-go/assets/110984055/ce171dba-8d34-4158-bbf1-9b264bc2f1e9">

**Comment by xmonader** [comment]
open the issue you have with `--all` please in a new ticket i'll close this one
