### ISSUE TITLE
🐞 [Bug] TFrobot: is flist mentioned on the docs working?

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-go#999]
### What happened?

[v0.15.1](https://github.com/threefoldtech/tfgrid-sdk-go/releases/tag/v0.15.1)

Is the image in the TFRobot docs is working?
I tried different deployments, and it didn't work for me, and then I changed flist to ubuntu, and it worked.

but with `flist: https://hub.grid.tf/mariobassem1.3bot/threefolddev-holochain-latest.flist`, it keeps giving me connection refused.
https://github.com/threefoldtech/tfgrid-sdk-go/blob/development/tfrobot/README.md#download

### which network/s did you face the problem on?

Dev, QA

### Relevant log output

```console
- name: batta_vmg1
    vms_count: 1 # amount of vms with the same configurations
    node_group: group_2 # the name of the predefined group of nodes
    cpu: 2 # number of logical cores
    mem: 2 # amount of  memory in GB
    public_ip4: false
    public_ip6: false
    flist: https://hub.grid.tf/mariobassem1.3bot/threefolddev-holochain-latest.flist
    entry_point: /usr/local/bin/entrypoint.sh
    root_size: 0 # root size in GB, 0 is the default
    ssh_key: example1 # the name of the predefined ssh key, will be defined below
    env_vars:
      key1: val1
```

**Comment by xmonader** [comment]
@Eslam-Nawara please update it to use ubuntu vm

**Comment by Eslam-Nawara** [comment]
Work Completed:
- Updated the readme example to use Ubuntu flist for vms.
